### ISSUE TITLE
Citrus not populating varargs into docker container properties correctly

### ISSUE THREAD

**Issue by blessedchitamba** [citrusframework/citrus#1008]
Version - 3.4.0

**Expected behaviour**: 
When using the ```DockerExecuteAction.builder``` to create docker containers as shown in the code snippet below, methods marked as ```methodName(String... properties)``` using vararg format in the source code are supposed to properly add the properties onto the docker container. The example below shows me trying to set environment variables

```
import static com.consol.citrus.docker.actions.DockerExecuteAction.Builder.docker;
.
.
.
	$(docker().client(dockerClient)
               .create(my_image_name)
               .name("my_container")
               .env("ENV_1=True", "ENV_2=false", "ENV_3=true")
              .validateCommandResult(new CommandResultCallback<CreateContainerResponse>() {
                       @Override
                       public void doWithCommandResult(CreateContainerResponse rsp, TestContext context) {
                                       System.out.println(rsp);
                      }
            }));
```

**Actual behaviour:**
The environment variables get populated as an object reference. This is because when they are populated into the command, they are not unpacked properly. The image below is the output of a ```docker inspect container```. 
![image](https://github.com/citrusframework/citrus/assets/40063222/e83e580b-624b-4179-8831-20ad38f1fa2d)

**Suspicion:**
The method call to ```getParameters()``` here returns a ```Map<String, Object>``` and putting ```String... env``` results in an Object type being put in the map. 
![image](https://github.com/citrusframework/citrus/assets/40063222/5dc99e6f-df07-4796-91fb-7b7c576672ae)

**Comment by bbortt** [comment]
thanks for the detailed report! I assume that the underlying java-docker implementation changed (we're using third party there) and you would have to change the way the `String[]` environment variables get passed here: https://github.com/citrusframework/citrus/blob/82d985f4d588d35b36718062dcc5ab35bddf9ffb/connectors/citrus-docker/src/main/java/org/citrusframework/docker/command/ContainerCreate.java#L99.

**Comment by blessedchitamba** [comment]
Sure I can do that. You can give me any other info I need to know regarding that process.

**Comment by bbortt** [comment]
nothing more, really. just fork the project, fix the bug, submit a PR. straight forward 😉 

note that the pipeline must pass and tests ensuring the desired behavior are always welcome. you can add me as a reviewer.

thanks very much!

**Comment by blessedchitamba** [comment]
Hi @bbortt. After further debugging and investigation, seems like this ```'toString()'``` that converts the items retrieved from the command parameters map is a roadblock for me, as it will just convert the varargs array representation to its object reference string. So rather I am thinking of adding a ```getVarargsParameter()``` method to that class (AbstractDockerCommand.java) that doesn't add ```toString()```. 

![image](https://github.com/citrusframework/citrus/assets/40063222/81b8eb6d-2e7d-4bca-825b-6b8dbf266eec)

**Comment by bbortt** [comment]
I see. and "env" is not the only varargs parameter, there are others. I think a `getVarargsParameter` is reasonable. just make sure that it can handle both arrays and simple types. also, for all arrays it must still replace dynamic contents recursively. I think of something like this, to give you an idea:

```java
    private static Object[] getVarargsParameter(Object parameter, TestContext context) {
        if (parameter.getClass().isArray()) {
            return Arrays.stream((Object[]) parameter)
                    .map(parameterObject -> getVarargsParameter(parameterObject, context))
                    .toArray();
        } else {
            return new String[]{context.replaceDynamicContentInString(parameter.toString())};
        }
    }
```

I am however not sure, if this will work with all cases. but you'll figure this out! 😉

**Comment by blessedchitamba** [comment]
Hi @bbortt. I have created the PR; however it seems like I dont have permissions/the option to add reviewers. Here is the PR: https://github.com/citrusframework/citrus/pull/1021
