### ISSUE TITLE
jetty v11 to v12 migration

### ISSUE THREAD

**Issue by bbortt** [citrusframework/citrus#1010]
must migrate the `jetty` dependencies from 11 to 12. see the [migration guide](https://eclipse.dev/jetty/documentation/jetty-12/programming-guide/index.html#pg-migration-11-to-12) for detailed information.

**Comment by christophd** [comment]
Throwing in the idea to move to netty instead?

**Comment by bbortt** [comment]
ahm, I have no clue what differences pros/cons are, whatsoever 😓 up to you.

**Comment by hmmlopez** [comment]
I’ve tried last week to use citrus with spring boot 3.2.0 and indeed faced this issue with jetty v12. Had to downgrade back to 3.1.x of spring boot.

**Comment by bbortt** [comment]
I too ran into issues. I am now trying to upgrade the codebase to Spring >= 3.2 and Jetty 12.

@christophd I don't think that migrating to Netty would help. it's not exactly the same thing, from my understanding of it. Jetty is a simple HTTP server. Netty is a whole non-blocking framework, right? I think v11 to v12 migration is < to Netty migration.

**Comment by bbortt** [comment]
migration ongoing.. managed to do it up to `citrus-ws` over the weekend: https://github.com/citrusframework/citrus/pull/1087.
