### ISSUE TITLE
When will Citrus 4.0 be deployed to Maven Central

### ISSUE THREAD

**Issue by tschlat** [citrusframework/citrus#1043]
**Citrus Version**
4.0.0

**Question**
There are rumors about a new release. It is not yet visible on maven central. When will it be deployed?

**What I've tried so far**
Checked maven central for org.citrusframework:citrus-base. There are only two milestone releases.

**Additional information**

**Comment by christophd** [comment]
It should be there immediately but it takes some time to sync for search.maven.org so that you can see it in the UI. 

I just checked it is there now also on [search.maven.org/org.citrusframework/citrus/4.0.0/pom](https://search.maven.org/artifact/org.citrusframework/citrus/4.0.0/pom)

**Comment by tschlat** [comment]
Looks good. Thank you very much for your endless effort in pushing this forward.
