### ISSUE TITLE
Migration guide from v3.4.0 to v4.0.0

### ISSUE THREAD

**Issue by sothavirak** [citrusframework/citrus#1051]
**Citrus Version**
Migrating from v3.4.0 to v4.0.0

**Question**
What is the replacement of https://github.com/citrusframework/citrus/blob/v3.4.0/vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/runner/TestRunner.java in v4.0.0?

**Comment by bbortt** [comment]
https://github.com/citrusframework/citrus/blob/main/core/citrus-api/src/main/java/org/citrusframework/TestCaseRunner.java

and

https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/org/citrusframework/DefaultTestCaseRunner.java

some guide would be helpful indeed.. eyeing @christophd. do you have plans for that? or should I try and come up with something?

**Comment by sothavirak** [comment]
Thanks but cant find replacement for this in v4.0.0

https://github.com/citrusframework/citrus/blob/v3.4.0/vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/runner/TestRunner.java#L431

**Comment by christophd** [comment]
Yep, need to add this into the migration guide. Thanks you!

Please, also have a look into the [citrus-samples](https://github.com/citrusframework/citrus-samples) repository. Here you can see how it works with Citrus 4.0.0 and the mentioned TestCaseRunner replacement

Also this might give you an idea (e.g. for JUnit Jupiter runtime):
https://github.com/citrusframework/citrus/tree/main/runtime/citrus-junit5/src/test/java/org/citrusframework/junit/jupiter/integration

**Comment by christophd** [comment]
https://github.com/citrusframework/citrus-samples/tree/main/samples-junit
https://github.com/citrusframework/citrus-samples/tree/main/samples-testng

**Comment by sothavirak** [comment]
The documentation seems still refering to v3.4.0

![Uploading image.png…]()

**Comment by christophd** [comment]
True, and sorry for that. Updating the documentation will be an iterative task. Any help is much appreciated!

**Comment by sothavirak** [comment]
Would love too, but struggling to fix the breaking changes after migrating to v4.0.0 - Some codes no longer work.

**Comment by christophd** [comment]
We are here to help. Please can you give some examples and error messages?

**Comment by sothavirak** [comment]
Another question, we used to rely on this class for our JUnit
https://github.com/citrusframework/citrus/blob/v3.4.0/vintage/citrus-java-dsl/src/main/java/com/consol/citrus/dsl/junit/JUnit4CitrusTestRunner.java

What is the 1 to 1 replacement in V4.0.1?

**Comment by christophd** [comment]
This would be `org.citrusframework.junit.spring.JUnit4CitrusSpringSupport`

Once again, I recommend having a look into the samples (the Java code as the update of the documentation is still ongoing) as these have all been updated to Citrus 4.0

**Comment by sothavirak** [comment]
Thanks Chris. Will close this.
