### ISSUE TITLE
ClasspathResourceResolver does not support loading resources from fat jars

### ISSUE THREAD

**Issue by tschlat** [citrusframework/citrus#1071]
**Citrus Version**
4.0

**Expected behavior**
Citrus should be able to run from a Spring Boot application.

**Actual behavior**
Citrus does not resolve all required components like validators etc. These are loaded by classpath scanning and this fails on jars, that are nested in a fat jar, like in Spring Boot application.

**Test case sample**
We run a Citrus Simulator in a K8S environment and we have plenty of issues, because components are not properly resolved. Remote debugging provided insight into this issue.

**Comment by bbortt** [comment]
@tschlat I think that issue has been solved. report back if that is not the case.
