### ISSUE TITLE
Citrus Functions documentation gaps

### ISSUE THREAD

**Issue by picimako** [citrusframework/citrus#1086]
Hi!

I've been going through the implementations of Citrus function classes and I've found a few things that are missing from the [documentation](https://citrusframework.org/citrus/reference/4.0.2/html/index.html#functions) on the website:
- `encodeBase64`/`decodeBase64`: no mention of the optional charset parameter.
- `readFile`: no mention of the optional encode base64 and replace dynamic content parameters.
- `jsonPath`: no mention of that the jsonPath expression is always the last parameter, and there can be an arbitrary number of json source part parameters before that, that are concatenated into a single json source text.
- `unixTimestamp`: there is no section for this in the documentation

**Comment by bbortt** [comment]
hello @picimako, thanks for the remarks. contributions are always welcome, if you're able to do so. especially in the documentation section - we're always having hard times there. please let me know if you're willing to do so, or if I should proceed with the updates if I find time.

**Comment by picimako** [comment]
@bbortt Yeah, I'll do it gladly.

**Comment by christophd** [comment]
Fixed with #1088
