### ISSUE TITLE
JsonTextMessageValidator should ignore order of json array items

### ISSUE THREAD

**Issue by novarx** [citrusframework/citrus#1101]
**Citrus Version**

4.1.0

**Context**

[`JsonTextMessageValidator#validateMessage`](https://github.com/citrusframework/citrus/blob/main/validation/citrus-validation-json/src/main/java/org/citrusframework/validation/json/JsonTextMessageValidator.java)

**Expected behavior**

The validation of a given json array, compared to a control json, should ignore the order of array items.
i.e. the follwing "recived-json"

```json
{ "books": ["book-c", "book-b", "book-a"] }
```
should throw no ValidationException when compared with the follwing "control-json"

```json
{ "books": ["book-a", "book-b", "book-c"] }
```

**Actual behavior**

The item ordering is always asserted, even when not in `strict` mode.

**Test case sample**

See Pull Request (#1102)

**Comment by bbortt** [comment]
fixed in https://github.com/citrusframework/citrus/pull/1102.
