### ISSUE TITLE
CitrusLifecycleHooks break the Cucumber API

### ISSUE THREAD

**Issue by christophd** [citrusframework/citrus#1116]
**Citrus Version**
4.1.1

**Problem**
The CitrusLifecycleHooks use a custom Scenario class as a method parameter. This breaks the Cucumber API when the hook class is loaded as part of the Cucumber glue code.

Usually the hooks are not loaded as `normal` Cucumber hook definitions but they are loaded specifically with the Citrus backend implementation. But the hook class uses the `normal` Cucumber before/after hook annotations and that may break the Cucumber API as the hooks may also be loaded by the usual Cucumber glue code.

**Suggestion**
Remove the usual Cucumber annotations from the CitrusLifecycleHooks hook class as it is not supposed to be loaded by normal glue code.

**Comment by tobiashochguertel** [comment]
This isn't yet released or?
