### ISSUE TITLE
Citrus kafka functionality maven dependency

### ISSUE THREAD

**Issue by ZuikovAV** [citrusframework/citrus#1132]
@christophd help me please!

**Citrus Version 4.0.0**

**Question: What maven dependency do i need to use citrus kafka functionality?**

**What I've tried so far**
<dependency>
    <groupId>org.citrusframework</groupId>
    <artifactId>citrus-kafka</artifactId>
    <version>4.0.0-M1</version>
</dependency>

<dependency>
    <groupId>org.citrusframework</groupId>
    <artifactId>citrus-kafka</artifactId>
    <version>4.0.0</version>
</dependency>

<dependency>
    <groupId>org.citrusframework</groupId>
    <artifactId>citrus-kafka</artifactId>
    <version>4.2.0</version>
</dependency>

**Additional information**
The following dependencies not found.

**Comment by christophd** [comment]
Should be available on Maven central: https://search.maven.org/artifact/org.citrusframework/citrus-kafka

Latest version is 4.1.1: https://search.maven.org/artifact/org.citrusframework/citrus-kafka/4.1.1/jar

**Comment by christophd** [comment]
maybe you are sitting behind a firewall that prevents internet access to Maven central?

**Comment by ZuikovAV** [comment]
> maybe you are sitting behind a firewall that prevents internet access to Maven central?

Is citrus-http at the same repository?

**Comment by ZuikovAV** [comment]
Thanks all for the reply! Found a problem...
