### ISSUE TITLE
Citrus Framework: Spring vs Spring Boot / spring-cloud-azure-starter-keyvault-secrets Usage

### ISSUE THREAD

**Issue by pablopaul** [citrusframework/citrus#1180]
**Citrus Version**
4.1.0

**Question**
1) My understanding is that Citrus Framework uses Spring, but not **Spring Boot**. Is that correct?

I want to use [spring-cloud-azure-starter-keyvault-secrets](https://mvnrepository.com/artifact/com.azure.spring/spring-cloud-azure-starter-keyvault-secrets) to securely store and retrieve a test secret. With the mentioned package it should be possible that a value in the `application.properties` file get replaced automagically with the according secret in a Azure key vault.

2) Do you think this package should work with a Citrus Framework project or is it not expected to work since it needs a Spring Boot application?

3) Would it be sensible and would you suggest to convert a Citrus Framework Spring project into a Citrus Framework Spring Boot project or is this non sense?

**What I've tried so far**

I have tried to integrate "spring-cloud-azure-starter-keyvault-secrets" as described in the [official docs](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault#use-spring-key-vault-propertysource) under "Use Spring Key Vault PropertySource".
The value in the `application.properties` does not get replaced as expected.

Thank you!

**Comment by bbortt** [comment]
sorry for the late answer, but there you go... let me know if that helps.

> automagically

never heard that one 😆 gave me a good laugh.

> My understanding is that Citrus Framework uses Spring, but not Spring Boot. Is that correct?

partly. the core ([`citrus-api`](https://github.com/citrusframework/citrus/tree/main/core/citrus-api) and [`citrus-base`](https://github.com/citrusframework/citrus/tree/main/core/citrus-base)) have been written in pure java. [`citrus-spring`](https://github.com/citrusframework/citrus/tree/main/core/citrus-spring) is just another connector, but not a necessity.

this is also documented in the [Maven chapter](https://citrusframework.org/citrus/reference/4.2.1/html/index.html#setup-maven).

> Do you think this package should work with a Citrus Framework project or is it not expected to work since it needs a Spring Boot application?

I would expect it to work out of the box, with regards to the comment below...

> Would it be sensible and would you suggest to convert a Citrus Framework Spring project into a Citrus Framework Spring Boot project or is this non sense?

That is a sensible decision. You could then do something like the below:

```java
@SpringBootTest(classes = { AzureConfiguration.class })
class MyTest {

    // Continue with the test here...
}
```

We do this almost all the time in my company.
