### ISSUE TITLE
Archetype: citrus-quickstart:4.2.1 - dependency to citrus-testng points to ${project.version} in pom.xml

### ISSUE THREAD

**Issue by OLegrand** [citrusframework/citrus#1202]
**Citrus Version**
4.2.1

**Expected behavior**
Dependency to citrus-testng points to ${citrus.version} in generated pom.xml.

**Actual behavior**
Dependency to citrus-testng points to ${project.version} in generated pom.xml.

**Test case sample**
> Command 'mvn archetype:generate -Dfilter=org.citrusframework.archetypes:citrus' on version 4.2.1 generates a pom.xml trying to load citrus-testng:jar:1.0-SNAPSHOT instead of citrus-testng:jar:4.2.1. 
So I got the message: Could not find artifact org.citrusframework:citrus-testng:jar:1.0-SNAPSHOT

Local fix is obvious (change to <version>${citrus.version}</version>) but might be interesting to change in the archetype :)

Many thanks for the great job on this nice framework!

**Comment by bbortt** [comment]
thanks for reporting this, I will take a look at it!

**Comment by OLegrand** [comment]
Many thanks for the fast resolution! Best regards
