### ISSUE TITLE
How to use selector kafka and KafkaMessageFilteringConsumer 

### ISSUE THREAD

**Issue by akuz0** [citrusframework/citrus#1249]
**Citrus Version**
4.3.3

**Question**
1. How to use  https://github.com/citrusframework/citrus/blob/188fb5392fe9f0f0a94f49122ba6eaa1e382a4be/src/manual/endpoint-kafka.adoc#L459

I finded example for TestNG, but not finded for Junit 5 https://github.com/citrusframework/citrus/blob/188fb5392fe9f0f0a94f49122ba6eaa1e382a4be/endpoints/citrus-kafka/src/test/java/org/citrusframework/kafka/integration/KafkaEndpointJavaIT.java#L52

```java
then(
    receive(kafkaWithRandomConsumerGroupEndpoint)
        .selector(
            kafkaMessageFilter()
                .eventLookbackWindow(Duration.ofSeconds(1L))
                .kafkaMessageSelector(
                    KafkaMessageByHeaderSelector.builder()
                        .key("key")
                        .value("prefix")
                        .matchingMechanism(STARTS_WITH)
                        .build()
                )
                .build()
        )
);
```

3. How to use KafkaMessageFilteringConsumer ? https://github.com/citrusframework/citrus/blob/188fb5392fe9f0f0a94f49122ba6eaa1e382a4be/endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaMessageFilteringConsumer.java

**What I've tried so far**
I see selector(String messageSelector)  and  kafkaMessageFilter() not finded

```java
testActionRunner.run(
                receive()    
                .endpoint(topic)
                .validate((message, context) -> {
             
                }));
```
**Additional information**

**Comment by bbortt** [comment]
ah wait, I think it's not released yet. I think it's part of citrus 4.4.0. so it's already in the source code (`main` branch), but not released. @christophd thoughts on that? any schedule on the release?
