### ISSUE TITLE
receiveTimeout will be depricated?

### ISSUE THREAD

**Issue by akuz0** [citrusframework/citrus#1253]
**Citrus Version**
4.3.3

**Question**
Why adoc not work? https://github.com/citrusframework/citrus/blob/main/src/manual/actions-timeout.adoc
But in my code receiveTimeout works

**What I've tried so far**

**Additional information**

**Comment by bbortt** [comment]
is it possible that you're referring to https://github.com/citrusframework/citrus/blob/main/src/manual/actions-expect-timeout.adoc?

on the other hand you're right, the [citrus documentation](https://citrusframework.org/citrus/reference/4.3.3/html/index.html) does never ever mention `receive-timeout` which is based on https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/org/citrusframework/actions/ReceiveTimeoutAction.java. however I've no clue if it should or did at any point.

**Comment by bbortt** [comment]
that has been renamed to https://github.com/citrusframework/citrus/blob/main/src/manual/actions-expect-timeout.adoc. it's the same content-wise.
