### ISSUE TITLE
Typo in message selector documentation

### ISSUE THREAD

**Issue by zackzack38** [citrusframework/citrus#1265]
**Citrus Version**
4.3.3 and previous versions

**Expected behavior**
In actions-receive.adoc the CitrusTest for a "message selector inside a receiving action" initializes a **hashMap** for the test.

**Actual behavior**
In actions-receive.adoc the CitrusTest for a "message selector inside a receiving action" initializes a **hasMap** for the test.

**Test case sample**
```
@CitrusTest
public void selectorTest() {
    Map<String, String> selectorMap = new HasMap<>();
    selectorMap.put("correlationId", "Cx1x123456789");
    selectorMap.put("operation", "getOrders");

    $(receive(someEndpoint)
        .selector(selectorMap)
        .message()
        .body("...")
    );
}
```

**Comment by christophd** [comment]
Fixed with #1266
