### ISSUE TITLE
How to Autowire Services into my Citrus Test

### ISSUE THREAD

**Issue by adamlukaszewski** [citrusframework/citrus#1269]
**Citrus Version**

Citrus: 4.4.0
Spring: 3.3.3

**Question**

Maybe a no-brainer but I need some clarification on that: Is it possible to autowire a service class into the Citrus test? 

The use-case is that I would like to use some of my (already defined) persistence services to make some preparations before the actual test. The setup of @CitrusEndpoints is working. I also see that before spring boot will be executed also the citrus context environment will be started --> that's fine. 

The actual questions start if I want to autowire some of the spring boot services into my test (@CitrusSpringSupport since I am using junit5).

**What I've tried so far**

Something simple like that:

```java 
@CitrusSpringSupport
@ContextConfiguration(classes = {CitrusSpringConfig.class, EndpointConfig.class})
public class TodoListIT {

    @Autowired
    private AServiceForWhatEver service;

    @CitrusEndpoint
    private HttpClient todoClient;

    @Test
    @CitrusTest
    void testGet( @CitrusResource TestActionRunner actions
    ) {
        service.sayHello();
    }
}
```

And this is my EndpointConfig:

```java
@Configuration
public class EndpointConfig {

    @Bean
    public BeforeSuite embeddedTodoApp() {
        return new SequenceBeforeSuite.Builder()
                .actions(context -> {
                    SpringApplication.run(Application.class);  // Store the Spring context
                })
                .build();
    }

    @Bean
    public HttpClient todoClient() {
        return CitrusEndpoints
                .http()
                .client()
                .requestUrl("http://localhost:8080")
                .build();
    }
}
```

When I start it that way I am getting this error:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'com.example.citrusmeetscucumber.TodoListIT': Unsatisfied dependency expressed through field 'service': No qualifying bean of type 'com.example.citrusmeetscucumber.AServiceForWhatEver' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
```

Or is this not the correct approach and method to use citrus (since it have the impression that it is more like a e2e testing tool)? 

**Additional information**

Actually, the above example is only a minimized version of what I plan to do. I want to use citrus with the cucumber integration and use the http component to make some test within my steps. But the use-case is there quite the same. I would like to inject a jdbcTemplate (of spring boot) to truncate some tables with a kind of "Given an empty database" instruction. Instead of maintaining different DB accesses I just wanted to reuse what is already have in the spring boot context. That was the entire idea behind all that.

Another question how can I set the active profile for the test run?

Thanks folks!

**Comment by christophd** [comment]
yes, this is absolutely possible. The `@ CitrusSpringSupport ` brings the Spring JUnit5 extension already so `@Autowire` support is enabled already.

You could use `@Autowire` instead of `@CitrusEndpoint` in your example already.

The thing missing is that your service `AServiceForWhatEver` is not declared as a bean in the Spring application context that is started as part of the Citrus test. Either you include the Spring bean java config where `AServiceForWhatEver` is declared as a bean to the `@ ContextConfiguration` annotation or you just add it as a bean into `EndpointConfig` class.

Autowire of Spring beans into your test should be working for you.

**Comment by adamlukaszewski** [comment]
That worked:

```java
@Configuration
public class EndpointConfig {

    @Bean
    public AServiceForWhatEver aServiceForWhatEver() {
        return new AServiceForWhatEver();
    }

    @Bean
    public BeforeSuite embeddedTodoApp() {
        return new SequenceBeforeSuite.Builder()
                .actions(context -> {
                    SpringApplication.run(Application.class);  // Store the Spring context
                })
                .build();
    }

    @Bean
    public HttpClient todoClient() {
        return CitrusEndpoints
                .http()
                .client()
                .requestUrl("http://localhost:8080")
                .build();
    }
}
``` 
Even though I do not fully understand why I need to re-declare Beans that are already known to my application spring boot context. Maybe you can provide some words to that.

Furthermore, wouldn't it also be possible to add  to the ContextConfiguration just the complete Application.class? I tried it and it seems also to load the application if I provide the properties for datasource, etc. For some reason it is not using my application.yml I have in my application?! But once I made some adjustments in the properties it seems to work and I can directly Autowire the AServieForWhatEver:

```java
@CitrusSpringSupport
@ContextConfiguration(classes = {CitrusSpringConfig.class, EndpointConfig.class, Application.class})
@TestPropertySource(
        properties = {
                "spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1",
                "spring.datasource.username=admin",
                "spring.datasource.password=password",
                "spring.datasource.driver-class-name=oracle.jdbc.OracleDriver"
        }
)
public class TodoListIT {

    @Autowired
    private AServiceForWhatEver service;

    @CitrusEndpoint
    private HttpClient todoClient;

    @Test
    @CitrusTest
    void testGet( @CitrusResource TestActionRunner actions
    ) {
        service.sayHello();
    }
}
``` 

Is this method recommended? If so do you have an idea how to solve the issue with the properties? And last but not least what is the preferred way to make a spring profile active (for instance "test")? @ActiveProfiles annotation was not working.

Thanks for your help.

**Comment by christophd** [comment]
It depends how you want to separate tests and the system under test. In the todo list examples Citrus tests are separated from the actual Spring boot application. The Spring boot application is started in a separate Java JVM (e.g. via Maven plugin) in a pre integration-test phase and the Citrus tests operate in another JVM. The Spring bean application context instances of Citrus and the Spring Boot application are separated, too. This is why you had to re-declare the service bean in the Citrus test application context.

In case you want to combine both tests and system under test into a single JVM and Spring bean application context you can do that, too. You may combine Citrus JUnit5 extensions with the SpringBootTest extension then. The SpringBootTest support may also load your `application.yml` then and support the activation of profiles etc. The Spring boot application will start as part of the test JVM then and you may have full access to the beans and services in your application with `@Autowire`.

Both procedures of separating/combining test and system under test do have pros and cons. If you heavily want to access services of your application during the test combining may be a good alternative.

**Comment by adamlukaszewski** [comment]
Thanks man. You confirmed the feeling that I had about this and you extended my understanding.
