### ISSUE TITLE
JSR 107 Cache support

### ISSUE THREAD

**Issue by christophd** [citrusframework/citrus#149]
There are many caching frameworks out there (e.g. Hazelcast, Infinispan, ehcache, Ignite) and all of them implement JSR 107 cache specification. Citrus should provide module for connecting to those JSR compliant caches. Citrus must be able to put new data to the cache read data from the cache and listen for notifications.

**Comment by svettwer** [comment]
@christophd is this still a thing?
I would recommend to close this issue and if JSR 107 is requested, we could just reopen it or create a new issue.

**Comment by svettwer** [comment]
Closed as JSR is currently not requested by the community
