### ISSUE TITLE
Apache Kafka support

### ISSUE THREAD

**Issue by christophd** [citrusframework/citrus#152]
Add endpoint module for Apache Kafka connectivity

**Comment by 7Bit** [comment]
As Apache Kafka and the event-driven architecure becomes more and more a used pattern in a microservices world, a native endpoint module for Apache Kafka would be really useful.

**Comment by Cs4r** [comment]
any news on this @christophd ?

**Comment by FMAOuroboros** [comment]
Currently we're unable to provide a detailed schedule on this but we're pretty confident to get this done until the end of Q3 2018.
