### ISSUE TITLE
HELP: Get citrus ftpserver files with LIST command

### ISSUE THREAD

**Issue by antoneladestito** [citrusframework/citrus#286]
Hi!
I have a citrus ftpClient that connects to a citrus ftpServer (both defined in citrus context):

        ftpClient.getFtpClient().connect(ftpHostname, Integer.valueOf(ftpPort));
        ftpClient.getFtpClient().login(ftpUsername, ftpPassword);
        ftpClient.send(new FtpMessage(FTPCmd.EPRT, "|1|192.168.32.1|22|"), context);
        ftpClient.send(new FtpMessage(FTPCmd.CWD, ftpDir), context);
        ftpClient.send(new FtpMessage(FTPCmd.LIST, null), context);
        Message response = ftpClient.receive(context);

Here, the connection is successful. and the reply is; SENT: 150 File status okay; about to open data connection.

In the citrus console, i see the files that are in the server, but they are not in the response Message object; where can i find the list?

Thanks in advanced,
Antonela

**Comment by christophd** [comment]
Ftp client responses are cached and queued so you are actually receiving the response for the first send operation. Please add a receive after each send operation to make sure that no queued responses are on the ftp client component.

**Comment by antoneladestito** [comment]
Thanks for your answer!
I'm facing this problem now: i'm trying to wait for a FTP file using the following commands:
```
 final String finalPath = path;
 waitFor().condition(new Condition() {
            @Override
            public String getName () {
                return "Check file uploaded to FTP";
            }

            @Override
            public boolean isSatisfied (TestContext testContext){
                return new File(finalPath).listFiles().length != 0;
            }

            @Override
            public String getSuccessMessage (TestContext testContext){
                return "Files found in FTP!";
            }

            @Override
            public String getErrorMessage (TestContext testContext){
                return "No file was found in FTP";
            }
        }).seconds(seconds).interval(INTERVAL);
```

And then, i want to connect FTP client to the server and list the files. Citrus is running this in incorrect order: first it tries to connect FTP client and then waits for the file.
How can i resolve this order problem?

**Comment by christophd** [comment]
FTP client and server have been reimplemented in order to make things more straight forward. Please review the new FTP support and open/reopen a new issue when things are not working out for you.

http://citrusframework.org/citrus/reference/html/index.html#ftp
