### ISSUE TITLE
Selenium: waitUntil() before element loaded - element not found

### ISSUE THREAD

**Issue by purrplingcat** [citrusframework/citrus#293]
Hi,

I want check element with some id or xpath to be loaded via

```java
selenium().waitUntil().visible().element(By.id("someid")); # element with id not exists
selenium().waitUntil().element(By.id("someid")); # same error
```

but I get failed test because element with id someid not found. I test a VAADIN web app. VAADIN loads pages dynamically via JS (elementsnot exists before load by JS).

How I can resolve it? You can add support for 'ExpectedConditions' to waitUntil()? Or exists some was, how to do it?

Thanks.

**Comment by svettwer** [comment]
Hi @purrplingcat!

Sorry for the late response. Have you been able to resolve your problem or does it still occur?

BR,
Sven

**Comment by svettwer** [comment]
I assume that the issue has been solved.

If you've any further questions, please do not hesitate to open a new issue. We're currently try to reorganize the project so that questions are answered in time!

Again: Sorry for the very late response!

BR,
Sven
