### ISSUE TITLE
Add YAML support for configuration

### ISSUE THREAD

**Issue by sburkard** [citrusframework/citrus#324]
It would be nice to use YAML as alternative configuration format to properties. The main reason is to reuse Spring configurations that are more and more in YAML format.

citrus-application.yml as alternative to citrus-application.properties

**Comment by svettwer** [comment]
Hi!

I agree that this would be a nice alternative. Unfortunately we've no resources to get this done. If you would like to take care of this feature, feel free to reopen this issue and propose a pull request.

BR,
Sven
