### ISSUE TITLE
How to provide global variable as value  in cucumber step?

### ISSUE THREAD

**Issue by petyam** [citrusframework/citrus#342]
I have a global variable declared in citrus properties

    organisation.id=ec31936a-5fda-4d4e-b18d-a29f8f1a95b3

Then in citrus-context as 

    <citrus:variable name="organisation.id" value="${organisation.id}"/>

I am using it in a cucumber step

    Given I send a request for organisation=${organisation.id}

In the step itself I need to encrypt the value of the id so I noticed it encrypts the the string as it is ${organisation.id} instead of the actual value.
Can I somehow make it to evaluate first?

**Comment by christophd** [comment]
Could you please provide the step where you are encrypting the variable value? I need to see your code to know how you are accessing the variable.

**Comment by petyam** [comment]
so the step definition is like this:
@When ("^I send a request for organisation=(.*)$")
public void getOrg(String orgId){
 final String endpoint="/organisations?orgId="+orgId;
 final PrivateKey portal_pr_key = cryptoHelper
                .accept(PORTAL_KEYS)
                .getPrivate();
String digest=CryptoHelper.getDigest("GET&" + endpoint, portal_pr_key);
runner.http(httpActionBuilder -> {
            HttpClientRequestActionBuilder builder = httpActionBuilder
                    .client("OrgServiceEndpoint").send()
                    .get(endpoint).header("Secure-Sign", digest)
                    .contentType("application/json")
                    .accept("application/json");
}
I call it from the test case:
Given I send a request for organisation=${organisation.id}
//sometimes I have a set of values to use there it's not alway  the global variable. I've used global variables like that in other steps as well and as long as I don't need the real value before the execution it's fine. But in cases like this where I need it to calculate something before runtime I am not sure what is the way if any

**Comment by svettwer** [comment]
I assume that the issue has been solved.

If you've any further questions, please do not hesitate to open a new issue.

BR,
Sven
