### ISSUE TITLE
Include Travis CI

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#364]
To improve the possibility to check PRs whether all tests are running, one should consider to include Travis CI into Citrus.

**Comment by FMAOuroboros** [comment]
There is already a branch from @gucce (https://github.com/gucce/citrus/tree/travis-ci) that includes a `travis.yml` to start with.

**Comment by FMAOuroboros** [comment]
As a result of an internal discussion, we'll use Travis CI at least for branch builds etc.

**Comment by svettwer** [comment]
builds are currently failing + had to cherrypick from master into bugfix-2.7 branch, because the PR was pointing to master.

I've downgraded testNG to 6.11 to avoid the DynamicGraph bug introduced with 6.12. This should fix the build but I do still get some timeouts from integration tests.

**Comment by svettwer** [comment]
I can reproduce the issue locally. The recently added tests from jms topics are running into a timeout.

**Comment by svettwer** [comment]
The build passed! https://travis-ci.org/citrusframework/citrus/builds/411774895
