### ISSUE TITLE
@Value or @Autowire not working with Junit 5

### ISSUE THREAD

**Issue by vmasule** [citrusframework/citrus#370]
I am migrating my current TestNG based framework to Junit5 but @Value and @Autowire not working in test file though it works fine in Config file.
Also I can get bean instance with help of @CitrusEndpoint but there no Citrus specific annotation to get properties.

**Example usage:**

    @ExtendWith(CitrusExtension.class)
    class CustomerTest {    

        @Autowired
        private WebServiceClient soapClient;

        @Autowired
        private Environment environment;

        @Value("${sample.property}")
        private String sampleProperty;
    }

All these are initialised to null but works fine with TestNG.

**Comment by vmasule** [comment]
@christophd  For SpringExtension I have added below dependency but it gives me runtime error saying  
`java.lang.ClassNotFoundException: org.springframework.core.ErrorCoded`


```
<dependency>
             <groupId>org.springframework</groupId>
             <artifactId>spring-test</artifactId>
             <version>5.0.5.RELEASE</version>
             <scope>test</scope>
  </dependency>
```

Do I have to provide any other Spring dependencies to get this working?  Alos it looks like Citrus it still using Spring 4 behind.

**Comment by svettwer** [comment]
Hi!

If you expect any issues because of the spring version, don't worry! We've recently updated Citrus to Spring 5.

Is this issue solved for you or do you have any more questions?

BR,
Sven

**Comment by svettwer** [comment]
It seems like all questions have been answered.
