### ISSUE TITLE
Citrus HTTP REST client should allow syntactically incorrect Content Types

### ISSUE THREAD

**Issue by oweise** [citrusframework/citrus#386]
Citrus tests may want to send content type headers via HTTP REST clients that do not match general MIME Type syntax "mediatype/subtype". Citrus does not allow these MIME types when defined on the HTTP REST client.

Demo code:

```java
@ContextConfiguration(classes= InvalidContentTypeDemoTest.CitrusConfig.class)
public class InvalidContentTypeDemoTest extends JUnit4CitrusTest {

    @Configuration
    public static class CitrusConfig {

        @Bean(name="wsClient")
        public HttpClient wsClient() {
            return CitrusEndpoints.http()
                    .client()
                    .requestUrl("http://localhost:8080")
                    .contentType("bogus")
                    .build();
        }

        @Bean(name="wsServer")
        public HttpServer backendEndpoint() {
            return CitrusEndpoints.http()
                    .server()
                    .port(8080)
                    .autoStart(true)
                    .build();
        }
    }

    @Test
    @CitrusTest
    public void test(@CitrusResource TestRunner testRunner) {

        testRunner.http(action -> {
            action.client("wsClient")
                    .send()
                    .post("/")
                    .payload("<doc text=\"hello\"/>")
                    .fork(true);
        });

        testRunner.http(action -> {
            action.server("wsServer")
                    .receive()
                    .post("/")
                    .payload("<doc text=\"hello\"/>");
        });
    }
}
```

This test fails bc. the content type of the client is "bogus", which does not match  MIME Type Syntax.

**Comment by christophd** [comment]
> In the Extended BNF notation of RFC 822, a Content-Type header field value is defined as follows:
> Content-Type := type "/" subtype *[";" parameter]

The Content-Type header must have a type and subtype information. The underlying Spring and Http components implementation of the Http client do not allow to send malformed Content-Type header. Therefore it is not possible to tweak Citrus to send this kind of malformed header values.

The usage of custom media types such as `application/foo` is allowed and supported though.
