### ISSUE TITLE
Error to convert symbol #

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#390]
Hi guys! I ran into the following problem. In the http request, I must send the code ussd *448 #. The # character must be converted to% 23. But this does not happen. I ask to correct this defect. Example of correct request: GET http://host:8386/ussdpromo/service?ussd=*448%23&service=484&msisdn=7000. Example of request generated by citrus framework : GET http://app01.dev.tema:8386/ussdpromo/service?ussd=*448#&service=484&msisdn=7000

**Comment by svettwer** [comment]
Hi @NShpakov! 

Have you been able to solve your problem? It would be great, if you could share some details of your solution with us. =) 

BR, 
Sven
