### ISSUE TITLE
Helping edit documentation

### ISSUE THREAD

**Issue by taz77** [citrusframework/citrus#396]
Is there a repository that documentation updates can be provided?

**Comment by christophd** [comment]
Documentation sources are within this repository in https://github.com/citrusframework/citrus/tree/master/src/manual

The documentation uses Asciidoc and Asciidoctor maven plugin.

You can create the documentation locally by calling:

`mvn package -Pdocs-html,docs-pdf -N`

After that you should find generated documentation in `target/generated-docs`

**Comment by christophd** [comment]
any help or updates are appreciated!
