### ISSUE TITLE
How I can to use two or more different datasource?

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#399]
Hello all!
If I try to write in EndpointConfig two dataSource I will get mistake. How I can to do it correctly in citrus? I wanna use one base for get validation data. Another database for get test data (variables). In source code of application our developer use next code : 

```java
@Configuration
public class SpringDatasourcesApplicationConfig {
	
    @Bean(name = "dataSource")
    @Primary
    @ConfigurationProperties(prefix="datasource.primary")
    public DataSource primaryDataSource() {
        return DataSourceBuilder.create().type(org.apache.commons.dbcp2.BasicDataSource.class).build();
    }

    @Bean(name = "dataSource4Service")
    @ConfigurationProperties(prefix="datasource.service")
    public DataSource secondaryDataSource() {
        return DataSourceBuilder.create().type(org.apache.commons.dbcp2.BasicDataSource.class).build();
    }
}
```
In citrus documentation and citrus examples code I do not see any example about it.

**Comment by svettwer** [comment]
Hi!

This should easily be possible with the DI mechanism of Spring. If you inject the data sources into your test you could just use the one or the other in the DSL as follows.

```java
@Autowired
@Qualifier("DataSource")
private DataSource dataSource;

@Autowired
@Qualifier("dataSource4Service")
private DataSource dataSourceForService;

@Test
@CitrusTest
public void sampleTest() {
  query(dataSource)
    .statement("select * from whereEver");

  query(dataSourceForService)
    .statement("select * from somewhereElse");
}
```

I hope that helps!

BR,
Sven

**Comment by svettwer** [comment]
Hi!

I assume the issue has been solved. If you've any further questions, please don't hesitate to open a new issue.

BR,
Sven
