### ISSUE TITLE
wsdlimport not working when imported wsdl is within a jar

### ISSUE THREAD

**Issue by agcifre** [citrusframework/citrus#409]
Citrus version: 2.7.5

Hi,
It seems that Citrus framework doesn't handle correclty WSDL (using citrus:schema-repository ) which contains the tag `<wsdl:import namespace="http://..." location="common.wsdl"/>`.

```
Caused by: java.io.FileNotFoundException: jar:file:/home/agarcia/.m2/repository/bu/ba/bi/olo/olo-soap-api/2.1.0-SNAPSHOT/olo-soap-api-2.1.0-20180605.015146-16.jar!/wsdl/common.wsdl (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.springframework.core.io.FileSystemResource.getInputStream(FileSystemResource.java:114)
	at com.consol.citrus.xml.schema.WsdlXsdSchema.getWsdlDefinition(WsdlXsdSchema.java:192)
```
It tries to get the file from the FileSystem instead from the classpath.

I had to modify the class  WsdlXsdSchema in order to go forward:
![image](https://user-images.githubusercontent.com/6222777/41088761-a08b233a-6a40-11e8-93cf-66e4e16db5f4.png)
where: `PATH_SEPARATOR = "!/";`

Could you kindly check if the correction is appropiate and see if this fix can be added in future release, please?

BR,
Alejandro.

**Comment by christophd** [comment]
Could you please open a pull request with your changes?

**Comment by agcifre** [comment]
Hi Christoph,

Sorry for my ignorance but do I need to create a branch in order to create
a pull request or can I use the existing banch telnet?
I tried to create a new branch but I don't hace the rights...

Thanks in advance,
Alejandro.

**Comment by svettwer** [comment]
Hi @agcifre!

The regular way to contribute to a project is to fork it so that you've your own copy of the project related to your account, apply the changes and create a PR to the upstream.
For more information, please visit https://guides.github.com/activities/forking/

BR,
Sven

**Comment by svettwer** [comment]
Hi!

I reviewed your changes and they're unfortunately breaking some tests.

I also reviewed the current citrus code and found a WSDL with a import that is used to test exactly this use case.

It would be great if you could provide a code sample to reconstruct your issue on our side.

BR,
Sven

**Comment by svettwer** [comment]
I assume the issue has been solved because OP is not responding.
