### ISSUE TITLE
No example how to call store procedure and get output parameters using Datasource Instead JdbcServer 

### ISSUE THREAD

**Issue by vmasule** [citrusframework/citrus#412]
Hi,

I am using Datasource connection directly to my Oracle database. SQL queries are working fine but store procedure calls not.

May I don't know how achieve that. Please provide an example I was trying following way 

`designer.plsql(inProDataSource).sqlScript("{CALL P_GET_DEALER_DETAILS(?,?,?,?,?,?)`  

Most important is how to get out arguments for validation

**Comment by vmasule** [comment]
Thanks @christophd  that helps.

**Comment by vmasule** [comment]
@christophd I have written PLSQL code in separate .sql file calling the same way you have shown in example but it shows success but the PLSQL block never executed when I use `.sqlResource` though it work with `.sqlScript`.

Example:
`
designer.plsql(inProDataSource)
                .sqlResource("classpath:plsql.sql")
                .ignoreErrors(false);`


Please suggest what I am doing wrong here.

**Comment by svettwer** [comment]
Hi @vmasule!

Have you been able to solve this issue or is it still existing?

BR,
Sven

**Comment by svettwer** [comment]
I assume the issue has been solved!

If you've any further questions, do not hesitate to open a new issue!

BR,
Sven
