### ISSUE TITLE
Can't add @before in a testcase

### ISSUE THREAD

**Issue by chokdee** [citrusframework/citrus#413]
Hello

I'm trying to add something like

```
    @BeforeSuite
    @CitrusXmlTest(name = "before.xml")
    public void before() throws Exception {
        
    }
```

The method is called but the before.xml isn't executed.

Any hints?

**Comment by christophd** [comment]
Please add a before-suite-sequence to the Spring Application context as described here http://citrusframework.org/citrus/reference/2.7.5/html/index.html#before-suite

**Comment by chokdee** [comment]
Hi Christoph
this isn't what I want. I need for different testcases different before tests.
We have around 3000 test methods that I'm just migrating....
