### ISSUE TITLE
Can't add @before in a testcase (second try)

### ISSUE THREAD

**Issue by chokdee** [citrusframework/citrus#414]
Hello

I'm trying to add something like

    @BeforeSuite
    @CitrusXmlTest(name = "before.xml")
    public void before() throws Exception {
        
    }

The method is called but the before.xml isn't executed.

I really need for every test class different setups. We have more than 3000 test cases and every have different setup stuff to do. (Just migration to citrus)
If I will use before-suite-sequence it would end in 3000 sequences :-(

Any hints?

**Comment by christophd** [comment]
In case your setup is such different every time you should add these setup tasks to the test itself. Before suite and before test hooks are ment to be shared across multiple tests. Otherwise I do not see the point of calling the `before.xml` when it is not shared on multiple tests.

Nevertheless using the before suite Spring components in Citrus as mentioned in #413 is exactly what you are trying to do with `@BeforeSuite`. What you can do is to add a filter to the mentioned component configuration based on suite names, test groups and environment variables.

Once again if you end up with so many different before suite variations I do not see the point and would suggest to add those setup tasks to the tests directly.

**Comment by chokdee** [comment]
That's what I do at the moment. Generate the same code every time. But I generate many duplicates.

In JUnit Tests this is anormal behavior, that you do stuff in the @Before method.
E.g. Reset some values in db or purge a queue

Here is an example
```
public class TestA {}
  public void before() {
	  deleteValuesInDB();
	  purgeMyQueue();
	  ....
	}
	
	public void test1() {
	   testgoeshere();
	}
	
	public void test2() {
	   testgoeshere();
	}
	
}

public class TestB {}
  public void before() {
	  deleteOtherValuesInDB();
	  purgeAnotherQueue();
	  ....
	}
	
	public void test1() {
	   testgoeshere();
	}
	
	public void test2() {
	   testgoeshere();
	}
	
}
```

**Comment by christophd** [comment]
ok I see, but then you should use before test sequence as shown here: http://citrusframework.org/citrus/reference/2.7.5/html/index.html#before-test

By the way using Java Spring bean configuration might be more comfortable for you then

**Comment by chokdee** [comment]
Is this only possible in the spring context file?

**Comment by christophd** [comment]
This is also possible as Java Spring bean config

**Comment by chokdee** [comment]
Hmm, this isn't easy to handle.
In our case we have tons of test classes and if I add for every test class an entry in to the citrus-context file it will end up with an very large context file or java config file.

 I think you should extend your framework to provide this standard Unit Test feature,

**Comment by chokdee** [comment]
Hi Christoph

I think you misunderstand me.
Here I find a good picture what @Before is doing
https://s3.amazonaws.com/media-p.slid.es/uploads/dominiccharleyroy/images/674023/pasted-from-clipboard.png

There are 2 major points to use this
1) You don't have to implement the setup this in every test method
2) The @before method is running in the same scope, so the variables for the next test method

Example


```
@Before
public void before() {
  dosomeDBSetup();
  setsomeVariablesIntoTheContext();
}

@Test
public void test1() {
    String var = context.getVariable("bla");
    dosomethingWithVar(var);
}

@Test
public void test1() {
    String var = context.getVariable("bla");
    dosomethingOtherWithVar(var);
}
```

Hope this explains it better.

**Comment by svettwer** [comment]
Hi!

I think some misunderstandings are going on here.

@chokdee, you wrote:
>I really need for every test class different setups.

You've multiple options here:
* You could go with `TestDesignerBeforeTestSupport` or `<citrus:before-test>` in DSL. In this case you would have to setup filters to map the before test behavior to the correct tests.
* You could implement custom test actions and just add them as the first step in your test methods. 
```java
public class myTest extends TestNGCitrusTestDesigner {
   private TestAction beforeTest = new AbstractTestAction() {
        @Override
        public void doExecute(TestContext context) {
            //Do whatever you want here
        }
    };

     @Test
    @CitrusTest
    public void testSomething() {
        action(beforeTest);
        //test code here
    }
}
```

Based on my understanding, I think the second options would suite your requirement pretty well.

I hope that helps!

BR,
Sven

**Comment by chokdee** [comment]
Hi Sven

this nearly what I wanted. Bit I need it in XML Testcases. But we have found another sulition while generating the citrus testcases. So you can close it or put it on the future todo list.

Regards
Juergen

**Comment by svettwer** [comment]
Hi!

Cool, great to hear that. You could use this setup also in the XML-DSL. You would define a bean holding the *before test* logic and add them to the test. Here is a sample:

```xml
<testcase name="ActionReferenceTest">
    <actions>
        <action reference="cleanUpDatabase"/>
        <action reference="mySpecialAction"/>
    </actions>
</testcase>
```

Would it be possible for you to share your attempt in case that someone else encounters a similar issue? That would be awesome!

BR,
Sven

**Comment by SajanaKrishnan** [comment]
Hi Sven,

I am a Automation Architect and I came across Citrus as a great fit for my
organization. I am in the process of incorporating citrus in my new
framework. The automation engineers are totally unaware of the features it
has to offer.

Is it possible for you to put up a video from scratch like testcase
preparation, test context, designer, selenium, soap, ftp on what is their
scope and working with Java dsl. I can show it to my team

Regards,
Sajana

**Comment by svettwer** [comment]
Hi @SajanaKrishnan!

For such requirements, we're offering professional support and workshops. Maybe that's an option for you. Here's a link to the [ConSol GmbH contact form](https://www.consol.com/contact/). ConSol is the company behind Citrus. So working with ConSol is helping us to continue the Citrus development.

BR,
Sven
