### ISSUE TITLE
How to replace xpath variables in http:put or post

### ISSUE THREAD

**Issue by chokdee** [citrusframework/citrus#416]
Hi

I can't find any documentation or example about replacing variables in resource file with http:PUT

This here is working but not  useable for mem because we have many endpoints

```
<send endpoint="restService">
  <message>
     <resource file="templates/mytemplate.xml"/>
     <element path="//somenode/id" value="${myid}"/>
  </message>
</send>
```

The following doesn't work or I don't know how to do it
```
<http:send-request  client="restService">
  <http:PUT path="${pathWithVars}">
     <http:headers>
        <http:header name="X-MY" value="123"/>
     </http:headers>
     <http:body>
        <http:resource file="templates/mytemplate.xml"/>
        need x path here
     </http:body>
  </http:PUT>
</http:send-request>

```
Any help?

**Comment by chokdee** [comment]
If I change the citrus-http-testcase.xsd in citrus file with the element tag that is used in <message> the second part is working ;-)
Shall I provide a fix for that?

**Comment by christophd** [comment]
Manipulating message body templates with Xpath might be verbose as you need to find each element in the XML with a separate expression in order to overwrite.

I would suggest to use `${myid}` variable reference directly in the template file. Citrus is able to resolve the variables directly in the body templates. Wouldn't that be more comfortable than using lots of Xpath expressions?

**Comment by chokdee** [comment]
Maybe, but I'm converting 2000 test cases and I can't rewrite tons of xpath entries and templates

**Comment by chokdee** [comment]
I have provided a Pull Request with the changed XSD

**Comment by svettwer** [comment]
Hi @chokdee!

Unfortunately I can't find your PR. I see #432 that you proposed but this is concerning a different issue afaics.

**Comment by svettwer** [comment]
PR concerning this issue: #432

**Comment by svettwer** [comment]
Hi!

Thx for your contribution.
The changes have been merged into master.

BR,
Sven
