### ISSUE TITLE
Thread leak in TestCase.finish()

### ISSUE THREAD

**Issue by bwittwer** [citrusframework/citrus#418]
Hello,

I am using citrus in an automatic testing tool executing test cases every 5 minutes (in the same JVM). 

Following an upgrade from 2.6.2 to 2.7.4 I noticed a thread leak.
Investigations showed that it might be located in [`com.consol.citrus.TestCase::finish`](https://github.com/citrusframework/citrus/blob/master/modules/citrus-core/src/main/java/com/consol/citrus/TestCase.java#L255). 

It appears that the `ScheduledExecutorService` created by `Executors.newSingleThreadScheduledExecutor()` still hold the thread until the [`shutdown`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html#shutdown--) method is actually called. Completing the `finished` CompletableFuture will not stop the scheduled Executor itself.

Can you have a look at this issue? Note that I can provide you a PR with a fix if needed, please tell me.

Thanks,
Bernard.

**Comment by bwittwer** [comment]
probably a side effect of #329

**Comment by svettwer** [comment]
Hi Bernard,

thank you for the analysis of the issue. We're always happy for PRs. It would be great if you could provide one.

BR,
Sven

**Comment by bwittwer** [comment]
Hi Sven,

Sorry for the delay.
You can find PR #488  for review.

BR
Bernard.

**Comment by svettwer** [comment]
Hi Bernard!

That's awesome! Thank you so much! I'm currently a little busy but I'll have a look asap.

BR,
Sven

**Comment by svettwer** [comment]
closed by PR #488 + cherry picket into 2.7.8-SNAPSHOT
