### ISSUE TITLE
jdbc: schema-validation="false" is not settable

### ISSUE THREAD

**Issue by laura098** [citrusframework/citrus#427]
Hello,
if the jdbc action in citrus finds a xsd which looks like the result from a jdbc query, it tries to validate the result against the schema. As the schema is not exactly like the result, the test fails. We would like to avoid this validation, but there is no parameter like "schema-validation" for the jdbc action.
Our workaround is actually to not having any schema-repository in the citrus-context.xml. So the jdbc action can't find any similar xsd and our test ends successfully.
Kind Regards,
Laura

**Comment by svettwer** [comment]
Hi Laura!

Thx for the report. Would it be possible for your to provide some some details?
* Which Citrus Version are you using?
* Are you using the XML or Java DSL?
* Would it be possible to post some code that makes the issue reproducible for us?

BR,
Sven

**Comment by laura098** [comment]
Hi Sven,
the Citrus Version is 2.7.6 and we use xml.

Here is the data we send to the jdbcServer (snipped from the test case):
<send endpoint="jdbcServer">
				<message>
					<payload>
						<jdbc:operation-result>
							<jdbc:success>true</jdbc:success>
							<jdbc:data-set>
     <![CDATA[
         <dataset>
		   <row>
                <BTYPE>OBJECT</BTYPE>
                <ORIGIN>SYSTEM02</ORIGIN>
                <INSTANCE>DEV02</INSTANCE>
                <DTIME>2018-06-28T13:20:00-05:00</DTIME>
                <ENVIRONMENT>CITRUS</ENVIRONMENT>
                <COUNTRY>DE</COUNTRY>
                <TARGETSYSTEM>SYSTEM01</TARGETSYSTEM>
                <REQUESTID>1</REQUESTID>
                <FUNCTIONALKEYS>abc</FUNCTIONALKEYS>
                <ID_ROW>47110815</ID_ROW>     	
		   </row>
		</dataset>
      ]]> 
							</jdbc:data-set>
						</jdbc:operation-result>
					</payload>
				</message>
			</send>


Second the snipped from citrus-context.xml:



The current Problem is reproducible when commenting back in the citrus location of the XSDs. In our case a XSD-File contains a String-Element/Type called “BTYPE”. It seems that citrus validates the JDBC-Output with the Elements in the XSD-Files and fails. When the second snipped shown here is commented out of the citrus-context.xml the citrus test works fine.

Kind regards,
Laura

**Comment by svettwer** [comment]
Thx for the information!

I've briefly investigated the issue but I'll need some more time to come up with results.

BR,
Sven

**Comment by svettwer** [comment]
Hi!

Sorry for the delayed response. Unfortunately I'm not able to reconstruct this issue.
I've added a sample `.xsd ` as follows to the context of `citrus-samples/samples-db/sample-jdbc/xml/src/test/resources/citrus-context.xml` and destroyed it completely.
```xml
  <citrus:schema-repository id="schemaRepository">
    <citrus:locations>
      <citrus:location path="classpath:schema/*.xsd"/>
    </citrus:locations>
  </citrus:schema-repository>
```

I was still able to execute `TodoListIT.AddTodoEntry` successfully containing the following jdbc server response
```xml
<send endpoint="jdbcServer">
  <message>
    <payload>
      <jdbc:operation-result>
        <jdbc:success>true</jdbc:success>
        <jdbc:data-set>
          <![CDATA[
            <dataset>
              <row>
                <id>citrus:randomUUID()</id>
                <title>${todoName}</title>
                <description>${todoDescription}</description>
                <done>false</done>
              </row>
            </dataset>
          ]]>
        </jdbc:data-set>
      </jdbc:operation-result>
    </payload>
  </message>
</send>
```

Is it possible to provide more information about the context and the test case?

BR,
Sven

**Comment by svettwer** [comment]
Hi Laura,

I'm glad to hear that you found a solution. Thanks for your input. I'll open new issues for your proposed improvements. 

BR,
Sven
