### ISSUE TITLE
Credentials found in this repository

### ISSUE THREAD

**Issue by pylyf** [citrusframework/citrus#440]
It looks like this repository contains some credentials.
			```
			username: ['      <xs:attribute name="user" type="xs:string">', '      <xs:attribute name="username" type="xs:string"/>']

			password:       <xs:attribute name="password" type="xs:strin***
			
			host: ['      <xs:attribute name="host" type="xs:string"/>']
			```
			Please change them immediately.
			This issue was created by a robot, so please ignore any false positives and close this issue.

			I appreciate any donation as a way of thanking. Cheers.
			<a href="https://www.buymeacoffee.com/9gwHLnDTs" target="_blank"><img src="https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png" alt="Buy Me A Coffee" style="height: auto !important;width: auto !important;" ></a> 

			_Making the Internet a better place._

**Comment by svettwer** [comment]
False positive
