### ISSUE TITLE
Minimal web UI for remote server

### ISSUE THREAD

**Issue by oweise** [citrusframework/citrus#446]
Would be nice if the remote server would have a web UI, mainly used for manual execution and debugging of these tests.

Proposed features:
- Just show that the deployment worked by being there :-)
- Browse results of the latest test execution
  - Including detail information about f.e. exeptions thrown
- Trigger new test executions by button

**Comment by svettwer** [comment]
+1 from customer workshop

**Comment by bbortt** [comment]
that is included.
