### ISSUE TITLE
Using simulator under heavy load

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#447]
Hi! I have one question. Simulator has been started. It receives requests and returns 200 OK. After 100,000 it returns 500 code. How can I support the simulator without restarting it? I know that I should wrote it in other project, but here I get answer more fast. Thank you!

**Comment by svettwer** [comment]
Hi!

The simulator is storing the protocol of every request at the moment. So after a certain amount of requests, you'll run out of memory.

So currently, there is no way to solve this without redeployment.
I opened https://github.com/citrusframework/citrus-simulator/issues/20 to keep track of the issue.

Concerning the status of the citrus-simulator project. I'm currently in the process of reorganizing some things. The citrus-simulator is definitively in scope an is one of my next big To-Dos on the list.

BR,
Sven
