### ISSUE TITLE
Citrus-Maven-Plugin: Documentation differs from actual implementation

### ISSUE THREAD

**Issue by mischcon** [citrusframework/citrus#452]
**Citrus Version** Tested with 2.7.6 and 2.8.0-SNAPSHOT

According to the [official documentation](https://citrusframework.org/docs/maven-plugin/) the Citrus-Maven-Plugin should have 4 goals.

![image](https://user-images.githubusercontent.com/7205147/44528157-200b4380-a6e9-11e8-95e6-0ecf45a9f8d6.png)

The actual implementation of the plugin has not only more goals, but some of the goals mentioned in the documentation are (not long) part of the plugin.

```
[INFO] citrus-maven-plugin 2.7.6
  Citrus Maven Plugin

This plugin has 5 goals:

citrus:create-docs
  Creates test documentation in interactive mode. Either uses mode excel for MS
  Excel output or html for HTML web page output.

citrus:create-test
  Creates new Citrus test cases with empty XML test file and executable Java
  class. Mojo offers an interactive mode, where the plugin prompts for
  parameters during execution.

citrus:generate-docs
  Generates test overview documentation based on plugin configuration. Html
  documentation creates a web page that contains a list of all available tests
  with meta information. Excel documentation creates a table of all available
  tests with meta information such as name, author, status and so on.

citrus:generate-tests

citrus:help
  Display help information on citrus-maven-plugin.
  Call mvn citrus:help -Ddetail=true -Dgoal=<goal-name> to display parameter
  details.
```

I am not sure whether or not this is the right place for this issue, since there is also a repository for the citrus website. Please move the issue if you think it should be located elsewhere.

**Comment by svettwer** [comment]
Hi!

Thx for the hint. I've created https://github.com/citrusframework/citrus-website/issues/1 in the website repo, so I'll close this one.

BR,
Sven
