### ISSUE TITLE
Allure reports with citrus.

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#453]
Hi! Do you have an example of integration allure and citrus? If it`s possible can you describe it in the citrus documentation? Thanks!

**Comment by svettwer** [comment]
Hi!

Afaics, a adapter is required to integrate with allure, so a direct integration of citrus is not available.
Nevertheless, citrus is creating reports from TestNG, JUnit4 and JUnit5, which are integrated via allure. So it should be possible to use the mentioned allure features to integrate with citrus.

BR,
Sven

**Comment by svettwer** [comment]
Closed due to 14 days inactivity.
If you've further question, please don't hesitate to open a new issue.

BR,
Sven
