### ISSUE TITLE
TestCase class finish() method buggy

### ISSUE THREAD

**Issue by ajaytechie07** [citrusframework/citrus#457]
**Citrus Version**
2.7.4

**Expected behavior**
New Threadpools are getting created in finish() method of class TestCase and those thread-pools are never shut down and also the thread which is getting created keeps executing even if we are setting CompletableFuture.complete(true). Maybe because we are using the scheduleAtFixRate method, which is executing the same task again and again periodically and CompletableFuture.complete(true) has no effect on it.

**Actual behavior**
We should shut down properly all the thread pools we are creating after the task is done and also once we have set CompletableFuture.complete(true), the same task should not be executed again since it is already completed. You can observe this behavior by monitoring the Threads using some tool may be jvisualvm.

**Test case sample**
This is true for all the test cases. You can try with any random test case. It is an optimization issue. We are unnecessarily creating too many threads and never killing them. Since we are using Citrus as a service, we are getting the impact on this issue. Otherwise in the normal scenario when your test is complete your jvm exit all the threads will get destroyed automatically but in case of service, we have tomcat container which is hosting the service and running forever. Threads created are never destroyed.

**Comment by svettwer** [comment]
Hi!

You say you're using Citrus as a service. Are you using the citrus simulator to provide a endpoint simulation or how is your current setup?

As you mentioned, Citrus is designed to be shutdown with the jvm but not as a long running process. For such use cases, we have the citrus simulator or the new citrus remote concept to start endpoints and tests in a dedicated container.

BR,
Sven

**Comment by ajaytechie07** [comment]
Hi,
I am not using any simulation. I am using real endpoints and mostly I am
using ReceiveMessageAction, SendMessageAction and message validation,
that's all. Even if the noraml Citrus mode you are talking about is not
designed to be used as service, one should shutdown a threadpool when done
using. So please correct that part.


Thanks,
Ajay

**Comment by svettwer** [comment]
Hi,

please don't get me wrong, this is definitively something to fix. Nevertheless it's is a special use case where this issue occurs. I would still recommend to have a look at the citrus simulator. Maybe it fits your use case as well and it comes with a complete setup for a service mock deployed in a standalone container.

BR,
Sven

**Comment by svettwer** [comment]
Hi again!

I knew that I've seen this issue a while ago. https://github.com/citrusframework/citrus/issues/418 is already addressing this issue. I'll close this one in favor of https://github.com/citrusframework/citrus/issues/418.

BR,
Sven

**Comment by ajaytechie07** [comment]
No Problem. I will try that. Thanks for the help :)
