### ISSUE TITLE
Runing http call in parallel and can't receive all, Action timeout exception

### ISSUE THREAD

**Issue by ubbn** [citrusframework/citrus#458]
**Citrus Version**
2.7.6

**Question**
How to properly setup parallel test action that makes http calls and validate responses ?

**What I've tried so far**
```java
parallel().actions(
        sendAction(),
        sendAction(),
        ...
        sendAction()
);
parallel().actions(
        receiveAction(),
        receiveAction(),
        ...
        receiveAction()
);
```
And even tried as below:
```java
parallel().actions(
    sequential.actions(
        sendAction(),
        receiveAction()
    ),
    ...
    sequential.actions(
        sendAction(),
        receiveAction()
    )
);
```
where `sendAction()` is simply as below:
```java
return http(x -> x.client(httpClient)
    .send()
    .post()
    .contentType(ContentType.APPLICATION_XML.getMimeType())
    .header("Authorization", "Basic citrus:encodeBase64('${user}:${pass}')")
    .payload(...)
```
`receiveAction()` is:
```java
return http(x -> x.client(httpClient)
    .receive()
    .response(HttpStatus.OK)
    .validationCallback((m, c) -> {
        System.out.println(m.getPayload(String.class));
    }));
```
**Additional information**
Unfortunately, it failed with timeout exception usually at 2nd or 3rd receiveAction() method call.
```
com.consol.citrus.exceptions.TestCaseFailedException: Action timeout while receiving synchronous reply message from http server
```
Running in synchronous way as below is working totally fine. But we need to run those calls in parallel.
```java
sendAction();
receiveAction();
...
sendAction();
receiveAction();
```

**Comment by svettwer** [comment]
Hi!

To fix your first attempt, you would have to detach the clients from the main thread adding `fork(true)` to the client call.
```java
parallel().actions(
        sendAction(),
        sendAction(),
        ...
        sendAction()
);
parallel().actions(
        receiveAction(),
        receiveAction(),
        ...
        receiveAction()
);
```
with

```java
http(x -> x.client(httpClient)
    .send()
    .post()
    .contentType(ContentType.APPLICATION_XML.getMimeType())
    .header("Authorization", "Basic citrus:encodeBase64('${user}:${pass}')")
    .payload(...)
    .fork(true));
```

The second attempt should work out of the box. Are you sure that your SUT is responding in time? Maybe you could try to increase the timeout of the calls.

BR,
Sven

**Comment by svettwer** [comment]
Hi!

I've briefly checked your issue. On my machine the citrus internal correlation ids seems to be messed up. Let me have a closer look.

BR,
Sven

**Comment by ubbn** [comment]
Hi,

Yes, I forgot to mention that I used `fork(true)` on each `sendAction()` as you wrote. And I called `receiveAction()` either in parallel or synchronous manner. But result was same Action time out. 
And I am sure SUT is certainly responding in time. 

As I checkout source code `HttpClient`, in the `send` method it stores each response under same `correlationKey` which seems non-thread safe as only one response to parallel requests to same client will be retrieavable by `receive` method. Is there any workaround ?

Is there a way to call `receive(String selector, TestContext context, long timeout)` method from `HttpClient` directly by providing our own generated correlationKey? If so, it seems we can get around of this single `correctionKey` issue.

**Comment by svettwer** [comment]
Hi!

After a cup of coffee, I found out that the issue is caused by the way the `correlationManager` stores the correlation ids in combination with the `correlationKeyName` generated by the `DefaultMessageCorrelator`.

The id for every message is random but there is only one message mapped to a client once at a time.

So I would like to suggest to use different clients endpoints with different names. The correlationKeyName is affected by the endpoint name and therefore potentially different for every endpoint.
```java
@Configuration
public class EndpointConfig {

    @Bean("client")
    public HttpClient client() {
        return CitrusEndpoints.http()
                .client()
                .requestUrl("http://my.awesome-service.com")
                .build();
    }

    @Bean("foo")
    public HttpClient foo() {
        return CitrusEndpoints.http()
                .client()
                .requestUrl("http://my.awesome-service.com")
                .name("foo")
                .build();
    }

    @Bean("bar")
    public HttpClient bar() {
        return CitrusEndpoints.http()
                .client()
                .requestUrl("http://my.awesome-service.com")
                .name("bar")
                .build();
    }

}
```

Maybe I'll come up with a more elegant solution in a few hours but this is something that will work. At least it worked on my machine.™ ;-)

BR,
Sven

**Comment by svettwer** [comment]
Hi!

I knew there was a better way to solve this but I couldn't remember instantaneously.

```java
public class TodoListIT extends TestNGCitrusTestRunner {

    @Autowired
    private HttpClient httpClient;

    @Test
    @CitrusTest
    public void testPost() {

        final String request1 = "request1";
        final String request2 = "request2";
        final String request3 = "request3";

        parallel().actions(
                sendAction(request1),
                sendAction(request2),
                sendAction(request3));
        parallel().actions(
                receiveAction(request1),
                receiveAction(request2),
                receiveAction(request3));
    }

    public TestAction sendAction(final String requestVariable){
       return http(x -> x.client(httpClient)
                .send()
                .get()
                .extractFromHeader("citrus_message_id", requestVariable));
    }

    public TestAction receiveAction(final String requestVariable){
       return http(x -> x.client(httpClient)
                .receive()
                .response(HttpStatus.OK)
                .selector(Collections.singletonMap("citrus_message_id", "${" + requestVariable +"}"))
                .validationCallback((m, c) -> {
                    System.out.println(m.getPayload(String.class));
                }));
    }
}
```
You could apply selectors to identify the messages by their `citrus_message_id`. This is still a manual mapping. I'll open an enhancement issue so that citrus is able to handle those situations out of the box.

BR,
Sven

**Comment by ubbn** [comment]
Thanks Sven!

Yes this is the way eventually we ended up to receive parallel responses correspondingly. I agree that this should be supported out of box and we are waiting for the better solution.

**Comment by svettwer** [comment]
Hi!

Unfortunately I can't provide a schedule for #459 currently but it's good to hear that the suggested solution worked for you as well.

BR,
Sven
