### ISSUE TITLE
Java DSL waitFor().actions() call resides in java.util.NoSuchElementException

### ISSUE THREAD

**Issue by christophd** [citrusframework/citrus#460]
Calling waitFor().actions() is obviously not working for TestDesigner Java DSL as it results in a java.util.NoSuchElementException.

I would suggest to handle the call properly with waitFor().execution() as it is a inherited call from abstract action container builder DSL.

**Comment by svettwer** [comment]
Closed as we're deprecating/removing the TestDesigner.
