### ISSUE TITLE
Rename argument for RepeatOnErrorBuilder#autoSleep to clarify expected unit

### ISSUE THREAD

**Issue by jklingen** [citrusframework/citrus#461]
Modern IDEs display argument variable names as hint. If the `autoSleep` argument name was e.g. `millis`, I would not have to consult JavaDoc in order to know whether I should pass 1000 or 1. 
![image](https://user-images.githubusercontent.com/5475899/45032428-158a6b80-b052-11e8-8c83-e7996b721549.png)

**Comment by svettwer** [comment]
Solved with #651!

Thx to @swathisprasad! :tada:
