### ISSUE TITLE
Improve import of XSDs with dependencies

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#466]
Extracted from https://github.com/citrusframework/citrus/issues/427
-------

**User story**
As a citrus test developer, I want the dependencies between XSDs to be validated after all XSD files have been imported, so that I don't have to maintain the correct import order in my citrus context file.

**Comment by svettwer** [comment]
Hi @laura098!

I've checked the citrus XSD imports and could not find any issue. Could you please provide a sample of the import that didn't work for you?

BR,
Sven

**Comment by laura098** [comment]
Hi Sven,
I sent you a sample per mail.
BR,
Laura

**Comment by svettwer** [comment]
Hi Laura,

thank you very much. I'll have a look asap. 

BR, 
Sven

**Comment by svettwer** [comment]
Hi @laura098!

I've investigated the issue with the data you provided. I'm still unable to reproduce the issue. It might be the case that the issue occurs only with a specific configuration or setup that you've in place. 

Is it possible for you to investigate the issue further on your side to identify the root cause? If not, I'm sure that we'll find a solution for that. More details via mail.

BR,
Sven

**Comment by svettwer** [comment]
Closed as this issue is stale. If the issue gets reproducible, we'll open up a new issue.
