### ISSUE TITLE
How to start Chrome browser by selenium with personal extention or send to browser my headers?

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#471]
Hi!
I need to access the domain with different headers. I'm sharing this with the "header editor" extension. How to use citrus and selenium in a request to a specific url to preface my headers

**Comment by svettwer** [comment]
Hi!

Sorry, but I've no idea what you're trying to do here. Is it possible to share some additional information about your test, what you've tried so far and what the "header editor" extension does? In addition it would be great if you could point out what you try to archive with this setup.

BR,
Sven

**Comment by NShpakov** [comment]
This is my test:
`    @Test(priority = 1, enabled = true)
    @CitrusTest
    public void test_1(){

        selenium()
                .browser(browser).start()
               ;
        selenium()
                .browser(browser).navigate(todoClient.getEndpointConfiguration().getRequestUrl() +"/service/fotoflirt?campaign_id=1431&lead_id=437233CBB0B828E4E0532325A8C077B6_21321421");`

I want to add two headers (X-MSISDN-VALID: YES
X-Nokia-MSISDN: 79060376320). 
How can I do this without using the browser extension?

**Comment by NShpakov** [comment]
I want to have request like this: `Request URL: http://web01.stage.some:xxxxx/service/foto?campaign_id=xxxx&lead_id=xxxxxxxxxxxxxxxx
Request Method: GET
Status Code: 200 OK
Remote Address: 1xx.1xx.1xx.1x:9xxx
Referrer Policy: no-referrer-when-downgrade
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
Accept-Encoding: gzip, deflate
Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Cookie: partnership=xxxxxxxxxxxxxxxxxxxxxxxx
; SL_G_WPT_TO=ru; SL_GWPT_Show_Hide_tmp=1; SL_wptGlobTipTmp=1; _gorilla_csrf=x; signkey=O3E_njWfEuHYtbzoDu8DScwiH70=
Host: web01.stage.some:xxxxx
Upgrade-Insecure-Requests: 1
User-Agent:x
 Chrome/69.0.3497.81 Safari/537.36
X-MSISDN-VALID: YES
X-Nokia-MSISDN: 79060376320`

**Comment by NShpakov** [comment]
I use browser extention for adding X-MSISDN-VALID: YES X-Nokia-MSISDN: 79xxxxxxxxxx. I want to use different headers in each test....

**Comment by NShpakov** [comment]
In this case I need to send only through the browser. Because this project uses specific autorization ... Thank you for answer. I will be use browser extention for the Firefox, in the application.properties I added `webdriver.firefox.profile = Selenium and webdriver.firefox.marionette=true and webdriver.gecko.driver= F:/Citrus-repo/Program...`. 
In this way Firefox start with my profile extentions. Thank you for answer!

**Comment by svettwer** [comment]
Hi!

So if I understand you correctly, you want to set your headers manually in a selenium test, right? Because selenium is a UI testing framework testing from a end user perspective, I would assume that a end user has to set the specific header manually as well, to use your application? Correct me if I am wrong, but this can't be a end user test from my perspective. 

It is also possible to use the citrus http client for authentication against your backend. Therefore, I would also recommend to use the http client.

BR, 
Sven

**Comment by NShpakov** [comment]
My application means that I get request from another partner. Request has headers. Browser create csrf-token. When I set this url in browser I got the csrf-token. If I will send my request without a browser I can't to create the csrf-token. Our developers told me that I might test this application only using a browser...

**Comment by svettwer** [comment]
Hi!

I bet you will receive the token using the http client with a get request as well. A browser does nothing more than a get request when openen a website in first place.

Would it be possible to point out the architecture of the system.
I understood that you use receive a request from a third party service. I've also noticed, that you open a certain URL with a browser to get a csrf-token. Does your service provide the csrf-token?
Could it be like this?
`Third party request ----> Your service <---- User(Browser)`

BR,
Sven

**Comment by NShpakov** [comment]
Thank you so much! I understood the concept.

**Comment by svettwer** [comment]
Cool! I'm glad to hear that! =)
