### ISSUE TITLE
Unable to find an alternate for clickable element in selenium methods

### ISSUE THREAD

**Issue by SajanaKrishnan** [citrusframework/citrus#474]
**Citrus Version**
2.7.6

**Question**
What is the alternate for -
WebDriverWait wait = new WebDriverWait(browser.getWebDriver(), 8);
 wait.until(ExpectedConditions.elementToBeClickable(btnCreateAddToWallet));

**What I've tried so far**
selenium(action -> action.browser(browser).waitUntil.?????

**Additional information**

**Comment by svettwer** [comment]
Hi!

`WebDriverWait` is a selenium Implementation to wait for a condition using a web driver, ignoring `NotFoundException` thrown by seleniums `until` implementation.

This is different from the Citrus implementation for `waitUntil`. Citrus provides the `WaitUntilActionBuilder` that is also capable of waiting for elements to be visible but with a different syntax based on the citrus fluent API.
For detailed information, please have a look at the documentation about [Selenium wait](http://citrusframework.org/citrus/reference/html/index.html#wait)

Here is a sample
```java
selenium(action -> 
    action.browser(browser)
        .waitUntil
        .visible()
        .element(By.id("add-to-wallet-button")));
```
Currently there is no dedicated implementation for `clickable`, but visible should do it.

BR,
Sven

**Comment by SajanaKrishnan** [comment]
Thanks. Let me check and get back.

**Comment by SajanaKrishnan** [comment]
Same error occurs - element is  not visible or not clickable, when I used - selenium(action -> 
    action.browser(browser)
        .waitUntil
        .visible()
        .element(By.id("add-to-wallet-button")));
Can you help me with a work around?

**Comment by svettwer** [comment]
Hi!

Have you altered the ID from my sample? It seems to be unchanged in the code you've posted. I just guessed an ID to make it clearer.

BR, 
Sven

**Comment by SajanaKrishnan** [comment]
Yes I did :)

**Comment by svettwer** [comment]
Mhm. 
Hard to say. Could you provide some more information about the website you want to test? Maybe some html snippets including the button you want to click?

**Comment by SajanaKrishnan** [comment]
I changed the ID locator to linkText and it started working! This is weird!
