### ISSUE TITLE
citrus flow data transformation

### ISSUE THREAD

**Issue by selly84** [citrusframework/citrus#477]
**Citrus Version**

**Question**

**What I've tried so far**

**Additional information**

**Comment by selly84** [comment]
Hi, I am having warnings when running citrus on my flow cytometry data: "transformation introduced infinite values in continuous y-axis". Does anyone know how to solve this issue? 
In addition, when setting up citrus it does not allow me to change the cross validation folds (by default is 1 and is not good), do you know why and how to solve this?

**Comment by christophd** [comment]
Are you sure that we are talking about Citrus the Java integration testing framework? I get the feeling that your question is totally misplaced in this repository.

If your concern is really about Citrus test framework, please clarify your question and give more information. At the moment I can not help you as I do not see any link to the Citrus framework that this repository is made for.

**Comment by selly84** [comment]
My mistake, sorry. I am new in github.
thanks!

**Comment by christophd** [comment]
Ok no problem. I am curious. What framework or library you were searching for?

**Comment by selly84** [comment]
There is a program called CITRUS developed in Nolan lab for multiparametric analysis of flow cytometry and Cytof derived data. These technologies allow to evaluate protein expression at single cell level.

**Comment by christophd** [comment]
Wow! Sounds like impressive high-tech stuff. I will close this issue due to non relevance for this repository then.
