### ISSUE TITLE
Supply parameters to beans through CI build

### ISSUE THREAD

**Issue by SajanaKrishnan** [citrusframework/citrus#478]
**Citrus Version**
2.7.6

**Question**
I am using VSTS/TFS for Version Controlling, CI builds. Can you please take me through the steps to supply parameters in CI tool such as BrowserType, Execution Environment to the SeleniumBrowser which is a bean definition in my framework? 

**What I've tried so far**
I do not have a lead, yet to try!

**Additional information**

**Comment by svettwer** [comment]
Hi!

This isn't something you would solve with citrus, but with spring.
You could pass the required information for making a decision on the bean configuration with environment variables or property files.
You might want to have a look at the `Condition` interface of spring.

 [conditional-spring-bean-creation](https://stackoverflow.com/questions/29844271/conditional-spring-bean-creation)

Nevertheless, this might not be the ideal solution depending on your use case.
If you want to use endpoints of different configuration in your tests, I recommend to wrap the reusable test procedures in e.g. citrus behaviors and setup a test case per endpoint config. In your context, you could setup a Selenium browser with `BrowserType=firefox` and one with  `BrowserType=chrome`. Afterwards your could pass the browser to your test logic like

```java
    @Test
    @CitrusTest
    public void testWithChrome() {
        applyBehavior(new MyBehavior(seleniumChromeBrowser));
    }

    @Test
    @CitrusTest
    public void testWithFirefox() {
        applyBehavior(new MyBehavior(seleniumFirefoxBrowser));
    }
```

This allows you to distinguish between different scenarios based on the configuration of the test behavior.

BR,
Sven

**Comment by svettwer** [comment]
Closed because of inactivity.
