### ISSUE TITLE
Problems with extracting from payload by xpath.

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#485]
Citrus Version
2.7.6
Hi! I can`t extract from the html page value:

```html
form name="subscr" method="post" action="/subscr/fotoflirt"
   input type="hidden" name="pp-token" value="Z61f3sAQqxDXigo271CqjmMgpF4sjalnZCK0HQ5lUME="
   input type="hidden" id="sign" name="sign" value="undefined"><a href="javascript: document.subscr.submit();" class="lp-button price5" target="_self" style=""></a>
</form
```

I need the pp-token value. I use this code :
`http().client(todoclient).receive().response().status(HttpStatus.OK).messageType(MessageType.XHTML).extractFromPayload("//html[1]/body/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/input[1]/@value","ppTOKEN");`

And in logs I see :

`2018-09-24 16:10:35,939 DEBUG [main] ? (?:?) - Found DOMImplementationLS: org.apache.xerces.impl.xs.XSImplementationImpl@69e308c6
2018-09-24 16:10:35,939 DEBUG [main] ? (?:?) - Using DOMImplementationLS: org.apache.xerces.dom.CoreDOMImplementationImpl
2018-09-24 16:10:35,939 DEBUG [main] ? (?:?) - Evaluating XPath expression: //input[@name=pp-token and contains (@value,1)] Its can`t stop.

**Comment by NShpakov** [comment]
After few minutes I get this in the log:
`2018-09-24 16:26:11,595 DEBUG [main] ? (?:?) - TEST STEP 1 SUCCESS

com.consol.citrus.exceptions.TestCaseFailedException: The element type "input" must be terminated by the matching end-tag "</input>".

	at com.consol.citrus.TestCase.executeAction(TestCase.java:241)
	at com.consol.citrus.TestCase.doExecute(TestCase.java:153)
	at com.consol.citrus.actions.AbstractTestAction.execute(AbstractTestAction.java:46)
	at com.consol.citrus.Citrus.run(Citrus.java:403)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.invokeTestMethod(TestNGCitrusTest.java:125)
	at com.consol.citrus.dsl.testng.TestNGCitrusTestDesigner.invokeTestMethod(TestNGCitrusTestDesigner.java:73)
	at com.consol.citrus.dsl.testng.TestNGCitrusTest.run(TestNGCitrus`

**Comment by NShpakov** [comment]
And `2018-09-24 16:18:47,089 DEBUG [main] ? (?:?) - Evaluating XPath expression: //html[1]/body/div[1]/div[2]/div[1]/div[1]/div[1]/form[1]/input[1]/@value
[Error] :160:67: Attribute "name" must be declared for element type "form".
[Error] :162:155: Attribute "target" must be declared for element type "a".
[Fatal Error] :163:3: The element type "input" must be terminated by the matching end-tag "</input>".
2018-09-24 16:26:06,588 INFO  [main] ? (?:?) - `

**Comment by NShpakov** [comment]
How I can get it by another way?

**Comment by svettwer** [comment]
Hi!

Unfortunately the posted HTML snipped is not a valid HTML document and the error message is pointing to this direction as well.
Would it be possible to provide a complete HTML document for further investigation?
In addition, depending on the size of your HTML document, the process of parsing and analyzing it may take a while.

Based on your XPath expression, it seems you try to extract the `pp-token` from your from. If you could provide more information about the use case you want to test, it might be possible for us to provide a different attempt for solving this issue.

BR,
Sven

**Comment by NShpakov** [comment]
Sorry for this format. You can download the html file from here: https://yadi.sk/d/Wy8nem0P_a1iDg

**Comment by NShpakov** [comment]
I try to extract the pp-token from the document.

**Comment by svettwer** [comment]
Hi!

The formatting is no problem. You could use tripple back ticks instead of single back ticks to declare a code block. You can also add syntax highlighting as I did.

```
    ```html
   <html></html>
    ```
```

would result in 
 ```html
   <html></html>
```

**Comment by svettwer** [comment]
Hi!

It seems that there is an issue while working with the dtd from the open mobile alliance. `<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.2//EN" "http://www.openmobilealliance.org/tech/DTD/xhtml-mobile12.dtd">`.
From the logs, it looks like xerces tries to download the dtd file and fails.
So this is nothing caused by citrus but by one of its dependencies.

If I substitute the doctype with a default XHTML one, it works.
E.g.`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">`
The test fails nevertheless but with a validation exception concerning the documents content.

**Comment by svettwer** [comment]
Btw: The download is also slow when using the `http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd`

**Comment by svettwer** [comment]
I've also found out that you specify the document to be a XHTML, but in fact, it is a HTML, because the input field is noted `<input>` but in XHTML it would be `<input/>`

**Comment by svettwer** [comment]
Hi!

The it took me some time but I recognized, you missed the default namespace declaration in the xpath expression
```java
http()
  .client(httpClient)
  .receive()
  .response(HttpStatus.OK)
  .messageType(MessageType.XHTML)
  .extractFromPayload("//:html[1]/:body/:div[1]/:div[2]/:div[1]/:div[1]/:div[1]/:form[1]/:input[1]/@value", "ppTOKEN");
```

BR,
Sven

**Comment by NShpakov** [comment]
Great! Thank you much! I saw this moment in the documentation but I don`t understood how to 
realized it.

**Comment by svettwer** [comment]
Cool!
I'm glad it worked out for you!

BR,
Sven
