### ISSUE TITLE
Is Citrus support SFTP Mock Server?

### ISSUE THREAD

**Issue by CassieRyu** [citrusframework/citrus#489]
**Citrus Version**
2.7.6

**Question**
**1. Using Scenario:**
I want to use Citrus to support SFTP mock server instead of real sftp server in test environment. I's like to setup the mock server that can retrieve a XML file on another server in an interval time and able to response another XML file back to the server. Is this possible to achieve by using Citrus?
**2. Setup error:**
I'm trying to setup a sftp server via maven(seems only support mvn?) and it can't resolve symble "CitrusEndpoints" in sftp server setup stage. As below.
**What I've tried so far**
Here's my pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>Shan_Liu</groupId>
    <artifactId>shanTest</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.0.5.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

    <dependency>
        <groupId>com.consol.citrus</groupId>
        <artifactId>citrus-core</artifactId>
        <version>2.7.7</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.consol.citrus</groupId>
        <artifactId>citrus-jms</artifactId>
        <version>2.7.7</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.consol.citrus</groupId>
        <artifactId>citrus-ws</artifactId>
        <version>2.7.7</version>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>com.consol.citrus</groupId>
        <artifactId>citrus-http</artifactId>
        <version>2.7.7</version>
        <scope>test</scope>
    </dependency>

    <dependency>
        <groupId>com.consol.citrus</groupId>
        <artifactId>citrus-ftp</artifactId>
        <version>2.7.6</version>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter</artifactId>
    </dependency>
</dependencies>
</project>
```
and my sftp server setup code, which same as your example:
```
import com.consol.citrus.ftp.server.SftpServer;
import org.springframework.context.annotation.Bean;

public class sftpServer {
    @Bean
    public SftpServer sftpServer() {
        return CitrusEndpoints.sftp()
                .server()
                .port(2222)
                .autoStart(true)
                .user("citrus")
                .password("admin")
                .allowedKeyPath("classpath:ssh/citrus_pub.pem")
                .build();
    }
}
```
In above file, 'CitrusEndpoints' can't be resolved.
**Additional information**
Thank you in advance

**Comment by svettwer** [comment]
Hi!

Have you added a `citrus-application.properties` to your resource folder containing the class path to your java config?
E.g.  `citrus.spring.java.config=com.consol.citrus.samples.todolist.EndpointConfig`

BR,
Sven

**Comment by svettwer** [comment]
Ah, sorry!
My bad. You're missing the `CitrusEndpoints` resolution.
This should be resolvable by importing `import com.consol.citrus.dsl.endpoint.CitrusEndpoints;`

Do you use a IDE with auto imports?

**Comment by CassieRyu** [comment]
Thank you @svettwer 
I tried on Gradle as well, it's working for `CitrusEndpoints` now. But unfortunately, `sftp` can't be resolved now.
**build.gradle** file
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:1.5.6.RELEASE")
    }
}
plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.2.61'
    id 'application'
}

mainClassName = 'App'
repositories {
    mavenCentral()
}

dependencies {
    compile 'com.google.guava:guava:23.0'
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
    testCompile group: 'junit', name: 'junit', version: '4.12'
    compile("org.springframework.boot:spring-boot-starter")
    compile("org.springframework.boot:spring-boot-starter-web")
    compile("com.consol.citrus:citrus-simulator-starter:1.0.0")
    compile("com.consol.citrus:citrus-ftp:2.7.6")
    compile("com.consol.citrus:citrus-java-dsl:2.7.2")

}
sourceCompatibility = 1.8
targetCompatibility = 1.8

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'

jar {
    group = "com.consol.citrus.simulator"
    baseName = 'citrus-simulator-sample'
    version =  '1.0.0'
}
```
my sftp server file sftpServer.java
```
import com.consol.citrus.dsl.endpoint.CitrusEndpoints;
import com.consol.citrus.ftp.server.SftpServer;
import org.springframework.context.annotation.Bean;

public class sftpServer {
    @Bean
    public SftpServer sftpServer() {
        return CitrusEndpoints.sftp()
                .server()
                .port(2222)
                .autoStart(true)
                .user("citrus")
                .password("admin")
                .allowedKeyPath("classpath:ssh/citrus_pub.pem")
                .build();
    }
}
```
Where the `sftp` of `CitrusEndpoints.sftp()` can't be resolved.
Thank you again!

**Comment by svettwer** [comment]
Hi!

I've recognized you're using different citrus versions for citrus dependencies.
```
    compile("com.consol.citrus:citrus-ftp:2.7.6")
    compile("com.consol.citrus:citrus-java-dsl:2.7.2")
```
I'd recommend to use the latest release 2.7.7.

In addition, it seems that you want to setup a citrus simulator with sftp.
This is not implemented yet.

I would recommend to use a embedded sftp server as shown in the [sftp sample](https://github.com/citrusframework/citrus-samples/tree/master/samples-ftp/sample-sftp).
In case you want to try this attempt, please use the following dependencies.

```xml
    <dependency>
      <groupId>com.consol.citrus</groupId>
      <artifactId>citrus-core</artifactId>
      <version>${citrus.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.consol.citrus</groupId>
      <artifactId>citrus-java-dsl</artifactId>
      <version>${citrus.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.consol.citrus</groupId>
      <artifactId>citrus-ftp</artifactId>
      <version>${citrus.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
```

BR,
Sven

**Comment by svettwer** [comment]
Hi!

Second try for an answer ;-)

So at first, it looks like you're going to use a citrus simulator with a sftp server. Therefore you'd have to use the  *Endpoint support* feature as described in the [documentation](http://citrusframework.org/citrus-simulator/#endpoint).
There are also various samples included in the [citrus simulator repository](https://github.com/citrusframework/citrus-simulator/tree/master/simulator-samples).

In addition, I've recognized, that you're using two citrus version
```    
    compile("com.consol.citrus:citrus-ftp:2.7.6")
    compile("com.consol.citrus:citrus-java-dsl:2.7.2")
```
The citrus version should be the same. Ideally I'd recomment 2.7.7.

I've tried it locally with the samples provided in the repository.
If I add 
```xml
    <dependency>
      <groupId>com.consol.citrus</groupId>
      <artifactId>citrus-ftp</artifactId>
      <version>${citrus.version}</version>
    </dependency>
```

I'm able to create my endpoint as follows:
```java
    @Override
    public Endpoint endpoint(ApplicationContext applicationContext) {
        return CitrusEndpoints.sftp()
                .server()
                .port(2222)
                .autoStart(true)
                .user("citrus")
                .password("admin")
                .allowedKeyPath("classpath:ssh/citrus_pub.pem")
                .build();
    }
```

BR,
Sven

**Comment by CassieRyu** [comment]
Awesome!! Thank you so much @svettwer ! All methods and keywords are recognized now!
Btw,  do you have any idea about my first question? 
```
I want to use Citrus to support SFTP mock server instead of real sftp server 
in test environment. It's like to setup the mock server that can retrieve a XML 
file on another server in an interval time  and able to response another XML 
file back to the server. Is this possible to achieve by using Citrus?
```
Thanks a lot,
Shan

**Comment by svettwer** [comment]
Hi Shan!

Glad I could help. 
> I want to use Citrus to support SFTP mock server instead of real sftp server 
in test environment.

Sounds like a good idea to me! ;-)

> It's like to setup the mock server that can retrieve a XML 
file on another server in an interval time  and able to response another XML 
file back to the server. Is this possible to achieve by using Citrus?

I'm not sure whether I understand the use case correctly.
So you want the citrus sftp server to get a file from another real ftp server in a interval time and the citrus sftp server should then put another file back to the real ftp server?
If this is the case I would recommend to go with the citrus ftp client. 
The client would be able to get a file from a server and send another file back.

I hope I got your point.

BR,
Sven

**Comment by CassieRyu** [comment]
Coo~ thank you @svettwer
I've updated the versions consistent as your suggestion.
 And I'll take a look at sftp client later.
Thank you again for your kind help!!
