### ISSUE TITLE
not supported jdbc statement function 'executeBatch'

### ISSUE THREAD

**Issue by laura098** [citrusframework/citrus#490]
The batch update function of tibco is not supported in the citrus jdbc adapter. This function is needed for all inserts that affect more than one row. And all updates which gets a list of different where-clauses.
Please see the attached file for some screenshots.

Best Regards,
Laura
[JDBC-Batch Update-Bug.docx](https://github.com/citrusframework/citrus/files/2419140/JDBC-Batch.Update-Bug.docx)

**Comment by svettwer** [comment]
Hi!

Yes this is absolutely the case. We've just implemented a set of driver functionality with the idea of extending the driver over time and on demand.

Thx for reporting your demand on this feature! :+1: 

BR,
Sven

**Comment by svettwer** [comment]
closed in favor of https://github.com/citrusframework/citrus-db/issues/36 as the implementation effort goes into the driver
