### ISSUE TITLE
Unable to create Local Webdriver for Opera, Android Webview

### ISSUE THREAD

**Issue by SajanaKrishnan** [citrusframework/citrus#495]
**Citrus Version**
2.7.6

**Question**
When I try BrowserType.OPERA or OPERABLINK - I get "Unsupported local browser type: 
". Also, I was looking for options to BrowserType = AndroidWebview. Can you please help

**Additional information**

**Comment by svettwer** [comment]
Hi!

Citrus doesn't support all Browsers supported by Selenium.
The supported Browsers can be found in the [documentation of the selenium integration](http://citrusframework.org/citrus/reference/html/index.html#selenium-browser).

I've opened #498 to keep track of this.

BR,
Sven
