### ISSUE TITLE
404 error for todo-list and todo-app

### ISSUE THREAD

**Issue by santosh1303** [citrusframework/citrus#507]
Hi, I received 404 error when clicked on todo-list and todo-app links available in
https://github.com/citrusframework/citrus-samples/tree/master/samples-cucumber/sample-cucumber/java-dsl

**Comment by svettwer** [comment]
Hi!

Thx for the hint! :+1:

BR,
Sven

**Comment by svettwer** [comment]
Hi!

There is an issue in the sample repository concerning this topic. 
I'll close this issue in favor of https://github.com/citrusframework/citrus-samples/issues/29.

BR, 
Sven
