### ISSUE TITLE
Connectivity to Oracle service bus

### ISSUE THREAD

**Issue by bhaktizade** [citrusframework/citrus#508]

**Comment by bhaktizade** [comment]
need to create context.xml for an oracle service bus project. need the parameters for the same or any reference to existing osb-citrus project

**Comment by christophd** [comment]
we need more information to help you out with your question. how do you want to connect with OSB? which parameters are you speaking of?. Please point out your situation and what you are trying to do with Citrus and OSB

**Comment by bhaktizade** [comment]
Hi,

We are trying to implement Citrus for local testing of OSB services which includes proxy and business services. It will be helpful if you can provide a sample context file for OSB configurations with Citrus so that it will be easy for me to understand which beans are to be used .

Currently we want to connect to our existing OSB server which is a weblogic server.

**Comment by christophd** [comment]
the issue seems to be blocked.
@bhaktizade please provide some more information or close the issue

**Comment by bhaktizade** [comment]
Hello

You can close the issue as it is resolved from my end.
Thank you for the efforts.

**Comment by svettwer** [comment]
Hi!

Thx for the information.
I'd would be great if you could share some details with the community.

BR,
Sven
