### ISSUE TITLE
How does Citrus check xml response.

### ISSUE THREAD

**Issue by NShpakov** [citrusframework/citrus#517]
Hello! I`ve got the one question. My app returns xml nodes in a different order. Could citrus to compare the xml in response by template? I mean does the node sort before validation?

**Comment by NShpakov** [comment]
For example my template for validation: `<?xml version="1.0" encoding="UTF-8"?>
<todo xmlns="http://citrusframework.org/samples/todolist">
  <id>${todoId}</id>
  <title>${todoName}</title>
  <description>${todoDescription}</description>
  <done>false</done>
</todo>` 

My app returned me this xml : `<?xml version="1.0" encoding="UTF-8"?>
<todo xmlns="http://citrusframework.org/samples/todolist">
  <title>${todoName}</title>
  <id>${todoId}</id>
  <description>${todoDescription}</description>
  <done>false</done>
</todo> `

**Comment by christophd** [comment]
Ordering of elements in XML is not optional so the validator will raise validation errors by default when ordering is not as expected. You can only switch to XPath validation in this case in order to validate the elements without taking care on element ordering.
