### ISSUE TITLE
HttpMessage has String payload with random encoding, logger outputs with correct encoding

### ISSUE THREAD

**Issue by bergerst** [citrusframework/citrus#522]
**Citrus Version**
2.7.1

**Expected behavior**
Special characters such as äöü in the SOAP response of a Client call should be handled correctly. You should be able to validate them using `.validate("//*:x/text()", Matchers.stringContainsInOrder(Arrays.asList("äöü")));`

**Actual behavior**
*:x/text() produces a String with Ã¤Ã¶Ã¼ in it, so the XPath validation fails. I was able to debug the issue so far as to see that the HttpMessage during the XPath validation has a payload with wrongly encoded special characters.

During the logging of the response message, the encoding is correct, though.

**Test case sample**
Can't really provide a good example because you need a REST provider for it and I'm not familiar with the REST providers used in the JUnit tests here.

**Comment by svettwer** [comment]
Hi!

Unfortunately I'm unable to reconstruct the issue.

I've altered a soap sample as follows:
```java
public class TodoListIT extends TestNGCitrusTestDesigner {

    @Autowired
    private WebServiceClient todoClient;

    @Test
    @CitrusTest
    public void testAddTodoEntry() {
        variable("todoName", "citrus:concat('todo_', citrus:randomNumber(4))");
        variable("todoDescription", "Description äüö: ${todoName}");

        soap()
            .client(todoClient)
            .send()
            .soapAction("addTodoEntry")
            .payload(new ClassPathResource("templates/addTodoEntryRequest.xml"));

        soap()
            .client(todoClient)
            .receive()
            .payload(new ClassPathResource("templates/addTodoEntryResponse.xml"));

        soap()
            .client(todoClient)
            .send()
            .soapAction("getTodoList")
            .payload(new ClassPathResource("templates/getTodoListRequest.xml"));

        soap()
            .client(todoClient)
            .receive()
            .validate("//todo:description/text()",
                      Matchers.stringContainsInOrder(Collections.singletonList("äüö")));
    }

}
```

Which charset are you using?
Please make sure that the used charset matches the configured charset. 
The charset is configurable via:
* System properties: `citrus.file.encoding`
* Environment variables: `CITRUS_FILE_ENCODING`

Default is: `Charset.defaultCharset()`

For more information, please have a look at the [Application environment settings](http://citrusframework.org/citrus/reference/html/index.html#application-environment-settings)

BR,
Sven

**Comment by bergerst** [comment]
Sorry, I was mistaken about it being a SOAP call, was a REST call instead. I've set the citrus.file.encoding to UTF-8, even made sure using System.getProperties().get("citrus.file.encoding"), but it still returns the wrong characters.

**Comment by svettwer** [comment]
Hi!

The payload is parsed with the charset specified in `citrus.file.encoding`. That being said, the charset of the message payload may differ from the charset of your local work station or the charset of your source code in the IDE.

So the charset of the Message sent by your system under test has to match `citrus.file.encoding`.

BR,
Sven

**Comment by bergerst** [comment]
I've found out that citrus.file.encoding really has nothing to do with how the REST response is parsed. Instead, the charset is decided in part of Spring's code.

The class RestTemplate uses a StringHttpMessageConverter. StringHttpMessageConverter looks up if the HTTP response has a charset set in the HTTP header in the method getContentTypeCharset and uses ISO-8859-1 as per specification here: https://www.w3.org/Protocols/rfc2616/rfc2616-sec3.html .

Because the Content Type was just text/xml without any charset, Spring used ISO and thus parsed the UTF-8 string as ISO-8859-1 string.

**Comment by svettwer** [comment]
Hi!

Glad that you found the solution!
Yeah, you're right! In my mind I was still in the SOAP context. :man_facepalming: 

BR,
Sven
