### ISSUE TITLE
Initial local build failing in citrus-arquillian

### ISSUE THREAD

**Issue by christophd** [citrusframework/citrus#524]
**Citrus Version**
v2.7.7

**Expected behavior**
Initial local build with empty Maven repository (~/.m2/repository) should be successful

**Actual behavior**
Build fails with citrus-arquillian module because of missing dependency for 'org.yaml.snakeyaml'

**Test case sample**
Build Citrus with empty Maven repository

**Comment by christophd** [comment]
see pull-request #525 😄

**Comment by svettwer** [comment]
:+1: 

I just don't unterstand why we can assume `org.yaml.snakeyaml` as provided here :thinking:

**Comment by christophd** [comment]
The provided scope tells Maven to get the dependency at compile time. For runtime the dependency is not taken into account as it is marked as provided. This way the dependency is loaded at the initial build but not as transitive dependency when someone is using citrus-arquillian module at runtime.

**Comment by christophd** [comment]
it would be good though to understand which module/library is using 'snakeyaml'. In the Citrus POM it has not been declared as dependency so far. So it must be a transitive dependency of one of the other libs that is not loaded for some reason.

**Comment by svettwer** [comment]
> The provided scope tells Maven to get the dependency at compile time. For runtime the dependency is not taken into account as it is marked as provided. This way the dependency is loaded at the initial build but not as transitive dependency when someone is using citrus-arquillian module at runtime.

Got that so far but nevertheless some instance has to provide `org.yaml.snakeyaml` during runtime and I've no clue which part does this.

**Comment by svettwer** [comment]
> it would be good though to understand which module/library is using 'snakeyaml'. In the Citrus POM it has not been declared as dependency so far. So it must be a transitive dependency of one of the other libs that is not loaded for some reason.

Yeah that's my point why I wanted to investigate this a little bit more. The build might be fixed but the root cause is still unclear.

**Comment by christophd** [comment]
> Got that so far but nevertheless some instance has to provide org.yaml.snakeyaml during runtime and I've no clue which part does this.

I am sure that 'org.yaml.snakeyaml' is an optional dependency in one of the Citrus dependencies. So it is a transitive dependency that is not loaded as the dependency is optional. So when your project uses the citrus modules and you do not use snakeyaml APIs in your tests everything is fine.

As soon as you start to use snakeyaml stuff you need to add the dependency to your project POM on your own.

The compile time dependency is required though as citrus-arquilian is resolving all dependencies and transitive dependencies in order to make the arquillian integration work with shrinkwrap micro deployments.

Hope this makes some things more clear

**Comment by svettwer** [comment]
>As soon as you start to use snakeyaml stuff you need to add the dependency to your project POM on your own.

And that's why I think this is a bigger issue. The first experience of the user would be that Citrus does not work *somehow* as soon as `org.yaml.snakeyaml` is required. The user would have to investigate the root cause and add snakeyaml as a dependency.
As we don't know anything about the environment, that Citrus will run in, we should deliver a project including all potentially required dependencies instead of lowering the user experience by saving some KB because of a `provided` dependency we don't ship.

**Comment by christophd** [comment]
I think that it is a common thing to declare optional dependencies that should be added on demand when it is used. A library should only ship those dependencies that are required to operate the core functionality. In this case 'snakeyaml' is not even used by Citrus itself but by a dependency library that has declared it as `optional`.

If you start to add all these to the Citrus list of dependencies you will get a beast that all users will complain about that do not use the corner cases where `snakeyaml` would be mandatory.

I think Citrus is having a lot of dependencies that is already a bit of burden we have to carry because of the nature that we support so many different technologies and messaging transports.

I think if we can safely declare some dependencies as optional or provided we should make use of that.

**Comment by svettwer** [comment]
Hi!

>In this case 'snakeyaml' is not even used by Citrus itself but by a dependency library that has declared it as optional.

If this is the case for all use cases of citrus (including all corner cases), I'm absolutely okay with the decision to put it in the `provided` scope. :+1: 

Let me just check which dependency is using `snakeyaml` and how Citrus might be influenced by it.

**Comment by svettwer** [comment]
Hi!

I investigated the issue. There is a dependency clash with snakeyaml. TestNG ist using snakeyaml 1.17 while the fabric8 kubernetes client requires snakeyaml 1.15 as a third party dependency. This clash was pretty hard to find as `com.fasterxml.jackson.dataformat:jackson-dataformat-yaml`  which is using 1.15 is not listing its dependencies with `mvn dependency:tree -Dverbose`.

If it's not too late for me, this would imply the following:
As soon as you use the citrus-kubernetes module with TestNG in a fresh environment, citrus would not be executable as mvn would resolve snakeyaml 1.17 but the fabric8 kubernetes client would expect snakeyaml 1.15 to be available in the maven repository. :dizzy_face: 

BR,
Sven

**Comment by christophd** [comment]
> As soon as you use the citrus-kubernetes module with TestNG in a fresh environment, citrus would not be executable as mvn would resolve snakeyaml 1.17 but the fabric8 kubernetes client would expect snakeyaml 1.15 to be available in the maven repository

Maven will include v1.17 then in the classpath. As long as v1.17 is downwards compatible with v1.15 the project is fine to execute with both TestNG and fabric8 kubernetes client. Actually you can not say if it works beforehand. This is something to find out at runtime in a particular test.
