### ISSUE TITLE
Conversion from byte array payload to String fails using JsonMappingValidationCallback

### ISSUE THREAD

**Issue by lmeyer4** [citrusframework/citrus#529]
**Citrus Version**
2.7.7

**Expected behavior**
In JsonMappingValidationCallback the method _T readJson(Message message)_  should convert the payload in the message parameter into an object of type T.

**Actual behavior**
If the payload is a byte array representing a json string, the method throws an MismatchedInputException. This happens because _message.getPayload(String.class)_ returns a numeric representation of the byte array  (e.g. "[123, 34, 105, 100, 34, 58, 32, 34, 49, 50, 51, 34, 125]") instead of a direct representation (e.g. "{"id":"123"}"). This numeric representation is used as parameter to a _readValue_ method from ObjectMapper, which throws the Exception. The _readValue_ method can only convert strings, if they are formatted in json.

**Test case sample**
```java
static class Product {

        private String id;

        public Product() {
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }
    }

    @Test
    @CitrusTest
    public void validateJsonPayload() {
        String id = "123";
        String json = String.format("{\"id\": \"%s\"}", id);

        Message message = new JmsMessage();
        message.setPayload(json.getBytes());

        (new JsonMappingValidationCallback<Product>(Product.class, new ObjectMapper()) {
            @Override
            public void validate(Product payload, Map<String, Object> headers, TestContext context) {
                assertThat(payload.getId()).isEqualTo(id);
            }
        }).validate(message, null);

    }
```

**Comment by svettwer** [comment]
Okay, got your point!

Thx for the explanation! :+1:

**Comment by christophd** [comment]
You can transform/convert message payloads prior to validation now in Citrus 3.0
