### ISSUE TITLE
How to receive an unknown amount of messages?

### ISSUE THREAD

**Issue by mischcon** [citrusframework/citrus#536]
**Citrus Version**
2.7.7

**Question**
How to receive an unknown amount of messages / How to receive multiple messages from one endpoint at the same time?

I want to test if my application fires not only the correct syslog messages (this can be verified using Message Selectors + Validators), but also the correct amount of messages. 

What I think of is to somehow get a list of messages + validate afterwards, that the amount of messages matches my expectation.

**What I've tried so far**
I tried to call 'receive' until I get an ActionTimeoutException (thrown because there are no more messages, wrapped in a TestCaseFailedException)
```
List<Message> receivedMsgs = new LinkedList();
try {
    while(true) {
        Message msg = ... // receive the message + extract it from the message store
        receivedMsgs.add(msg);
    }
    // If there are no more messages an ActionTimeoutException wrapped in a TestCaseFailedException will be thrown
} catch(TestCaseFailedException e) {
    // if the cause of the TestCaseFailedException is in fact a ActionTimeoutException, than return the received messages
    if (e.getCause() instanceof ActionTimeoutException) {
        return receivedMsgs;
    }
    // if the cause of the TestCaseFailedException is something different, rethrow the exception
    else {
        throw e;
    }
}
```

Unfortunately the 'ActionTimeoutException' is caught in the class 'TestCase.java'
```
    /**
     * Executes a single test action with given test context.
     * @param action
     * @param context
     */
    public void executeAction(TestAction action, TestContext context) {
        if (!CollectionUtils.isEmpty(context.getExceptions())) {
            throw context.getExceptions().remove(0);
        }

        try {
            if (!action.isDisabled(context)) {
                testActionListeners.onTestActionStart(this, action);
                setActiveAction(action);

                action.execute(context);
                testActionListeners.onTestActionFinish(this, action);
            } else {
                testActionListeners.onTestActionSkipped(this, action);
            }
        } catch (Exception | AssertionError e) {
            testResult = TestResult.failed(getName(), testClass.getName(), e);
            throw new TestCaseFailedException(e);
        }
    }
```
This catch block sets the testResult to 'failure' before the exception gets wrapped in a 'TestCaseFailedException' which means that even if I catch the 'TestCaseFailedException' the test still counts as 'failure'.

Is there any other option to receive multiple messages?
Thanks a lot!

**Comment by mischcon** [comment]
Edit: 
I found out that I can use the TestRunner to set the TestResult to null manually to prevent the test from being marked as 'failed', but this seems quite hacky. Is there a better way?

```
List<Message> receivedMsgs = new LinkedList();
try {
    while(true) {
        Message msg = ... // receive the message + extract it from the message store
        receivedMsgs.add(msg);
    }
    // If there are no more messages an ActionTimeoutException wrapped in a TestCaseFailedException will be thrown
} catch(TestCaseFailedException e) {
    // if the cause of the TestCaseFailedException is in fact a ActionTimeoutException, than return the received messages
    if (e.getCause() instanceof ActionTimeoutException) {
        ((DefaultTestRunner) runner).getTestCase().setTestResult(null);
        return receivedMsgs;
    }
    // if the cause of the TestCaseFailedException is something different, rethrow the exception
    else {
        throw e;
    }
}
```

**Comment by svettwer** [comment]
Hi!

It would be possible to receive a specific number of messages on a given endpoint by just receiving them in a loop, followed by a expected timeout.

```java 
public class TodoListIT extends TestNGCitrusTestRunner {

    @Autowired
    private HttpClient todoClient;

    @Autowired
    private HttpServer todoServer;

    @Test
    @CitrusTest
    public void testGet() {

        //Simulating a system under test sending messages
        for(int i = 0; i < 3; i++){
            http(http -> http.client(todoClient)
                    .send()
                    .get("/todolist")
                    .accept(MediaType.TEXT_HTML_VALUE)
                    .fork(true));
        }

        //Expect a specific amount of requests on a specific endpoint
        for(int i = 0; i < 3; i++){
            http(http -> http.server(todoServer)
                    .receive()
                    .get("/todolist"));
        }

        //ensure that no further messages arrive
        receiveTimeout(
                receiveTimeout ->
                        receiveTimeout.endpoint(todoServer));
    }
}
```
I recommend to ensure, that the test cases are well separated to keep the tests maintainable and readable.

In case of an unknown amount:
>I want to test if my application fires not only the correct syslog messages (this can be verified using Message Selectors + Validators), but also the correct amount of messages.

What's your use case here? From your statement it seems like the *correct amount of messages* is known for the test case.

BR,
Sven

**Comment by mischcon** [comment]
I have two different use cases for this:

1. verify that my application sends only the exepcted amount of messages - for this use case your proposed solution works very well (since I expect a timeout - in case a message arrives I do not receive a timeout --> test failed). Thank you for that! :+1: 
2. I have multiple tests run in parallel, each of them triggering the sending of syslog messages. I want to purge the syslog message channel only partly (just erase the syslog messages that belong to one test). To accomplish this task I just found out that there is a 'purgeEndpoint' / 'purgeChannel' action that should do the job :)

**Comment by svettwer** [comment]
Hi!

Glad you found a solution! :+1: 

BR,
Sven
