### ISSUE TITLE
begin to use citrus with existing cucumber test cases

### ISSUE THREAD

**Issue by wushuzh** [citrusframework/citrus#537]
**Question**
I already have some cucumber + Junit test cases without using citrus.
Now I want to introduce citrus to my test suite for all new added test cases in the future.
But I cannot config correctly with new added citrus jar deps and **cucumber.properties** so old and new test cases could co-exist.

<br/>

**Citrus Version**
3 testCompile with following dependencies in build.gradle file:
**citrus-core, citrus-java-dsl, citrus-cucumber with version  2.7.8**

<br/>
<br/>

**What I've tried so far**
Previously my testCompile includes **io.cucumber:cucumber-java** and **cucumber-junit**, the test could try without problem: launch `gradle clean test` and output is build successful and test reports are generated. (to make test quicker I use dryRun as true)

1. But as soon as I added citrus-cucumber (also with citrus-core and citrus-java-dsl) into my build.gradle file as testCompile deps, the error happens as following.
```
com.mycompany.RunTest > initializationError FAILED
    cucumber.runtime.CucumberException: 
           java.lang.NoSuchMethodException: 
               cucumber.runtime.java.CitrusBackend.<init>(cucumber.runtime.io.ResourceLoader, io.cucumber.stepexpression.TypeRegistry)

        Caused by:
        java.lang.NoSuchMethodException: cucumber.runtime.java.CitrusBackend.<init>(cucumber.runtime.io.ResourceLoader, io.cucumber.stepexpression.TypeRegistry)
```
2. Then I added the the file **src/test/resources/cucumber.properties** and launch gradle clean test -i again, Same error msg as above.
```
cucumber.api.java.ObjectFactory=cucumber.runtime.java.CitrusObjectFactory
```

3. I added cucumber glue options into my RunTest.java file as following and launch gradle cmd again. Same error msg as above.
```
@RunWith(Cucumber.class)
@CucumberOptions(
    plugin = { "pretty", 
        "html:build/reports/cucumber", 
        "json:build/test-results/cucumber/cucumber.json" }, 
    monochrome = true, 
    glue = { "com.mycompany", "com.consol.citrus.cucumber.step.runner.core" }, 
    dryRun=true)
public class RunTest {
}
```

<br/>
**Additional information**
No

**Comment by svettwer** [comment]
Hi!

What you could do in first place is to separate the citrus-cucumber tests and the cucumber only tests into different test modules/projects and execute them sequentially. 

I'll have a look whether it's possible to come around this separation.

BR,
Sven

**Comment by svettwer** [comment]
Hi!

I was able to reconstruct your issue by removing the `cucumber.properties` from the project.
Here is a working [sample project](https://github.com/svettwer/cucumber-vanilla-plus-citrus) with Citrus-Cucumber tests and vanilla Cucumber tests in one module. Just check it out and execute `mvn clean verify`. I hope that helps you out.
It would be great if you could provide more details about the differences between your project setup and the sample project setup in case the sample project setup did not work for you.

BR,
Sven

**Comment by wushuzh** [comment]
Hi svettwer,

Thanks a lot for your kind help and sample project. It gave me a great start point.

- Your sample project run perfectly without any changes.
- Change version of cucumber-java and cucumber-junit >= 3 in sample project pom.xml will cause **NoSuchMethodException** from cucumber.runtime.CucumberException.

Now I guess there are some compatible problems between versions of cucumber and citrus ? If so, the reasonable move would be to ask my project to downgrade the cucumber version to 2.x.x when introducing citrus fwk 2.7.8, right ? Do we have any issues id for supporting latest version of cucumber so I could know the progress of fix ?
 

Best regards,
wushuzh

**Comment by svettwer** [comment]
Hi!

Yes, there are breaking changes.

With the upcoming release 2.8.0 of Citrus, cucumber 3.x is supported (#403) so that a setup like this is possible.
```xml
    <properties>
        <citrus.version>2.8.0</citrus.version>
        <cucumber.version>3.0.2</cucumber.version>
    </properties>
```

I opened #539 for you to keep track of the 4.x.x support.

>If so, the reasonable move would be to ask my project to downgrade the cucumber version to 2.x.x when introducing citrus fwk 2.7.8, right ?

This would be one option. Another option would be to create two separate modules as mentioned in https://github.com/citrusframework/citrus/issues/537#issuecomment-440188073 with different dependencies.

So you would have one module with your cucumber >= 3.0.0 vanilla tests and one module with your citrus-cucumber tests with citrus v2.7.8 and cucumber 2.x.x. In this scenario it might be required to ensure that the modules are running in separate processes with different dependency trees so that the dependency clash between cucumber 2.x.x and >= 3.0.0 is compensated. A advantage of this is, that you could use citrus as it is but also use new cucumber features. As soon as Citrus supports the newer cucumber versions, it should be possible to merge both modules again and run the tests in parallel as in the sample project.

BR,
Sven

**Comment by wushuzh** [comment]
Hi Sven,

Thanks a lot for this details explanation.

I will close this issue.

Best regards,
wushuzh

**Comment by sainisumit344** [comment]
Hi svettwer,

I am migrating cucumber 3.0.2 to latest version 6.9.0 but I am not able to run its giving issue with cirtus version 2.8.0.

could you please let me know what version I should use of citrus how should I proceed.

Thanks

**Comment by svettwer** [comment]
Hi @sainisumit344 :wave: 

I'm not involved in Citrus anymore. Maybe @christophd can provide some advice.

**Comment by christophd** [comment]
Citrus 2.8.0 only works with Cucumber 3.x

In case you want to upgrade to newer Cucumber versions please upgrade to [Citrus 3.0.0-M2](https://github.com/citrusframework/citrus/releases/tag/v3.0.0-M2)

**Comment by sainisumit344** [comment]
Hi @christophd,

is Citrus 3.0.0-M2 is stable version? I am not able to use Citrus 3.0.0-M2 I mean dependency of Citrus 3.0.0-M2 is not being downloaded. 
could you please suggest how I can upgrade Cucumber 3.x to Cucumber 6.9.0.
Thank you in Advance christophd

Thanks,
sumit saini

**Comment by christophd** [comment]
Hi @sainisumit344 

3.0.0-M2 is the 2nd milestone of Citrus 3.0.0. Milestones have reached a basic stability and we use it in several projects already. However changes are likely to happen in this state of the framework until the final 3.0.0 version will be released (estimated Q1 of 2021). 

What module are you missing? The modules are available on Maven central (https://search.maven.org/search?q=g:com.consol.citrus) and should be downloaded by default.

3.0.0-M2 uses Cucumber 5.7 support. Cucumber 6.9.0 support has been added recently and will be available in 3.0.0-M3 (coming this month).

**Comment by sainisumit344** [comment]
Hi @christophd 

As you suggested I tried citrus version 3.0.0.M2 with cucumber 5.7.0 its giving me compile time error build failed

error: cannot find symbol
import com.consol.citrus.dsl.builder.ReceiveMessageBuilder;
                                    ^
  symbol:   class ReceiveMessageBuilder
  location: package com.consol.citrus.dsl.builder
Thanks,
sumit saini

**Comment by christophd** [comment]
This is because you need to migrate from Citrus 2.8.0 to 3.x, too. Could you please have a look at these [cucumber-samples](https://github.com/citrusframework/citrus-samples/tree/master/samples-cucumber) and see how things are done in 3.x

If you have further errors I would suggest to open new issues and please give the detailed error information (e.g. stacktrace). Thx!
