### ISSUE TITLE
Support Cucumber Version >= 4.0.0

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#539]
Extracted from #537
---------------

**User story**
As a Citrus user, I would like to use cucumber version >= 4.0.0 with my citrus tests, so that I can use the 4.x.x features of cucumber.

**Additional information**
- 2.7.x of citrus supports Cucumber 2.x
- 2.8.x of citrus supports Cucumber 3.x

**Comment by svettwer** [comment]
Update: The major update to cucumber 4 is mostly done. I just have to add some docs and test before this is ready for review.

BR,
Sven

**Comment by hmmlopez** [comment]
Hello Sven,
Will this branch eventually be merged with the master one? 
I'm looking forward to being able to use Cucumber 4 with Citrus. When merged with the master branch I could use it directly with the 2.9.0-SNAPSHOT until it's released (any info about the release of 2.9.0 maybe?).
For now, I'll use the 2.8.0 version with Cucumber 3, thanks for keeping up the good work with CitrusFramework.

**Comment by svettwer** [comment]
Hi @hmmlopez,

yes, this branch will eventually be merged as soon as development and review have been finished. I just realized that in Cucumber 4, some API changes affect the Citrus after suite life cycle hooks. I am in touch with the Cucumber-jvm team to fix this but I have to spent some hours to get into cucumber a little bit more.

>When merged with the master branch I could use it directly with the 2.9.0-SNAPSHOT until it's released

Currently the master build does not publish a snapshot automatically at the moment, but I will create a snapshot after the merge now that I know it is requested. :+1: 

>any info about the release of 2.9.0 maybe

Yes, based on our [road map for 2019](http://citrusframework.org/news/2019/01/17/citrus-roadmap-2019/) 2.9.0 is _planned_ for Q2 so by the end of June. As I am currently working on a lot of customer projects, I am not sure whether I can guarantee a 2.9.0 with all the features.

>For now, I'll use the 2.8.0 version with Cucumber 3 [...]

Awesome! :tada: 

> [...] thanks for keeping up the good work with CitrusFramework. 

You're welcome :smiley: 

BR,
Sven

**Comment by hmmlopez** [comment]
Hello Sven,

Thanks for the update. 
When merged with master, I could live with a local SNAPSHOT as well. But would be nice if I can pull the snapshot from the citrus repository directly, then I don't need to clone the repository and build it locally myself.

Thanks again,
Humphrey

**Comment by hmmlopez** [comment]
Hello, I have a question, not sure if this is the correct place to add questions, so maybe you can redirect me.

When doing a get on an HTTP endpoint I'm receiving a list of objects, which in JSON format.
I need to call a next HTTP endpoint for each object. The list of objects is being saved in a citrus variable.

I'm using the Runner (not Designer) to interact with the endpoints. I need to be able to access the TestContext to extract the Citrus variable and convert it into a Java Object. 

As explained here I'm supposed to use the **CitrusResource** to inject the **TestContext** but it is always **null**.
https://stackoverflow.com/questions/49659177/turn-citrus-variable-into-java-variable

```java
public class StepDefs {

    @CitrusResource
    protected TestRunner runner;

    @CitrusResource
    private TestContext context;

    @Given("Hello world")
    public void helloWorld() {
        runner.traceVariables();
        context.getVariable("myVariable");
    }
}

```

I can see the variable when doing the traceVariables() on the runner but I'm unable to extract it to java. 
This is a Step Definition class for Cucumber.

Humphrey

**Comment by svettwer** [comment]
Hi @hmmlopez!

>I have a question, not sure if this is the correct place to add questions, so maybe you can redirect me.

In general, this would be a Question worth a dedicated ticket. For more information on the workflow, issue management, etc., please have a look at our [contribution guidelines](https://github.com/citrusframework/citrus/blob/master/CONTRIBUTING.md).

I have extracted your question into issue #657.

BR,
Sven

**Comment by christophd** [comment]
Hi Sven,

how is the status of this? Is Cucumber 4.x support still in scope for Citrus 2.8.1 or 2.9.0? Any rough plan when to merge this?

I can also help to get this done if you need some help here but I would need to know what's missing to merge this.

Cheers,
Christoph

**Comment by hmmlopez** [comment]
Please! And could you also fix the TestContext with Cucumber? I’m not able to get a variable in Java from the Context.

**Comment by Metalmix** [comment]
Any news on that?

**Comment by RaymondMouthaan** [comment]
This issue is open for quite some time, like many others I am curious about it's status. @svettwer ?

**Comment by froemra** [comment]
Waiting for this, too ...

**Comment by blackfoxoh** [comment]
@svettwer Thanks for your valuable work on this. Of course it's up to you when and how much time you can afford on citrus. A little statement like "maybe fixed in a month" or "for sure not in the next half year" or any other rough indication how this might go on would be very appreciated...

**Comment by christophd** [comment]
Cucumber dependency has been updated with Citrus 3.0
