### ISSUE TITLE
[SOAP] How can I tell citrus to not to add its own SOAP envelope

### ISSUE THREAD

**Issue by coding-yogi** [citrusframework/citrus#541]
**Citrus Version**
2.7.8

**Question**
I do not want citrus to add its own envelope as its duplicating the envelop and also the one which citrus adds doesn't match the way I would like it to be

**What I've tried so far**
I didn't see any option to set this

**Additional information**
I woud want request to be as below
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ser="http://service.ws.um.carbon.wso2.org">
    <soap:Header/>
    <soap:Body>
```

Request generated is as below
```
<?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">
  <env:Header/>
  <env:Body>
    <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ser="http://service.ws.um.carbon.wso2.org">
    <soap:Header/>
    <soap:Body>

```

**Comment by coding-yogi** [comment]
Tried below with no impact on request sent
`       .keepSoapEnvelope(true)`

**Comment by svettwer** [comment]
HI!

Sorry for the delayed response. I assume you perform a send operation here, right? Currently `.keepSoapEnvelope(true)` does only affect incoming messages (receive operations) for envelope validation purposes. 

It would be possible to add custom namespaces in the payload as follow:
```xml
<todo:addTodoEntryRequest xmlns:todo="http://citrusframework.org/samples/todolist">
  <todo:title>${todoName}</todo:title>
  <todo:description>${todoDescription}</todo:description>
</todo:addTodoEntryRequest>
```

and a registration of the schema in Citrus
```java
    @Bean
    public SimpleXsdSchema todoListSchema() {
        return new SimpleXsdSchema(new ClassPathResource("schema/TodoList.xsd"));
    }

    @Bean
    public XsdSchemaRepository schemaRepository() {
        XsdSchemaRepository schemaRepository = new XsdSchemaRepository();
        schemaRepository.getSchemas().add(todoListSchema());
        return schemaRepository;
    }

    @Bean
    public NamespaceContextBuilder namespaceContextBuilder() {
        NamespaceContextBuilder namespaceContextBuilder = new NamespaceContextBuilder();
        namespaceContextBuilder.setNamespaceMappings(Collections.singletonMap("todo", "http://citrusframework.org/samples/todolist"));
        return namespaceContextBuilder;
    }
```

With this, no custom envelope would be required. Please have a look into our [samples-soap](https://github.com/citrusframework/citrus-samples/tree/master/samples-soap) for more information.

BR,
Sven

**Comment by coding-yogi** [comment]
Thanks Sven, Let me try that out

**Comment by svettwer** [comment]
Hi!

Were you able to solve the issue on your side?

BR,
Sven

**Comment by coding-yogi** [comment]
Yeah, I am kind of OK for now if Envelope is autogenerated. Closing this one
