### ISSUE TITLE
MessageContentBuilder interface broken for buildMessageContent

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#552]
**Citrus Version**
    >= 2.7.3

**Description**
If you upgrade your Citrus version to 2.7.3 or higher, we've a breaking change in the `MessageContentBuilder` Interface affecting all implementing classes. We'll correct this with one of the future releases to ensure effortless version upgrades

**API before change**
```java
    /**
     * Builds the control message. 
     * @param context the current test context.
     * @param messageType the message type to build.
     * @return the constructed message object.
     */
    Message buildMessageContent(TestContext context, String messageType);
```

**API after change**
```java
 /**
     * Builds the control message. 
     * @param context the current test context.
     * @param messageType the message type to build.
     * @param direction
     * @return the constructed message object.
     */
    Message buildMessageContent(TestContext context, String messageType, MessageDirection direction);
```

**Additional information**
We'd have to extend the interface by the older version, mark it as deprecated and ensure that all implementing classes implement the interface correctly

Issue: #310
Commit: https://github.com/citrusframework/citrus/commit/51e9fa326e0947dcbb46eb9de3dd3790073c4c2c#diff-89200ee0f0faf01c7071b52f73d6f7b5R71

BR,
Sven

**Comment by christophd** [comment]
Introducing the (deprecated) method to this interface will introduce another breaking change for users on v2.7.3 as they need then to implement the deprecated method when upgrading to v2.7.9, too.

**Comment by svettwer** [comment]
Hi!

Nope, this could be implemented without a breaking change by adding a default implementation for the interface to prevent the enforcement of implementing the method. 

The implementation could follow the implementation of the `AbstractMessageContentBuilder` like:

```java
    default Message buildMessageContent(TestContext context, String messageType){
        return buildMessageContent(context, messageType, MessageDirection.UNBOUND);
    }
```

**Comment by christophd** [comment]
👍
