### ISSUE TITLE
WaitBuilder.condition() changed return type

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#555]
**Citrus Version**
    >= 2.7.7

**Description**
If you upgrade your Citrus version to 2.7.7 or higher, we've a breaking change on the `WaitBuilder.condition` method which is affecting the return type of the method. 
From my perspective, this is not fixable without introducing another breaking change.

**API before change**
```java
/**
     * Condition to wait for during execution.
     * @param condition
     * @return
     */
    public WaitConditionBuilder condition(Condition condition)
```

**API after change**
```java
/**
     * Condition to wait for during execution.
     * @param condition
     * @return
     */
    public Wait condition(Condition condition) 
```

**Additional information**

Issue: #417
Commit: https://github.com/citrusframework/citrus/commit/515e840f9133383d19304916db197ce5fdb9ac83#diff-fc38b7c87355bad09a45d5e7589fd83eR47

BR,
Sven

**Comment by christophd** [comment]
> From my perspective, this is not fixable without introducing another breaking change.

True! Introducing a deprecated version of the same method with another return type is not possible in Java. In addition to that I do not think that any user is actually worried about the change that initially has been introduced.

**Comment by svettwer** [comment]
Reviewed and agreed!
