### ISSUE TITLE
Add support for initialisation of http client like restassured

### ISSUE THREAD

**Issue by adhithyasrinivasan** [citrusframework/citrus#577]
Please add support for client initialisation like restassured so that we can integrate with our framework

**Comment by svettwer** [comment]
Hi!

What do you mean with *initialisation* here?
Do you mean the given-when-then syntax like: `given().when().get("http://www.google.com").then().statusCode(200);`
or do you mean the client configuration like:
```java
RestAssured.config = RestAssured.config().httpClient(httpClientConfig().httpClientFactory(
         new HttpClientConfig.HttpClientFactory() {

            @Override
            public HttpClient createHttpClient() {
                return new SystemDefaultHttpClient();
            }
        }));
```
?

**If you mean the given-when-then syntax:**
Citrus comes with a rich Java-DSL and we're not planning to add a *given-when-then* variant currently. To be honest, a *given-when-then* syntax would reduce the flexibility of the frameworks as well as the exactness concerning message protocol validation.

**Concerning the configuration:**
It's easily possible to create Citrus endpoints with the `CitrusEndpoints` Builder like
```java
@Configuration
public class EndpointConfig {

    @Bean
    public HttpClient todoClient() {
        return CitrusEndpoints.http()
                            .client()
                            .requestUrl("http://localhost:8080")
                            .build();
    }
}
```

I hope I got your question right.

BR,
Sven

**Comment by svettwer** [comment]
Closed due to inactivity.
