### ISSUE TITLE
How to add queryparams to HTTP/s Requests when using TestNGCitrusTestRunner

### ISSUE THREAD

**Issue by lebuitrago** [citrusframework/citrus#586]
**Citrus Version**
2.7.7

**Question**
Using TestNGCitrusTestRunner, how can I add queryparams to a Request prior to executing the 'send()' command? For example, I want to append something like the following to my RESTful service call url:

`?color=blue`

**What I've tried so far**
From the Citrus Guide, I see that this is possible using TestNGCitrusTestDesigner, however, I do not see the functionality available for the TestNGCitrusTestRunner.

**Additional information**
Is there a way you would recommend to go about doing this? Is there a Citrus pattern out there that people are using to get this resolved?

Thank you.

**Comment by svettwer** [comment]
Hi!

Here is a sample:
```java
public class QueryParameterIT extends TestNGCitrusTestRunner {

    @Autowired
    private HttpClient httpClient;

    @Test
    @CitrusTest
    public void showQueryParameter() {
        http(http -> http
                .client(httpClient)
                .send()
                .get("/colorService")
                .queryParam("color","blue"));

    }

}
```

The Syntax with the Runner is slightly different. I hope that helps you out.

BR,
Sven

**Comment by lebuitrago** [comment]
Sven,

Perfect, got it working now.

Thank you very much.
