### ISSUE TITLE
Deprecate Citrus XML Tests

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#608]
In order to improve the maintainability of the framework and reduce the complexity from a user’s perspective, we are going to deprecate the XML-DSL.

**Comment by elvinsp** [comment]
Hi Sven,

I'm using XML-DSL, because it allows me to have separate files for separate tests.
Because I'm not an Java Expert: Is it possible to do that with Java-DSL? From Documentation it looks like I have to put everything into the test class.

BR
Elvin

**Comment by mlybarger** [comment]
i'm sad to hear the depreciation.  our team has swarms of xml test and love using the simplicity of writing tests using xml as oppose to java.  it seems a better dsl for writing integration tests... must my 0.02$

**Comment by christophd** [comment]
We can certainly open a discussion on that. I hear many voices that still have XML as the way to go.

@svettwer what are the plans here? would the de-deprecation be an option for you?

**Comment by svettwer** [comment]
Hiho :wave: 
The decision to deprecate the XML-DSL was made under totally different conditions as we have today. Back then, the Idea was to reduce maintenance effort and simplify the release process. If you (@christophd) want to keep it alive, feel free. :+1:

**Comment by christophd** [comment]
thanks Sven, so if it is my call I would keep it.
