### ISSUE TITLE
org.xml.sax.SAXParseException if xmldsig is used in xsd

### ISSUE THREAD

**Issue by tamer-erdogan** [citrusframework/citrus#620]
**Citrus Version**
2.8.0

**Question**
I have the following xsd:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.test.com/test"
		   xmlns:xs="http://www.w3.org/2001/XMLSchema"
		   xmlns:dsig="http://www.w3.org/2000/09/xmldsig#"
		   targetNamespace="http://www.test.com/test"
		   elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#"
			   schemaLocation="http://www.w3.org/TR/2002/REC-xmldsig-core-20020212/xmldsig-core-schema.xsd"/>

	<xs:element name="Invoice" type="EncryptedType"/>
	<xs:complexType abstract="true" mixed="false" name="EncryptedType">
		<xs:sequence>
			<xs:element ref="dsig:KeyInfo" minOccurs="0" />
			<xs:element ref="dsig:Signature" minOccurs="0"/>
		</xs:sequence>
		<xs:attribute name="Id" type="xs:ID"/>
		<xs:attribute name="Type" type="xs:anyURI" use="optional"/>
		<xs:attribute name="MimeType" type="xs:string" use="optional"/>
		<xs:attribute name="Encoding" type="xs:anyURI" use="optional"/>
	</xs:complexType>
</xs:schema>
```

Wenn ich im citrus-context.xml in schemas eintrage und die tests starte bekomme ich folgende Fehler:
`Caused by: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 50; src-resolve: Cannot resolve the name 'dsig:KeyInfo' to a(n) 'element declaration' component.`

**What I've tried so far**
I have also downloaded the xmldsig-core-schema.xsd and imported as follows:
`<xs:import namespace="http://www.w3.org/2000/09/xmldsig#"  schemaLocation="xmldsig-core-schema.xsd"/>`
But didn't help.

**Additional information**
I have validated the xsd here and it is valid: http://www.utilities-online.info/xsdvalidation/?save=bcf85318-7f83-482f-b002-aca8914618a2-xsdvalidation#.XGLnMoUxlhF
Any help is really appreciated.

**Comment by svettwer** [comment]
Hi!

I've added the provided schema to a sample project but was unable to reconstruct the issue. 
Would it be possible for you to provide a sample test case where the issue occurs and maybe some information about your context setup?

BR,
Sven

**Comment by tamer-erdogan** [comment]
Hi,
Here are my steps:

- I created with mvn the sample project.
`mvn archetype:generate -Dfilter=com.consol.citrus.archetypes:citrus`
- Choose archetype: 3
com.consol.citrus.archetypes:citrus-quickstart-soap (Citrus quickstart project with SOAP client and server)
- Choose com.consol.citrus.archetypes:citrus-quickstart-soap version: 5
Version: 2.7.8
- groupId: com.consol.citrus.test
- artifactId: invoice

I run mvn install, then I got some errors. Then I changed the version to 2.8.0, then again mvn install: BUILD SUCCESS.
Now I edited the citrus-context.xml and added the test.xsd to schema repository, and again mvn install, then I get the following error:
`Caused by: org.xml.sax.SAXParseException; lineNumber: 7; columnNumber: 50; src-resolve: Cannot resolve the name 'dsig:KeyInfo' to a(n) 'element declaration' component.`

Here is my citrus-context.xml
` 
  <context:property-placeholder location="classpath:citrus.properties"/>

  <citrus:schema-repository id="schemaRepository">
    <citrus:schemas>
      <citrus:schema id="helloServiceWsdl" location="classpath:schemas/HelloService.wsdl" />
      <citrus:schema id="test.xsd" location="classpath:schemas/test.xsd" />
    </citrus:schemas>
  </citrus:schema-repository>

  <citrus:global-variables>
    <citrus:variable name="project.name" value="Citrus Integration Tests"/>
  </citrus:global-variables>

  
  <citrus:namespace-context>
    <citrus:namespace prefix="hello" uri="http://citrusframework.org/schemas/samples/HelloService"/>
  </citrus:namespace-context>

  <bean id="messageFactory" class="org.springframework.ws.soap.saaj.SaajSoapMessageFactory"/>

  
  <citrus-ws:client id="helloSoapClient"
                    request-url="${hello.service.url}"
                    timeout="1000"/>

  
  <citrus-ws:server id="helloSoapServer"
          port="${server.port}"
          auto-start="true"
          timeout="10000"
          endpoint-adapter="staticResponseAdapter"/>

  
  <citrus:static-response-adapter id="staticResponseAdapter">
    <citrus:payload>
      <![CDATA[
      <hello:HelloResponse xmlns:hello="http://citrusframework.org/schemas/samples/HelloService">
        <hello:Message>Hello User!</hello:Message>
      </hello:HelloResponse>
      ]]>
    </citrus:payload>
    <citrus:header>
      <citrus:element name="citrus_soap_action" value="HelloService/sayHello"/>
    </citrus:header>
  </citrus:static-response-adapter>
</beans>`

**Comment by svettwer** [comment]
Hi!

Thx for the detailed explanation. :+1: 
I did it the way you described but was unable to reconstruct the issue. On my side, the setup runs fine. The only reason I can imagine is, that it was not possible for Citrus to access the schema on the schema-location. But as you said, that you downloaded the schema and provided it as a local reference, this shouldn't be the root cause. Nevertheless, if the issue still exist, I'm afraid it is a local one. :disappointed: 

BR,
Sven

**Comment by svettwer** [comment]
Closed due to inactivity.
