### ISSUE TITLE
Citrus Kafka Consumer with schema registry

### ISSUE THREAD

**Issue by nagendratest** [citrusframework/citrus#623]
Hi Team,

I am trying to consume kafka message with schema id to validate the message. Could any one let me know how it can be done.

Kafka :0.11
Avro :1.8.2
Confluent Schema Registry :3.3

Regards,
Nagendra.

**Comment by nagendratest** [comment]
Hi Team,

Can any one assist me on this issue.


Regards,
Nagendra.

**Comment by svettwer** [comment]
Hi!

We are currently short on time. That leads to increased reaction times. Sorry for that. 

@s1hofmann You already had a project with Kafka and Avro right? :thinking:

BR,
Sven

**Comment by s1hofmann** [comment]
Hi @nagendratest,

I've only been working with Kafka producers, but this shouldn't be a problem regarding the schema registry.
Communication with Confluent schema registries is done via REST, so it's no problem to mock these calls using Citrus.

We just have to add a HTTP server endpoint:

```
@Configuration
public class EndpointConfig {
...
    @Bean
    public HttpServer schemaRegistry() {
        return CitrusEndpoints.http()
                .server()
                .port(9093)
                .autoStart(true)
                .build();
    }
...
}
```

And are able to mock communication with e.g. a Confluent SchemaRegistryClient:
(This little snippet roughly demonstrates a client which first queries the latest schema meta data from a registry and then queries a specific schema via its id)
```
@ExtendWith(CitrusExtension.class)
public class SchemaRegistryIT {

    // Other endpoints
    ...
    @CitrusEndpoint
    private HttpServer schemaRegistry;

    @Test
    @CitrusTest
    public void schemaRegistryMockTest(@CitrusResource final TestRunner runner) {
        // Other requests / responses
        ...

        runner.http(http -> http.server(schemaRegistry)
                .receive()
                .get("/subjects/${your-schema-name}/versions/latest")
                .contentType("application/vnd.schemaregistry.v1+json")
                .messageType(MessageType.JSON));

        runner.http(http -> http.server(schemaRegistry)
                .respond(HttpStatus.OK)
                .contentType("application/vnd.schemaregistry.v1+json")
                .messageType(MessageType.JSON)
                .payload(${your-schema-meta-data}));

        runner.http(http -> http.server(schemaRegistry)
                .receive()
                .get("/schemas/ids/${your-schema-id}")
                .contentType("application/vnd.schemaregistry.v1+json")
                .messageType(MessageType.JSON));

        runner.http(http -> http.server(schemaRegistry)
                .respond(HttpStatus.OK)
                .contentType("application/vnd.schemaregistry.v1+json")
                .messageType(MessageType.JSON)
                .payload(${your-schema-data}));
        
        /// Other requests / responses
        ...
    }
}
```

This little sample should get you started. For questions regarding payloads I can highly reccomend the Confluent docs, which also hold a [Schema Registry API Reference](https://docs.confluent.io/current/schema-registry/docs/api.html).

**Comment by svettwer** [comment]
Thx @s1hofmann for the explanation. I assume the question has been answered @nagendratest?

**Comment by nagendratest** [comment]
Hi  Team,

Thanks alot for your assistance.

Regards,
Nagendra.
