### ISSUE TITLE
Citrus with Selenide framework

### ISSUE THREAD

**Issue by RaymondMouthaan** [citrusframework/citrus#630]
**Question**
Is there anyway / possibility to integrate [selenide.org](https://selenide.org) / [Selenide Framework](https://github.com/selenide/selenide) with Citrus framework to handle web gui testing instead of Selenium?

**Comment by svettwer** [comment]
Hiho!

Without any detailed research: Yes, this should be possible.

Why do you want to use Selenide instead of selenium? Is there any functional or non functional requirement?

BR,
Sven

**Comment by RaymondMouthaan** [comment]
@svettwer, can I PM you somehow? 😀

**Comment by svettwer** [comment]
Hi, sure!

Mail: sven.hettwer@consol.de 
Twitter: twitter.com/@SvenHettwer

BR,
Sven

**Comment by RaymondMouthaan** [comment]
Hopefully Selenide will be integrated into Citrus some day 💪🏼. For now I'll close this issue.
