### ISSUE TITLE
Example: how to configure Citrus JdbcDriver in tested application?

### ISSUE THREAD

**Issue by stallewar** [citrusframework/citrus#631]
**Citrus Version**
2.8.0

**Question**
Hi! could you please provide some example how to configure Citrus JdbcDriver for tested application. It seems not enough, just add maven dependency in pom.xml, and change connection configuration parameters and credentials.

**What I've tried so far**
I've tried this way for oracle db (thin driver) , but no luck. 

**Additional information**
https://github.com/citrusframework/citrus/issues/532

**Comment by svettwer** [comment]
Hi!

>It seems not enough, just add maven dependency in pom.xml, and change connection configuration parameters and credentials.

Well, this should do it for you. 
Have you added the driver dependency as well?
```xml
<dependency>
  <groupId>com.consol.citrus</groupId>
  <artifactId>citrus-db-driver</artifactId>
  <version>${citrus.db.version}</version>
</dependency>
``` 

A sample configuration can be found in the [sample-jdbc](https://github.com/citrusframework/citrus-samples/tree/master/samples-db/sample-jdbc) project of the citrus-samples repository. Another example using environment parameters, can be found in this [smartwatch mapping](https://github.com/svettwer/smartwatch-mapping-service) sample project. 
At the end, I can't give you a detailed instruction how you would have to configure your software concerning the database driver, because I don't know the configuration capabilities of your software.

I hope the samples help you out. =)

BR,
Sven

**Comment by RaymondMouthaan** [comment]
I've tried to connect to oracle db as well and didn't succeed with only citrus-db-driver dependency. I had to add the oracle driver dependency too. Unfortunately Oracle doesn't publish this driver to Maven repos for some reason...

**Comment by svettwer** [comment]
Hi @RaymondMouthaan,

>I've tried to connect to oracle db as well and didn't succeed with only citrus-db-driver dependency.

That can not work either, because the citrus-db-driver is only able to connect to the corresponding citrus-db-server. It's not possible to substitute the Oracle DB driver with a Citrus db driver and establish a connection to an Oracle Database.

It's possible to configure a citrus-jdbc-server like:
```java
@Bean
public JdbcServer jdbcServer() {
    return CitrusEndpoints.jdbc()
            .server()
            .host("localhost")
            .databaseName("testdb")
            .port(13306)
            .timeout(10000L)
            .autoStart(true)
            .build();
}
```

and connect to it via the driver like:

```java
@Bean
public SingleConnectionDataSource dataSource() {
    SingleConnectionDataSource dataSource = new SingleConnectionDataSource();
    dataSource.setDriverClassName(JdbcDriver.class.getName());
    dataSource.setUrl("jdbc:citrus:http://localhost:13306/testdb");
    dataSource.setUsername("sa");
    dataSource.setPassword("");
    return dataSource;
}
```

BR,
Sven

**Comment by RaymondMouthaan** [comment]
Hi Sven, I'll try what you suggest. Would even be better, since there is no need for the oracle driver. 👍🏽

**Comment by RaymondMouthaan** [comment]
@svettwer, i've tried as you suggested.

```
@Bean
    public SingleConnectionDataSource dataSource() {
        SingleConnectionDataSource dataSource = new SingleConnectionDataSource();
        dataSource.setDriverClassName(JdbcDriver.class.getName());
        dataSource.setUrl("jdbc:citrus:thin:@<servername>:1521/testdb");
        dataSource.setUsername("username");
        dataSource.setPassword("password");
        return dataSource;
    }
```

And ...

```
@Bean
    public SingleConnectionDataSource dataSource() {
        SingleConnectionDataSource dataSource = new SingleConnectionDataSource();
        dataSource.setDriverClassName(JdbcDriver.class.getName());
        dataSource.setUrl("jdbc:citrus:http://<servername>:1521/testdb");
        dataSource.setUsername("username");
        dataSource.setPassword("password");
        return dataSource;
    }
```

Both do not work ..

What does work is the following, but this doesn't use citrus-db-driver.

```
    @Bean
    public SingleConnectionDataSource dataSource() {
        SingleConnectionDataSource dataSource = new SingleConnectionDataSource();
        dataSource.setDriverClassName("oracle.jdbc.driver.OracleDriver");
        dataSource.setUrl("jdbc:oracle:thin:@<servername>:1521/testdb");
        dataSource.setUsername("<username>");
        dataSource.setPassword("<password>");
        return dataSource;
    }
```

Just to make sure we understand each other, i am trying to connect to a remote hosted Oracle database server, not localhost. :)

Any suggestions to make this work? 
Cheers,
Ray

**Comment by svettwer** [comment]
Hi @RaymondMouthaan.

>Just to make sure we understand each other, i am trying to connect to a remote hosted Oracle database server, not localhost.

This is exactly what you can _not_ do with the Citrus JDBC Driver.
The only kind of server, you can connect your application to using the Citrus JDBC Driver, is a Citrus JDBC Server. A connection to any other Kind of Database is not possible at all.

If you want to connect to an existing remote test database, this is a totally different use case. Citrus is able to handle this as well but not using the Citrus JDBC Driver.
The Idea behind creating a dedicated Citrus related JDBC Driver and Server is to get rid of expensive test databases, test data setups, tear downs and stuff like that.

But if you already have a test database and you want to use it in your Citrus test, please use the SQL module of Citrus. Here is [a sample](https://github.com/citrusframework/citrus-samples/tree/master/samples-db/sample-sql) showing how to use Citrus with a real database.

Here is the `DataSource` configuration:
```java
@Bean(destroyMethod = "close")
public BasicDataSource todoListDataSource() {
    BasicDataSource dataSource = new BasicDataSource();
    dataSource.setDriverClassName("org.hsqldb.jdbcDriver");
    dataSource.setUrl("jdbc:hsqldb:hsql://localhost:9099/testdb");
    dataSource.setUsername("sa");
    dataSource.setPassword("");
    dataSource.setInitialSize(1);
    dataSource.setMaxActive(5);
    dataSource.setMaxIdle(2);
    return dataSource;
}
```

In your test case you would select from the configured db as follows:
```java
query(executeSQLQueryBuilder -> executeSQLQueryBuilder
            .dataSource(todoDataSource)
            .statement("select count(*) as cnt from todo_entries where title = '${todoName}'")
            .validate("cnt", "0"));
```

I hope that makes it a little clearer and help you out. =)

BR,
Sven

**Comment by RaymondMouthaan** [comment]
Hi @svettwer, this is perfectly explained! Thank you very much :+1: I have it working now :-)

One other question I have, is it possible to use JUnit4 or JUnit5 instead of TestNG ?

**Comment by svettwer** [comment]
Closed due to inactivity of OP.
