### ISSUE TITLE
How to set null value in variable("houseName", null)

### ISSUE THREAD

**Issue by vmasule** [citrusframework/citrus#632]
I am not able to create a variable with `null` value. 
**Example**

`variable("houseName", application.getHouseName());`

Here `application.getHouseName()` can return null value and I am using this variable in json request file.

Could you please suggest how to achieve that?

I am getting below exception.

`com.consol.citrus.exceptions.VariableNullValueException: Trying to set variable: houseName, but variable value is null`

**Comment by svettwer** [comment]
Hi  @vmasule!

As you stated, there is a check preventing null values to be set as variables. I assume the value you put in the json file would be `null` right?

I would suggest to create a little helper method like:
```java
private Object getValue(Object theObject) {
    return Objects.isNull(theObject) ? "null": theObject;
}
```
This should help you out in your use case.

One could also think about allowing null values for variables, but I doubt that this would be possible without breaking something.

BR,
Sven

**Comment by christophd** [comment]
How about 

`variable("houseName", Optional.ofNullable(application.getHouseName()).orElse("null"));`

**Comment by christophd** [comment]
this could also be done by Citrus I guess so that null values are automatically "translated" to "null" String.

**Comment by svettwer** [comment]
Closed due to inactivity

**Comment by awgtek** [comment]
I'm using the Given variables Gherkin to set an empty string:
```
    Given variables
      | resourceId                | |
```
But I get: com.consol.citrus.exceptions.VariableNullValueException: **Trying to set variable: resourceId, but variable value is null**
Is it possible to set an empty string this way somehow?
