### ISSUE TITLE
When executing citrus test case getting exception  as "CitrusRuntimeException: Failed to get correlation key"

### ISSUE THREAD

**Issue by rahul-mali-mpf** [citrusframework/citrus#635]
**Citrus Version**
2.8.0

**Question**
Getting error "Failed to get correlation key" when executing the Citrus HTTP test case.

**What I've tried so far**
Tried changing the "citrus-http:client" ID in citrus-context.xml file.

**Additional information**
I am trying to execute the HTTP test case using "TestNGCitrusTestDesigner" . However unable to do it.
Code snippet:
```java
    @Test
    @CitrusTest
     public void testResponse(){

        http().client(todoClient)
                .receive().response(HttpStatus.OK);
     }
```

**Comment by svettwer** [comment]
Hi @rahul-mali-mpf,

The snippet you have posted is not a complete HTTP Client communication. Even if HTTP is a synchronous protocol, the send and receive actions are separated to ensure the order of messages when other transports are involved.

Lets say, you send an HTTP request and you want to make sure that a JMS message leaves the system before the HTTP requests gets its response.

Therefore, you would have to specify a send action as well.
```java
@Test
@CitrusTest
public void testGet() {
    http(httpActionBuilder -> httpActionBuilder
        .client(todoClient)
        .send()
        .get("/todolist"));

    http(httpActionBuilder -> httpActionBuilder
        .client(todoClient)
        .receive()
        .response(HttpStatus.OK));
}
``` 

Please have a look at our [samples repository](https://github.com/citrusframework/citrus-samples) for some HTTP samples.

BR,
Sven

**Comment by svettwer** [comment]
closed due to inactivity
