### ISSUE TITLE
MessageTracingTestListener changed output from citrus v2.7.5

### ISSUE THREAD

**Issue by martku** [citrusframework/citrus#644]
**Citrus Version**
since v2.7.5

**Expected behavior**
Using an extended MessageTracingTestListener the method onOutboundMessage should have the headers and the body of the message.

**Actual behavior**
The message of onOutboundMessage contains only the headers, no body.
E.g. it shows a `Content-Length: 65` but no content following.

**Additional information**
Using Citrus v2.7.4 it works as expected without any other changes.

**Test case sample**
To test simply send a http response from Citrus and take a look in the log.

**Comment by svettwer** [comment]
Seems to relate to #359
