### ISSUE TITLE
Question about error Failed to get correlation key for

### ISSUE THREAD

**Issue by mmarciniuk** [citrusframework/citrus#647]
**Citrus Version**
2.8.0

**Question**
When I separated send action and receive an action to different methods, I got error
_com.consol.citrus.exceptions.TestCaseFailedException: Failed to get correlation key for 'citrus_message_correlator_petStore'_
Example:

```
@Autowired
	@Qualifier("petStore")
	private HttpClient httpClient;

@CitrusTest
@Test
public void sendStep1() {
	http(h -> h.client(httpClient)
			.send()
			.get("/pet/findByStatus?status=available")
			.contentType("application/json")
			.accept("application/json")
			.build());
}

@CitrusTest
@Test(dependsOnMethods = "sendStep1")
public void receiveStep2() {
	http(h -> h.client(httpClient)
			.receive()
			.response()
			.status(HttpStatus.OK));
}
```

As I understand every test with annotation @CitrusTest has its own test context with message storage/or reset test context with message storage before every test? Therefore I can't refer from the second step to message send in the first step.

But what if I would like to consider a class as a test case and method with annotation @Test and @CitrusTest as a step?

Can I somehow transfer test context to the next test? Or maybe there is some way to stop creating new test contexts and use the same for all executions of tests from the same class?

**What I've tried so far**

**Additional information**

**Comment by svettwer** [comment]
Hi!

It seems your question is somehow relates to https://github.com/citrusframework/citrus/issues/635.

>Therefore I can't refer from the second step to message send in the first step.

Correct!

>But what if I would like to consider a class as a test case and method with annotation @test and @citrustest as a step?

Well, this is not how the framework is designed. In addition, it would not make much sense as you can not guarantee the execution order in parallel test execution as long as you do not fix the execution by annotation or features of the underlying test runner. So to use such a setup you would have to fix the execution order. That would come with a lot of boilerplate and a most likely error prone setup.

>Can I somehow transfer test context to the next test?

No

>Or maybe there is some way to stop creating new test contexts and use the same for all executions of tests from the same class?

No

---------------

So my question would be, why would you like to separate test steps into dedicated methods? Is there any technical or business requirement that makes it impossible to structure the test steps in a single method?

BR,
Sven

**Comment by tvelkoff** [comment]
Hopefully this comment will be helpful... The JUnit 5 framework supports stateful testing. I have not used this capability myself but am familiar with it from the documentation.

**Comment by svettwer** [comment]
> Hopefully this comment will be helpful... The JUnit 5 framework supports stateful testing. I have not used this capability myself but am familiar with it from the documentation.

Could you provide a link to this feature? =)

**Comment by tvelkoff** [comment]
Sure thing! Here is the link from the JUnit 5 documentation:
https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested

Also, I came across a rather detailed example here:
https://blog.codecentric.de/en/2018/09/structured-junit-5-testing/

**Comment by svettwer** [comment]
Ah, okay. Nested testing is an option to keep some state, that is true. It is also handy when you have to test several aspects of your code. With this feature, it is easily possible to bundle test that have a certain correlation to each other or a certain topic.

Nevertheless, I would not recommend to store/pass the test context from one test to another. The test context creation is a complex process with a lot of logic involved. Therefore storing the test context and passing it to different test steps might work for the desired use case but could potentially break something else.

BR,
Sven

**Comment by mmarciniuk** [comment]
Ok, thank you for explanation and advice.

**Comment by svettwer** [comment]
I will close the issue as i assume, this is solved for you. =)

BR,
Sven
