### ISSUE TITLE
Unable to compile and install Citrus sample

### ISSUE THREAD

**Issue by chaitra1604** [citrusframework/citrus#652]
**Citrus Version**
2.8.0

**Question**
Using Apache Maven 3.6.1
New to maven and citrus
While trying to install below error is seen

[ERROR]     Non-resolvable import POM: Could not transfer artifact org.jboss.arquillian:arquillian-bom:pom:2.9.0-SNAPSHOT from/to consol-labs-snapshots 
[ERROR]   The project com.consol.citrus.samples:citrus-sample-todo:2.8.0 (/home_local/InteTesting/citrus-samples/todo-app/pom.xml) has 11 errors
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:2.1.4.RELEASE from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 

below POM files dont exists

 http://labs.consol.de/maven/snapshots-repository/org/jboss/arquillian/arquillian-bom/2.9.0-SNAPSHOT/arquillian-bom-2.9.0-SNAPSHOT.pom

 https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.4.RELEASE/spring-boot-dependencies-2.1.4.RELEASE.pom

**What I've tried so far**
Changing the version of arquillian and spring

**Additional information**

**Comment by svettwer** [comment]
Hi!

I'm a little confused currently. Have you cloned the samples repository fresh from github without changes and tried to execute the samples in the master branch without changes using ` mvn clean install -Dembedded`?

The reason I'm asking is, because there is no `arquillian:2.9.0-SNAPSHOT` dependency in the project.

BR,
Sven

**Comment by chaitra1604** [comment]
@svettwer  Yes I have cloned code from below link and tried running 
https://github.com/citrusframework/citrus-samples

No changes done.

**Comment by svettwer** [comment]
Hi!

I've checked the file you mentioned. In [demo/sample-javaee/java-dsl/pom.xml](https://github.com/citrusframework/citrus-samples/blob/master/demo/sample-javaee/java-dsl/pom.xml#L20), `1.1.15.Final` is used.

I'd recommend to delete your local copy of the samples and try a new checkout. 

BR,
Sven

**Comment by chaitra1604** [comment]
With new checkout as well same error is seen
![image](https://user-images.githubusercontent.com/50445251/57523409-85b86200-7342-11e9-96fe-24cf3b3b8b73.png)


Downloading from central: https://repo.maven.apache.org/maven2/org/jboss/arquillian/arquillian-bom/1.1.15.Final/arquillian-bom-1.1.15.Final.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-dependencies/2.1.4.RELEASE/spring-boot-dependencies-2.1.4.RELEASE.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not transfer artifact org.jboss.arquillian:arquillian-bom:pom:1.1.15.Final from/to consol-labs-snapshots (http://labs.consol.de/maven/snapshots-repository/): Connect to labs.consol.de:80 [labs.consol.de/94.185.89.33] failed: Connection timed out (Connection timed out) @ line 118, column 19
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead. @
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead. @
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead. @
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead. @
[ERROR] Non-resolvable import POM: Could not transfer artifact org.springframework.boot:spring-boot-dependencies:pom:2.1.4.RELEASE from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection timed out (Connection timed out) @ line 170, column 19


Actually below link gives 404 error
 http://labs.consol.de/maven/snapshots-repository/org/jboss/arquillian/arquillian-bom/1.1.15.Final/arquillian-bom-1.1.15.Final.pom
![image](https://user-images.githubusercontent.com/50445251/57523738-6cfc7c00-7343-11e9-9caa-bc4de89ec19f.png)

**Comment by svettwer** [comment]
Hi!

This is strange... maven should download arquillian from maven central and not from the consol repository. Maven usually tries to download from other repos when maven central is not available.
Are you behind a proxy or some other setup restricting your internet access?

BR,
Sven

**Comment by christophd** [comment]
In the error stack trace I read something like
```
Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.120.215] failed: Connection timed out (Connection timed out)
```
So there is definitely an issue with connectivity to maven central. And this needs to be fixed

**Comment by chaitra1604** [comment]
Thanks, was able to run correctly after updating proxy correctly. 
@svettwer  : Now while running "mvn jetty:run-war"
Getting below error Bakery Example

[INFO] --- activemq-maven-plugin:5.15.2:stop (stop-activemq) @ citrus-java-bakery-web ---
[INFO] Apache ActiveMQ 5.15.2 (localhost, ID:ddeVM-43985-1557837589507-0:1) is shutting down
[INFO] socketQueue interrupted - stopping
[INFO] Could not accept connection during shutdown  : {}
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait (AbstractQueuedSynchronizer.java:2014)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos (AbstractQueuedSynchronizer.java:2088)
    at java.util.concurrent.LinkedBlockingQueue.poll (LinkedBlockingQueue.java:467)
    at org.apache.activemq.transport.tcp.TcpTransportServer$1.run (TcpTransportServer.java:479)
    at java.lang.Thread.run (Thread.java:748)
18:10:11,509 WARN  er.FailoverTransport| Transport (tcp://localhost:61616) failed , attempting to automatically reconnect: {}
java.io.EOFException
        at java.io.DataInputStream.readInt(DataInputStream.java:392)
        at org.apache.activemq.openwire.OpenWireFormat.unmarshal(OpenWireFormat.java:268)
        at org.apache.activemq.transport.tcp.TcpTransport.readCommand(TcpTransport.java:240)
        at org.apache.activemq.transport.tcp.TcpTransport.doRun(TcpTransport.java:232)
        at org.apache.activemq.transport.tcp.TcpTransport.run(TcpTransport.java:215)
        at java.lang.Thread.run(Thread.java:748)

**Comment by chaitra1604** [comment]
@svettwer Any Update

**Comment by svettwer** [comment]
I am currently working on a customers project. I will have a look as soon as possible.

**Comment by svettwer** [comment]
Hi @chaitra1604,

`mvn jetty:run-war` is not supported as a standalone command as the system has some infrastructure dependencies to be met. Please have a look at the [README](https://github.com/citrusframework/citrus-samples/blob/master/demo/sample-bakery/java-dsl/README.md) of the bakery sample for more information and instructions for execution.

BR,
Sven

**Comment by svettwer** [comment]
Closed due to inactivity.
