### ISSUE TITLE
Http2 Client and server

### ISSUE THREAD

**Issue by chaitra1604** [citrusframework/citrus#653]
**Citrus Version**
2.8.0

**Question**
Is Http2 Client and server support available now. Or possible to extend and modify to support the same

**What I've tried so far**

**Additional information**

**Comment by svettwer** [comment]
Hi!

_Relates to #144_

Citrus does not support HTTP/2 currently but it would absolutely be possible to extend the framework to work with HTTP/2. Nevertheless, this feature has no priority actually as we have no customer project using HTTP/2 nor have we an order for this feature.

Nevertheless, we always appreciate pull requests from the community, so if you are interested in supporting and extending the framework, have a look at our [contribution guidelines](https://github.com/citrusframework/citrus/blob/master/CONTRIBUTING.md)

BR,
Sven

**Comment by svettwer** [comment]
Closed due to inactivity.
In addition, I assume the question has been answered.
