### ISSUE TITLE
How to inject Citrus TestContext into Cucumber step definition files

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#657]
Extracted from #539
---------------------
**Citrus Version**

**Question**
Hello, I have a question, not sure if this is the correct place to add questions, so maybe you can redirect me.

When doing a get on an HTTP endpoint I'm receiving a list of objects, which in JSON format.
I need to call a next HTTP endpoint for each object. The list of objects is being saved in a citrus variable.

I'm using the Runner (not Designer) to interact with the endpoints. I need to be able to access the TestContext to extract the Citrus variable and convert it into a Java Object. 

As explained here I'm supposed to use the **CitrusResource** to inject the **TestContext** but it is always **null**.
https://stackoverflow.com/questions/49659177/turn-citrus-variable-into-java-variable

**What I've tried so far**
```java
public class StepDefs {

    @CitrusResource
    protected TestRunner runner;

    @CitrusResource
    private TestContext context;

    @Given("Hello world")
    public void helloWorld() {
        runner.traceVariables();
        context.getVariable("myVariable");
    }
}

```

I can see the variable when doing the traceVariables() on the runner but I'm unable to extract it to java. 
This is a Step Definition class for Cucumber.

Humphrey

**Comment by hmmlopez** [comment]
Extra info, the runner is being injected and working fine but the TextContext is null.
This already with Cucumber 3.x and Citrus 2.8.0.

**Comment by hmmlopez** [comment]
It would be nice if someone could answer this question.

**Comment by MPleas** [comment]
FYI..... For anyone waiting on this, I posted a workaround to my StackOverflow article at https://stackoverflow.com/questions/60539128/citrus-framework-how-to-make-a-soap-response-citrus-variable-citrus-functio.
