### ISSUE TITLE
Update jackson-databind to version 2.9.9 or later

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#658]
Due to security implications, we should update `com.fasterxml.jackson.core:jackson-databind` to version 2.9.9 or later.

- root pom.xml
- tools/remote/pom.xml

**Comment by akuz0** [comment]
@svettwer Hello! I want try change it, but can`t find com.fasterxml.jackson.core:jackson-databind in tools/remote/pom.xml
This issue is actual?

**Comment by bbortt** [comment]
hi @akuz0, I think this issue is stale by now. the version in use is: https://github.com/citrusframework/citrus/blob/9e658d2f24f7324c3e822ab37405389bf4a7454d/pom.xml#L170.
