### ISSUE TITLE
Can't build citrus

### ISSUE THREAD

**Issue by chokdee** [citrusframework/citrus#659]
**Citrus Version**
2.9.0-SNAPSHOT

**Expected behavior**
Build is running

**Actual behavior**
Get an exception running mvn install with skipping the tests

**Test case sample**

checkout a fresh copy , disable the tests in the pom and run mvn install

You will get the error:

[ERROR] file:/C:/ws/citrus.git-chokdee/modules/citrus-model/model-ws/src/main/resources/com/consol/citrus/schema/citrus-ws-testcase.xsd [45,54] 
org.xml.sax.SAXParseException; systemId: file:/C:/ws/citrus.git-chokdee/modules/citrus-model/model-ws/src/main/resources/com/consol/citrus/schema/citrus-ws-testcase.xsd; lineNumber: 45; columnNumber: 54; src-resolve: Name 'core:TestActionType' kann nicht als 'type definition'-Komponente aufgelöst werden.

**Comment by svettwer** [comment]
Hi!

As Citrus is built with Travis automatically, such an error would occur during the automated build. I assume that this is a local issue. Nevertheless, I will briefly have a look.

BR,
Sven

**Comment by chokdee** [comment]
I think the problem is that there is a reference to an external xsd

Schemadokument 'http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd' konnte nicht gelesen werden

**Comment by chokdee** [comment]
You are partial right. The issue is that maven (I think xjc) needs a valid internet connection. And we are using a proxy here. So xjc can't load the xsd file. Maybe a good idea to store the xsd local and don't load it from the internet.

**Comment by svettwer** [comment]
In this case, please have a look at the [maven proxy configuration](https://maven.apache.org/settings.html#Proxies) respectively [xjc proxy config](https://docs.oracle.com/javase/10/tools/xjc.htm#JSWOR741).

It is not in the scope of Citrus to make it an offline project or store xsd's from the internet to make an offline build possible.

BR,
Sven

**Comment by chokdee** [comment]
Ok, but still a bad idea to load external entities from the internet.
Here is a good example how to do it.
Maybe a feature for the future
https://dzone.com/articles/jaxb-xjc-imported-schemas-and

**Comment by svettwer** [comment]
Thx for the link. I'll have a look but as the XML DSL is deprecated, it is more likely that it will be removed first.

BR,
Sven
