### ISSUE TITLE
Introduce lenient evaluation of XPath expressions

### ISSUE THREAD

**Issue by tvelkoff** [citrusframework/citrus#664]
# User Story
As an engineer who writes tests of a system, I want
* extraction of values from documents to permit optional elements to be missing without triggering exceptions.
* mismatches between actual and expected values to be handled as failures, not as exceptions

# Background

## Desired outcomes of system tests
I would like for the behavior of system tests to mirror that of unit tests, namely, that there be three possible outcomes: success, failure, and error. Successes and failures are "normal", in that they reveal the behavior of the software as implemented. Errors are exceptional events, and identify issues found not in the software under test, but in the environment in which it executes.

## Motivation - Description of my system
I have a system against which I want to run over two hundred tests on a recurring basis. If exceptions are reserved for problems with the system's environment (e.g. network, errors in the tests themselves), I can use the set of failures to focus attention on issues within the SUT.
My system performs federated search and retrieval from multiple back-end systems, and its inputs and outputs are SOAP XML messages. XPath is a natural technology choice for evaluating the correctness of messages returned by the system in response to given inputs.

# Citrus implementation
## Current behavior
The evaluation of XPath expressions by Citrus does not match the desired model of outcomes described above. In particular, the Citrus framework throws exceptions in two circumstances:
* when extracting values of elements whose presence is optional and sometimes do not appear in the message
* when comparing between expected and actual values and the values do not match

## Proposed behavior
In both of these cases, I would like Citrus to suppress exceptions, by returning an empty string in the first case, and by returning a failure in the second.

# Proposed change to Citrus
I plan to submit a pull request that will facilitate the "lenient" behavior I have described here, even while ensuring that the invariant of the current behavior is preserved for all existing Citrus tests, and for future tests that do not need this feature.

**Comment by svettwer** [comment]
Hi!

Thx for the detailed description. So if I understand you correctly, you talk about elements defined with `minOccurs="0"` in your XSD, so they are optional from a technical and a business perspective.

In this case, I understand your desired change and your motivation with this but I'm currently not sure whether a lenient evaluation behavior would be the way to go.

From a testers perspective: why does an optional field **sometimes** and **sometimes not** appear in a test case with a well defined environment? In this case, it seems that there are some random conditions making the SUT behavior not reproducible. In this case I would recommend to review the test cases and the environment setup during test execution.

Your second point was:
>when comparing between expected and actual values and the values do not match

I think this is nothing one should be able to deactivate. I mean, if there is an assertion on a value, the assertion has been made for a reason and should cause the test to fail.

In addition, I am not sure whether your definition for test results as _success, failure, and error_, where error is reserved on environmental issues is something that should be applied. If we add such a mechanism distinguishing between failures based on the environment or based on implementation issues consistently, this would be a lot of work.

But maybe I do not get you requirement. In this case, would it be possible for you to share an example in code from your user perspective showing the issue?

BR,
Sven

**Comment by svettwer** [comment]
>In this case, would it be possible for you to share an example in code from your user perspective showing the issue?

Maybe just an XSD, a sample message and a shrunk down test case.

**Comment by tvelkoff** [comment]
Thanks for your detailed analysis and response. For now, let me focus on the issue with variable extraction.
The use case deals with metadata in a response message. The response returns a result code (SUCCESS, WARNING, ERROR), and optional elements that contain details only when the code is not SUCCESS. When executing the tests, it is useful to capture this optional information for diagnostic purposes.
Here is a simplified excerpt of the XML Schema:
~~~
<complexType name="ResultType">
  <sequence>
    <element name="ResultCode" type="string"/>
    <element name="ResultCategory" type="string" minOccurs="0"/>
    <element name="ResultText" type="string" minOccurs="0"/>
  </sequence>
</complexType>
~~~
And here are excerpts of messages that conform to the schema:
~~~
<Result>
  <ResultCode>SUCCESS</ResultCode>
</Result>
~~~
~~~
<Result>
  <ResultCode>ERROR</ResultCode>
  <ResultCategory>EXTERNAL_ERROR</ResultCategory>
  <ResultText>Timeout</ResultText>
</Result>
~~~
Here is a simplified example of the TestRunner code. Note that when defining the receive action, it is not known whether the optional elements will be present or not.
~~~
runner.receive(action -> action
  .endpoint(this.endpointConfig.resultQueue())
  .extractor(new XpathPayloadVariableExtractor(true)) // see pull request
  .validator(new XpathMessageValidator(true)) // see pull request
  .selector("JMSCorrelationID='" + this.correlationId + "'")
  .payload("")
  .schemaValidation(true)
  .extractFromPayload("//ResultCode", "resultCode")
  .extractFromPayload("//ResultCategory", "resultCategory") // optional element
  .extractFromPayload("//ResultText", "resultText") // optional element
  .validate(this.resultAssertions)
);
~~~
If Citrus throws an exception when extracting a missing optional element, then the test will fail, even though it should succeed.

**Comment by tvelkoff** [comment]
Now I'll address the second topic, which concerns how the test should execute when a mismatch between expected and actual values occurs during an XPath evaluation. There is no question that this constitutes a test failure. The issue concerns the flow of control of the test when this happens.
In my tests, not only do I want to evaluate XPath assertions, I also want to collect diagnostic information from the message and make this available for later analysis. If Citrus throws an exception, then this information is lost. Therefore, the purpose of the proposed change to Citrus is to preserve the normal flow of control, when that is desired.
Here is the simplified TestRunner code:
~~~
runner.receive(action -> action
    .endpoint(this.endpointConfig.resultQueue())
    .extractor(new XpathPayloadVariableExtractor(true)) // see pull request
    .validator(new XpathMessageValidator(true)) // see pull request
    .selector("JMSCorrelationID='" + this.correlationId + "'")
    .payload("")
    .schemaValidation(true)
    .extractFromPayload("//ResultCorrelationId", "resultCorrelationId")
    .extractFromPayload("//NumberItemsReturned", "numberItemsReturned")
    .extractFromPayload("//ResultCode", "resultCode")
    .extractFromPayload("//ResultCategory", "resultCategory") // optional
    .extractFromPayload("//ResultText", "resultText") // optional
    .validate(this.resultAssertions) // Map of XPath expressions to expected results
);
~~~
Here is an example of diagnostic information when the flow of control is preserved:
~~~
Started : 2019-06-15T12:04:32.579
----------------------------------------------------------------
Foo_Bar_IT.retrieve
Response Code: ACCEPTED
Response Correlation Id: DEV16B567A25BBQ000000512
Result Code  : SUCCESS
Result Correlation Ids : DEV16B567A25BBQ000000512
NumberItemsReturned: 0
//NumberItemsReturned : expected = 1, actual = 0
Status: FAILED
Duration: 00:00:01.969
----------------------------------------------------------------
Finished: 2019-06-15T12:04:35.386
Duration: 00:00:02.807
~~~
Here is an example of diagnostic information when an exception is thrown:
~~~
Started : 2019-06-15T11:30:22.646
----------------------------------------------------------------
Foo_Bar_IT.retrieve
Response Code: ACCEPTED
Response Correlation Id: DEV16B567A25BBQ000000509
Status: FAILED
Duration: 00:00:01.581
----------------------------------------------------------------
Finished: 2019-06-15T11:30:25.06
Duration: 00:00:02.414
~~~
Perhaps it may be helpful if I describe more fully the context in which my Citrus tests are running. These system tests are being run neither in an IDE nor as part of a CI process. Instead, they are executed by a standalone service that periodically runs the tests and records the results in a database, which are then visualized as time series data.
This is implemented as follows:
* Spring Boot application
* JUnit 5 custom test launcher
* Citrus test driver that runs the tests and produces results
* Postgres database
* Grafana time series data visualizer

The motivation for this is that we expect tests will sometimes fail due to events outside our control: changes and errors that occur in the systems on which our system depends, and network failures. While we should be able to see 100% tests passing when all goes well, it is not realistic to expect that all of our system tests will pass all the time. Instead, we want to be able to track trends over time and need to define success in terms of success rates instead of boolean pass/fail.

**Comment by tvelkoff** [comment]
Post script:
I think in my treatise about _success_, _failure_, and _error_ I may have strayed into an unnecessary ivory tower. My goal is nothing more than mapping the system test results to the normal outcomes of a JUnit test, visualized as green, blue and red.

**Comment by christophd** [comment]
Many thanks for the detailed description of why you are doing things. This helps a lot to understand the motivation and goals.

Regarding the diagnostic information I would rather use a custom implementation of the [MessageListener](https://github.com/citrusframework/citrus/blob/a0b418a3782870792096e0fe5a4c4f9213195bbf/modules/citrus-core/src/main/java/com/consol/citrus/report/MessageListener.java). 

The listener is executed before the actual message validation takes place. So you can grab message information and add the diagnostics to the text context or write those to a database directly if you want. 

The listeners are configured once in your project so you do not need all those XPath expressions defined in all test cases which is a huge benefit in my eyes. Here you can also catch exceptions when the optional element is simply not available in order to have a failsafe extraction.

The test itself just defines the XPath validations and very specific extractions and fails of course as usual. You would still have all the diagnostics.

WDYT

**Comment by christophd** [comment]
You just need to add the custom message listener implementation to the Spring bean context and you are ready to go

**Comment by svettwer** [comment]
I agree with @christophd. A custom message listener would be a good idea to gather some diagnostic data without manipulating the test case itself.

**Comment by tvelkoff** [comment]
Thanks to both of you for your careful review and feedback. I'll go back to the drawing board with this.

My takeaway is that I should collect all diagnostic information with a MessageListener and reserve the TestRunner API for evaluating the XPath pass/fail conditions.

As it turns out, I'm having difficulty getting the MessageTracingTestListener to output messages to files, but rather than pollute this topic, I will post my questions about that separately.

Thanks!

**Comment by svettwer** [comment]
Glad we could help.

I'll close this issue for now. Please keep us updated if the attempt solved your problem or reopen the issue if not. 

I'm looking forward to the results. =) 

BTW. I'll have a look at your anyways. I realized that there are a lot of test cases written. Maybe I can pick up one or two. 

BR, 
Sven

**Comment by tvelkoff** [comment]
Thanks, Sven. Will do.
