### ISSUE TITLE
How to send ssh command with Java DSL

### ISSUE THREAD

**Issue by chokdee** [citrusframework/citrus#666]
**Citrus Version**
2.7.4

**Question**
We want to migrate from XML to Java DSL. But I can't find the syntax for the following commands

```
<send endpoint="sshClient">
            <message>
               <payload>
                  <ssh-request xmlns="http://www.citrusframework.org/schema/ssh/message">
                     <command>${sshcommand}</command>
                     <stdin></stdin>
                  </ssh-request>
               </payload>
            </message>
         </send>
         <receive endpoint="sshClient">
            <message>
               <payload>
                  <ssh-response xmlns="http://www.citrusframework.org/schema/ssh/message">
                     <stdout>@contains(response from server is 'ok')@</stdout>
                     <stderr/>
                     <exit>0</exit>
                  </ssh-response>
               </payload>
            </message>
         </receive>
```

**What I've tried so far**
send(action -> action.endpoint("sshClient").payload().ssh ??

**Additional information**

**Comment by hmmlopez** [comment]
Have you tried the following?

send(action -> action.endpoint("sshClient").message(new SshMessage()));
I’m using it like that for Http, think it is the same for SSH.

Humphrey

**Comment by chokdee** [comment]
message() and payload() doesn't accept a parameter of type SshRequest.

**Comment by svettwer** [comment]
Hi! :wave: 

As this is a very old module, I had to research a little bit but according to the [SshClientTest](https://github.com/citrusframework/citrus/blob/c0612b5a4e49b87ed1f8faf05f98db9aebb01054/modules/citrus-ssh/src/test/java/com/consol/citrus/ssh/client/SshClientTest.java#L184)
 it should be something like the following. I have not tested it but I'm pretty confident that this should work.

```java
    private final SshMarshaller marshaller = new SshMarshaller();

    @Test
    @CitrusTest
    public void testGet() {
        final SshRequest request = new SshRequest("ls", null);
        send(builder -> builder.endpoint("ssh-client")
                                   .message(createSshMessage(request)));
    }

    private Message createSshMessage(final SshMessage sshMessage) {
        final StringResult payload = new StringResult();
        marshaller.marshal(sshMessage, payload);
        return new DefaultMessage(payload);
    }
```
The `createSshMessage` function uses the general interfaces and therefore accepts `SshResponses` as well.

I hope that helps you.

BR,
Sven

**Comment by chokdee** [comment]
Hi Sven

sorry for my late reply. Yes that helps me. Only one thing was wrong
`return new DefaultMessage(payload);`
must be
`return new DefaultMessage(payload.toString());`

Can you help me too with receiving and validating the message?
According to your example I need to verify the result:

```
<receive endpoint="sshClient">
            <message>
               <payload>
                  <ssh-response xmlns="http://www.citrusframework.org/schema/ssh/message">
                     <stdout>@contains(.)@</stdout>
                     <stderr/>
                     <exit>0</exit>
                  </ssh-response>
               </payload>
            </message>
         </receive>
```

How can I do it?
`receive(builder -> builder.endpoint("sshClient").validate("@contains(.)@", true));`
doesn't work.

Thanks
Juergen 

btw: I have written a xml to Java DSL converter. It's a bit customized for our projects because we have some own action written bust maybe it will help some guys
