### ISSUE TITLE
Citrus Kafka - purge offset

### ISSUE THREAD

**Issue by vinceseguin** [citrusframework/citrus#681]
As an integration tester, I would like to purge a Kafka topic (set offset to the last message) to ensure I get the correct message when running my tests.

I'm willing to contribute the code in order to do this, but I'm curious to know if that feature would be interesting first.

Thanks!

**Comment by svettwer** [comment]
Hi,

purging kafka endpoints is already implemented. E.g.:
```java
@Bean
    public TestRunnerAfterTestSupport cleanUp(){
        return new TestRunnerAfterTestSupport() {
            @Override
            public void afterTest(final TestRunner testRunner) {
                testRunner.purgeEndpoints(purgeEndpointsBuilder ->
                        purgeEndpointsBuilder.endpoint(myKafkaEndpoint));
            }
        };
    }
```

BR,
Sven
