### ISSUE TITLE
Citrus Kafka consumer is attempting to unsubscribe only when there are no subscriptions already.

### ISSUE THREAD

**Issue by MikhailovNikita** [citrusframework/citrus#687]
**Citrus Version**
2.8.0

**Expected behavior**
Citrus KafkaConsumer is unsubscribing from all the assigned partitions when the method stop() is called.

**Actual behavior**
The consumer is unsubscribing only when there are no subscriptions, so the condition is inverted.

**Test case sample**
I think it's clear enough that it works the other way just by looking at the code.
https://github.com/citrusframework/citrus/blob/master/modules/citrus-kafka/src/main/java/com/consol/citrus/kafka/endpoint/KafkaConsumer.java at line 97.

**Comment by novarx** [comment]
This has been fixed: 

- https://github.com/citrusframework/citrus/blob/v4.3.2/endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaConsumer.java#L102
- https://github.com/citrusframework/citrus/pull/688

May be closed @christophd / @bbortt

**Comment by christophd** [comment]
Many thanks!
