### ISSUE TITLE
Feature Request - Support of appending nodes to XMLs prior to shipping the payload

### ISSUE THREAD

**Issue by lebuitrago** [citrusframework/citrus#69]
## Feature Request Description

Option to configure a data-dictionary, via the Spring bean definition,  to support APPENDing a node and text, that does not exist in the payload. 
### Sample

Will explain it with a scenario: 
### Payload

```
<Product>
    <Name>ProductName</Name>
    <Description>Description of the product</Description>
    <Cost>10.00</Cost>
    <CountriesInStock>
        <Germany>true</Germany>
        <UnitedStates>false</UnitedStates>
        <Colombia>true</Colombia>
        <Qatar>true</Qatar>
    </CountriesInStock>
</Product>
```

-- This is not good XML design, and unfortunately, out in the wild, any goes. 
### Requirement

For testing, I would need to include the following dynamically :

```
<ElSalvador>
<Italy>
```

as 'true' within the

`<CountriesInStock>`
### Possible Usage

Adding the tag and values via the Variables like so:

```
variable("ElSalvador", "true");
variable("Italy", "true");
send(action -> action.endpoint("ToThere")
.payload(new ClassPathResource(payload));
```

A sample context file snippet:

```
<citrus:xpath-data-dictionary id="xpathMappingDataDictionary">
     <citrus:mappings>
          <citrus:mapping path="//Product/Name" value="${ProductName}" />
          <citrus:mapping path="//Product/Description" value="${ProductDescription}" />
          <citrus:mapping path="//Product/Cost" value="${ProductCost}" />
          <citrus:mapping path="//CountriesInStock/Germany" value="${Germany}" />
          <citrus:mapping path="//CountriesInStock/UnitedStates" value="${UnitedStates}" />
          <citrus:mapping path="//CountriesInStock/Qatar" value="${Qatar}" />
          <citrus:mapping path="//CountriesInStock/Colombia" value="${Colombia}" />

          <citrus:mapping path="//CountriesInStock/ElSalvador" value="${ElSalvador}" append="true"/>
          <citrus:mapping path="//CountriesInStock/Italy" value="${Italy}" append="true"/>
     </citrus:mappings>
</citrus:xpath-data-dictionary>
```

Note the **append="true"** attributes which would notify Citrus to consider these special 'appendable' nodes; meaning if they do not exist, append them. False can be default. 
### Design Consideration

In this sample, there would be 196 entries entered into the bean definition, or located on an external file that would be referenced via citrus:mapping-file. 
### Conclusion

This would allow for more options to work with, in regards to the data-dictionary

Have a great day.

**Comment by lebuitrago** [comment]
I have developed my own utility function that manages content of the payload PRIOR to sending it over to Citrus. By the time I need Citrus to get involved, the payload has already been modified dynamically and is ready for Citrus to send it over to its destination.

I believe this might be the best way to go about it, rather than having it in the framework.

In other words, any XML structure modifications should be done outside Citrus. Perhaps the framework should not get into managing the XML structure, but only deal with its transportation to & from our system.

I feel like this issue/request should be closed.

**Comment by svettwer** [comment]
Closed by OP request
