### ISSUE TITLE
Update Spring to 5.2.0.RELEASE

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#696]
To update the citrus simulator to use the latest Spring Boot version and to be able to build Citrus with java 13, it is required to update to the latest spring version.

Required by:
- https://github.com/citrusframework/citrus-simulator/issues/15#issuecomment-548485419
- https://github.com/citrusframework/citrus-simulator/issues/78

**Comment by bbortt** [comment]
Hi Sven
Whats left to do? I might have some time this weekend.
BR Timon

**Comment by christophd** [comment]
Hi Timon

I think it is "just" to bump the versions to a newer Spring version and fix some broken things afterwards. 

There should be some compile errors to fix and some tests may fail after update. Once the Citrus build with all tests is green you can also run the [citrus-samples](https://github.com/citrusframework/citrus-samples) with that updated version. If these samples are also good you can be quite sure to have a successful update.

**Comment by bbortt** [comment]
Hi Christoph
Yes, I mean that's pretty straight forward. I just saw that Sven already referenced two commits.. and didn't know what else he already did.
At this point I `cherry-pick`ed 416488201d42474284287b184ecfb074c9527c76 and bc98f3caca32e22c5b761b0b5e5d2225a34d3a84 and am working on this task in my fork.
BR, Timon

**Comment by christophd** [comment]
Fixed with https://github.com/citrusframework/citrus/releases/tag/v3.0.0-M1

**Comment by bbortt** [comment]
Don't know if this is already enough.. what about the "legacy" dependencies like `javax.*`?

**Comment by christophd** [comment]
True can you please open a separate issue for that?

**Comment by bbortt** [comment]
Sure, I will 👍
