### ISSUE TITLE
Add citrus:unixTimestamp() to Citrus functions

### ISSUE THREAD

**Issue by svettwer** [citrusframework/citrus#697]
**User story**
As a test developer, I want to be able to obtain the current unix timestamp as a Citrus function to be able to parameterize payload templates.

**Additional Information**
```json
{
  "timestamp":  "citrus:unixTimestamp()"
}
```
Should result in the following after processing:
```json
{
  "timestamp":  "1573045235"
}
```

It would be great to have a switch implemented, causing the return value to be in milliseconds instead of seconds.

**Comment by farhad-vaghari** [comment]
hi.
i want to work on this issue but i can't run the project.

Error:(28, 13) java: cannot find symbol
  symbol:   class SchemaRepositoryModel
  location: class com.consol.citrus.model.config.core.SchemaRepositoryModelBuilder


Error:(28, 47) java: cannot find symbol
  symbol:   class SchemaRepositoryModel
  location: class com.consol.citrus.model.config.core.SchemaRepositoryModelBuilder


do you know what is the problem?

**Comment by akuz0** [comment]
@svettwer Hello, i want fix it, please can you review my step (general concept of action, in scattered order)
1. Added for FunctionsIT.xml unixTimestamp
2. In class DefaultFunctionLibrary added unixTimestamp
4. Create in com.consol.citrus.functions.core new class 'unixTimestampFunction'
3. In class Functions added unixTimestamp
3. Added test in FunctionsTest

**Comment by bbortt** [comment]
@akuz0 this sound good in general, but is hard to say without seeing any code ;)

**Comment by bbortt** [comment]
Hi @akuz0, I have reviewed your PR. there seems to be a little bit of code missing to make this work (the build fails). but it looks very good in general! let me know if you need some hints, I have not looked into it further (apart from the commends I made).
