### ISSUE TITLE
Could not resolve dependencies for project com.consol.citrus.samples:citrus-sample-testng:jar:2.8.0

### ISSUE THREAD

**Issue by iskander188** [citrusframework/citrus#704]
**Citrus Version**
2.8.0

**Expected behavior**
execute the Citrus test cases

**Actual behavior**
Failed to execute goal on project citrus-sample-testng: Could not resolve dependencies for project

**Test case sample**

Run -  mvn clean install -U
[log_error1.txt](https://github.com/citrusframework/citrus/files/3984982/log_error1.txt)

https://repo.maven.apache.org/maven2/com/consol/citrus/samples/citrus-sample-todo/2.8.0/citrus-sample-todo-2.8.0.jar
404 Not Found

**Comment by bbortt** [comment]
issue `stale`.
