### ISSUE TITLE
aws sdk integration

### ISSUE THREAD

**Issue by mlybarger** [citrusframework/citrus#713]
I have some components in my system which are aws lambda based.  I can invoke directly from the aws sdk, or i can hackishly use aws cli from ssh endpoint.   Our team is doing the latter right now, but it seems that some direct integration with citrus might be nicer.  Has anyone else looked at doing AWS lambda automation from citrus directly from aws api instead of aws cli?

**Comment by christophd** [comment]
You can have a look at the [Apache Camel components](https://camel.apache.org/components/latest/index.html). These components can be used in a Citrus test. You can create a Camel route that connects to AWS and call it from Citrus. Also you can use a dynamic endpoint for send operations:

```
send().endpoint("camel:aws-lambda://functionName[?options]");
```

Here is the [AWS Lambda component](https://camel.apache.org/components/latest/aws-lambda-component.html)
