### ISSUE TITLE
CitrusRuntimeException: Unable to create message tracing output directory

### ISSUE THREAD

**Issue by rksurapaneni** [citrusframework/citrus#717]
**Citrus Version**2.7.9

**Question**CitrusRuntimeException: Unable to create message tracing output directory

**What I've tried so far**Tried creating manually did not work

**Additional information**

**Comment by christophd** [comment]
Most probably a permission issue on your local system to create the output folders and/or files. By default Citrus tries to create this directory: `target/citrus-logs/trace/messages`

Please check permissions on this output folder.

You can also customize this directory via System property
```
citrus.message.trace.directory=/my/very/special/directory
```
or environment variable
```
CITRUS_MESSAGE_TRACE_DIRECTORY=/my/very/special/directory
```
