### ISSUE TITLE
I need example for QueueBrowser   in CitrusFramework

### ISSUE THREAD

**Issue by srilagi** [citrusframework/citrus#719]
**Citrus Version**

**Question**

**What I've tried so far**

**Additional information**

**Comment by christophd** [comment]
@srilagi Can you please elaborate on this? 

What messaging transport are you referring to? JMS, Kafka, something else? 

Please describe your use case and what you want to be able to do in more detail.

**Comment by srilagi** [comment]
Hi  Christoph,


I am trying to  configure the  IBM MQ QueueBrowser  using citrus
framework.   Current Citrus ReceiveMessageBuilder not supporting to
retrieve the message from the Queuebrowser.

  I have used Junit concept to  retrieve the messages from the Queuebrowser.

Can you please provide me the code snipper to retrieve the messages  from
the Queuebrowser using ReceiveMessageBuilder.

Thanks,
Srikanth.

**Comment by srilagi** [comment]
Hi Christoph,

I am  trying to develop code to read the messages from IBM MQ Queue using
Queue Browser mechanism.

Can you please provide the example for the above connector.

Thanks,
Srikanth.

**Comment by christophd** [comment]
So to understand your need correctly you are trying to read messages from IBM MQ queue without consuming those? Is that what you want to achieve with "browsing"

**Comment by srilagi** [comment]
Yes Christoph.

Sorry for the late reply.

We are developing microservices and most of the services communication
between and rest and mq queues. So, i want  do testing in testing
environment with out distributing original flow.

I have created test cases by using junit, but i am more interested in
developing using citrus framework.

So, please provide me  lead to develop the test case using citrus.

Thanks,
Srikanth.

**Comment by christophd** [comment]
Browsing messages on queues without consuming those messages is not part of the JMS standard to my knowledge. So queue browser implementations are always vendor specific features. This is why Citrus is will not be able to use those vendor specific browsers out of the box in order to consume messages.
