### ISSUE TITLE
Upgrade from 2.8.0 to 3.0.0

### ISSUE THREAD

**Issue by awgtek** [citrusframework/citrus#730]
**Citrus Version**
3.0.0-M1

**Question**
Need help with migration

**What I've tried so far**
I just tried the upgrade, but some code got broken:
- designer.setDescription(description); "cannot resolve method setDescription"
- import com.consol.citrus.cucumber.step.designer.core.MessagingSteps; "cannot resolve symbol designer"
- messagingSteps.addPayload(messageId, payload); cannot resolve addPayload

I checked the migration page but couldn't find any clues on how to migrate these functions, any help is appreciated.

**Additional information**
Need the ability to set a description on a step, and also add a payload during the design phase to messaging steps. Are these still available functions?

**Comment by christophd** [comment]
The test designer got replaced with the runner implementation in 3.0.0-M1. So you should have a look on equivalent classes in `runner` package instead of `designer`
