### ISSUE TITLE
Validating Camel Route Response not working (conversion fails)

### ISSUE THREAD

**Issue by bthdimension** [citrusframework/citrus#736]
**Citrus Version**
2.8.0

**Question**
When testing a Camel Route as described in the Camel testing blog post (https://citrusframework.org/news/2015/05/27/camel-testing-part-2/), I can't validate the response of the Camel Route because it is of type InputStreamCache. Citrus seems to not be able to properly convert the response:
```
WARN  c.c.citrus.util.TypeConversionUtils - Using object toString representation: Failed to convert value of type 'org.apache.camel.converter.stream.InputStreamCache' to required type 'java.lang.String'; nested exception is java.lang.IllegalStateException: Cannot convert value of type 'org.apache.camel.converter.stream.InputStreamCache' to required type 'java.lang.String': no matching editors or conversion strategy found
```

Here's my receive action:
```
receive("camel:sync:direct:postPerson")
                .name("receivedFromRoute")
                .messageType(MessageType.JSON)
                .payload(new ClassPathResource("data-expected/getPersonResponse.json"));
```

**What I've tried so far**
I used adviceWith to manually convert the result to string. It works, but it's kind of a hack …
```
@Before
    public void convertResponseFromStreamToString() throws Exception {
        context.getRouteDefinition("post-person-route")
                .adviceWith(context, new AdviceWithRouteBuilder() {
                    @Override
                    public void configure() throws Exception {
                        weaveAddLast().convertBodyTo(String.class);
                    }
                });
    }
```
**Thank you very much!**

**Comment by christophd** [comment]
good one! yes, this is a limitation of the type converter in Citrus. In Citrus 3.x you will be able to use the Camel type converter instead of the built in Citrus type converter.

The adviceWith seems to be a good workaround for now. Thanks for pointing to it

**Comment by bthdimension** [comment]
Thanks for the quick reply. Then I'll stick to my workaround for now and will be looking forward to version 3 :-)

**Comment by christophd** [comment]
Fixed in 3.x
