### ISSUE TITLE
minor: parameter name of namespace in KubernetesClientBuilder is incorrect

### ISSUE THREAD

**Issue by mingliangguo** [citrusframework/citrus#741]
Currently, the parameter in `namespace` method to set the namespace for KubernetesClientBuilder.java is incorrectly named as `email`, which is a bit confusing:

https://github.com/citrusframework/citrus/blob/7028a1aa3b825b87fefd9107363a0886084062bb/connectors/citrus-kubernetes/src/main/java/com/consol/citrus/kubernetes/client/KubernetesClientBuilder.java#L85-L93

**Citrus Version**

All versions.

**Expected behavior**

The name should reflect what it's used for.

**Actual behavior**

**Test case sample**
> Please, share the test case (as small as possible) which shows the issue

As this is a really minor issue, if it's OK I can open a PR to fix the name. Thanks!

**Comment by christophd** [comment]
@mingliangguo Many thanks! Please feel free to open a PR. Contributions are very welcome!

**Comment by mingliangguo** [comment]
Thanks, @christophd ! Just opened https://github.com/citrusframework/citrus/pull/742 Please let me know if I need to follow any practices for the PR. And any other branches we should port the changes to. Thanks!
