### ISSUE TITLE
Make Javadoc publicly available

### ISSUE THREAD

**Issue by christerengman** [citrusframework/citrus#746]
**User story**
As a tester, I want to be able to have Javadoc easily available for reference so that I know how to use the framework on a detailed level.

**Additional context**
The Javadoc should be available alongside the reference documentation. Maybe I'm blind but I simply cannot find it.

Today you have to either browse the source or rely on IDE support which is not always applicable. For example if you want to browse available implementations of an abstract class or an interface. This will be even more important with Citrus Framework 3.x as it is more modular.

As a bonus, this will increase Javadoc quality as it will be more exposed.

**Comment by christophd** [comment]
Please use https://javadoc.io/doc/com.consol.citrus

Maybe a good idea to add this link to the website to make it more prominent.

**Comment by christophd** [comment]
@christerengman I would close this one in favor of https://github.com/citrusframework/citrus-website/issues/10. Good for you?

**Comment by christerengman** [comment]
Fine with me. I'll add comments there.
