### ISSUE TITLE
 validationCallback on a HttpServerActionBuilder makes other validators being skipped

### ISSUE THREAD

**Issue by CarmenRD** [citrusframework/citrus#753]
**Citrus Version**
2.8.0

**Expected behavior**
All other message validators like e.g. for header verification should also be evaluated.

**Actual behavior**
Adding a validationCallback on a HttpServerActionBuilder results in other message validators for the response to a HTTP request not being evaluated.
E.g. expected header values are not evaluated. While with .validationCallback() custom validation logic can be easily wrapped into e.g. a one-line lambda statement, not being able to combine it with other message validators makes it hardly useful. The current behaviour is not obvious and also not documented. 

**Test case sample**
> Please, share the test case (as small as possible) which shows the issue

 ```
HttpServer myServer = ....; // omitted as not relevant
        http(action -> action.server(myServer)
                .receive()
                .post("/my/path/")
                .header("importantheader", not(emptyString())) // never fails 
                .validationCallback((message, ctx) -> assertEquals(message.getPayload().toString(),  "e.g. no json/xml message")));
```

**Comment by christophd** [comment]
Yes, the validation callback is an exclusive validation. When this is set no other validation mechanism is performed. We assume that you will do all customized validation logic in the callback with any assertion also on the header because you are provided with the message object in the callback.
