### ISSUE TITLE
FTP command The prefix "ftp" for element "ftp:command" is not bound.

### ISSUE THREAD

**Issue by bodharavikishore** [citrusframework/citrus#765]
**Citrus Version** =2.8.0

**Question**
FTP command The prefix "ftp" for element "ftp:command" is not bound.

**What I've tried so far**
Yes, I added supported schemas in the XML file.But still, I am getting ftp: command not bound issue.
![image](https://user-images.githubusercontent.com/28592139/112163646-3d8f4980-8c13-11eb-9241-f6b858f27f30.png)

**Additional information**
I need to test the FTP from source to target file transmission. Could you please help with this @christophd

**Comment by christophd** [comment]
You need to declare the XML namespace of the ftp message schema in the root element spring:beans like

`xmlns:ftp="http://www.citrusframework.org/schema/ftp/message"`

Please also add the schema location.

`http://www.citrusframework.org/schema/ftp/message http://www.citrusframework.org/schema/ftp/citrus-ftp-message.xsd`

**Comment by bodharavikishore** [comment]
It 'sworking, But need to add this schema's in citrus FTP doc's 
Thank you  @christophd
