### ISSUE TITLE
How to update Citrus FTP Host,Port,Username,Password with dynamic cucumber variables

### ISSUE THREAD

**Issue by bodharavikishore** [citrusframework/citrus#767]
**Citrus Version**
2.7

**Question**
How to make Citrus FTP Host,Port, Username,Password with dynamic variables

**What I've tried so far**
Feature file
Scenario: Test FTP
        Given FTP Host:"localhost"
        Given FTP Port:"21"
        Given FTP Username:"ravi"
        Given FTP Password:"admin"
        Given Test FTP connection

Steps.Xml:
<spring:beans xmlns="http://www.citrusframework.org/schema/cucumber/testcase"xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:spring="http://www.springframework.org/schema/beans"
 xmlns:citrus="http://www.citrusframework.org/schema/testcase"
 xmlns:citrus-ftp="http://www.citrusframework.org/schema/ftp/config"
xmlns:citrus-http="http://www.citrusframework.org/schema/http/config" 
xsi:schemaLocation="
    http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd http://www.citrusframework.org/schema/cucumber/testcase 
http://www.citrusframework.org/schema/cucumber/testcase/citrus-cucumber-testcase.xsd 
http://www.citrusframework.org/schema/http/config
 http://www.citrusframework.org/schema/http/config/citrus-http-config.xsd
http://www.citrusframework.org/schema/ftp/config
 http://www.citrusframework.org/schema/ftp/config/citrus-ftp-config.xsd">

<step given="^Test FTP connection">
<citrus:call-template name="MyFTP">
</citrus:call-template>
</step>

 <citrus-ftp:client id="ftpClient"
      host="${var1}"
      port="${var2}"
      username="${var3}"
      password="${var4}"
      timeout="10000"/>
 
<spring:import resource="FTP_Template.xml" />

</spring:beans>

**Additional information**
I have a cucumber feature file. In the file, I am declared the variables FTP host port username password. I need to make the feature file variables as an input to <citrus-ftp: client> to make dynamic configuration through feature files. Could you please help me with this @christophd

**Comment by bodharavikishore** [comment]
<step given="^Test FTP connection">
<citrus:call-template name="MyFTP">
</citrus:call-template>
</step>

**Comment by bodharavikishore** [comment]
Could you please help me with this @christophd

**Comment by christophd** [comment]
please have a look at the YAKS project (https://github.com/citrusframework/yaks) which leverages Citrus in combination with Cuucmber. The YAKS test is able to load Citrus components as part of the feature and this would allow you to set the test variables and use those in the FTP client component configuration.
