### ISSUE TITLE
set JMSMessageId when sending MQ messages

### ISSUE THREAD

**Issue by ZuikovAV** [citrusframework/citrus#780]
Hi!

Could you tell me please, are any working ways to set up JMSMessageId?

System under test uses MQ with both correlationId and JMSMessageId.

I'm trying to set up JMSMessageId in headers but as i understand JMS client rewrites the value as null and i can't do anything to prevent it.

**Comment by christophd** [comment]
Hi,

please use the special Citrus message headers that set those headers on the JMS message while converting the general message to a JMS message.

https://github.com/citrusframework/citrus/blob/main/endpoints/citrus-jms/src/main/java/com/consol/citrus/jms/message/JmsMessageHeaders.java

When writing tests in Java you can use the JmsMessage that provides some convenient methods to set those IDs:

https://github.com/citrusframework/citrus/blob/main/endpoints/citrus-jms/src/main/java/com/consol/citrus/jms/message/JmsMessage.java

**Comment by ZuikovAV** [comment]
Hi! Thanks for the comment!

The decision, sadly was to use non-citrus non-JMS MQ Message libraries...

**Comment by christophd** [comment]
Hi! Citrus also supports Kafka 😁
