### ISSUE TITLE
Custom Error Messages in CITRUS Test Results

### ISSUE THREAD

**Issue by bodharavikishore** [citrusframework/citrus#785]
**Citrus Version**
2.8.0

**Question**
Custom Error Messages in CITRUS Test Results

**What I've tried so far**
I want to use my custom error messages in my citrus test results. Example: Original Error Message: java.io.FileNotFoundException: D:\expectedOutput\Smaple.xml (The system cannot find the file specified).

Custom Message: Hey The File was not found in your directory Please check. (Need to print like this in my test results failure message).
@christophd 

**Additional information**
![image](https://user-images.githubusercontent.com/28592139/126493916-20080627-5d5e-433f-8fdf-6e613eeb0d48.png)

**Comment by christophd** [comment]
You can not change this message in particular as this is coming from the thrown Java exception. You could implement your own TestReporter and/or TestListener though to translate the error into something matching your needs.

Something like: https://citrusframework.org/samples/reporting/
