### ISSUE TITLE
Citrus 3.0.0 requires Java 11 despite information in readme

### ISSUE THREAD

**Issue by apupier** [citrusframework/citrus#786]
**Citrus Version**
3.0.0

**Expected behavior**

Working with Java 8 or readme stating Java 11 as mandatory

**Actual behavior**

[Readme is stating that Java 8 is required](https://github.com/citrusframework/citrus/tree/v3.0.0#preconditions) but [Java 11 is required](https://github.com/citrusframework/citrus/blob/4f9adee1de1f389bc3be2d98640e0ec72bbcb74d/pom.xml#L141)

it has changed between [3.0.0.M3 and 3.0.0](https://github.com/citrusframework/citrus/commit/45dd8d5acf518e81397c729b4af034af226f4e39)

**Test case sample**
> Please, share the test case (as small as possible) which shows the issue

for instance:
https://app.circleci.com/pipelines/github/camel-tooling/camel-language-server/373/workflows/0f993ca3-9d1d-4e30-bbee-01c144d1f8d6/jobs/1445
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project camel-lsp-server: Compilation failure
[ERROR] /home/circleci/project/src/test/java/com/github/cameltooling/lsp/internal/completion/KafkaTopicCompletionTest.java:[35,40] cannot access com.consol.citrus.kafka.embedded.EmbeddedKafkaServer
[ERROR]   bad class file: /home/circleci/.m2/repository/com/consol/citrus/citrus-kafka/3.0.0/citrus-kafka-3.0.0.jar(com/consol/citrus/kafka/embedded/EmbeddedKafkaServer.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

**Comment by christophd** [comment]
@apupier thx
