### ISSUE TITLE
Citrus Catch JAVA exceptions

### ISSUE THREAD

**Issue by bodharavikishore** [citrusframework/citrus#787]
**Citrus Version**
2.8.0

**Question**
Citrus Catch JAVA exceptions

**What I've tried so far**
I need to catch the java exceptions in citrus. Example: File not found exception. I need to catch it and make the test case successful.

`<catch exception="java.io.FileNotFoundException">
 <echo>
  <message>D:\expectedOutput\Rest_Authh.json</message>
</echo>
</catch>`

**Additional information**
![image](https://user-images.githubusercontent.com/28592139/126791876-7d4fcaa9-29b8-48f2-b8f8-03172cea83c8.png)

**Comment by bodharavikishore** [comment]
@christophd

**Comment by christophd** [comment]
The `catch` action in Citrus is a container action that holds a nested test action. This This nested action may raise the exception during processing and the surrounding `catch` will handle the exception. 

The echo test action in your sample will not throw such a FileNotFoundException. This exception must be thrown somewhere else in your test. Can you please elaborate on your sample?

**Comment by bodharavikishore** [comment]
Please provide me the SYNTAX of catching java exceptions.

**Comment by christophd** [comment]
something like
```xml
<catch  exception="java.io.FileNotFoundException">
  <receive endpoint="someEndpoint">
    <message>
      <payload file="classpath:some/file/that/does-not-exist.xml"/>
    </message>
  </receive>
</catch>
```

**Comment by bodharavikishore** [comment]
yes
