### ISSUE TITLE
Citrus Performance Load  testing with report

### ISSUE THREAD

**Issue by bodharavikishore** [citrusframework/citrus#797]
**Citrus Version**
3.1.0

**Question**
Is it possible to do performance Load tests in citrus-like karate Gatling with reports?

**What I've tried so far**

**Additional information**

**Comment by bodharavikishore** [comment]
@christophd  Could please help me with this!

**Comment by christophd** [comment]
Simple load tests where Citrus runs client requests with a given thread count and with a given iteration count can be accomplished with TestNG. See this example: https://citrusframework.org/samples/http-loadtest/

**Comment by christophd** [comment]
Please note the examples still use 2.x Java fluent API
