### ISSUE TITLE
What version of io.cucumber is compatible with Citrus 2.8.0?

### ISSUE THREAD

**Issue by qyouyang** [citrusframework/citrus#798]
Hi, 
I’ve been trying to have the Citrus framework stood up to write integration tests for my project. For context, my project is a Spring microservice running on Java 8, Gradle 6.1.1, Junit 4.13, and Cucumber 4.3.0. I tried configuring Citrus 2.8.0 using these gradle dependencies:

`citrus-core:2.8.0
citrus:citrus-java-dsl:2.8.0
citrus:citrus-http:2.8.0
citrus:citrus-cucumber:2.8.0`

When I run the Citrus runner I created to kick off Cucumber tests, I'm getting this error (see screenshot for full stacktrace)
`cucumber/runtime/DefaultSummaryPrinter
java.lang.NoClassDefFoundError: cucumber/runtime/DefaultSummaryPrinter`

I think io.cucumber version might be incompatible with citrus-cucumber. I’m wondering what Citrus version I should use inste
![image (5)](https://user-images.githubusercontent.com/24872156/131748144-17b55313-93a0-4a37-9f92-48c1ce11ef60.png)
ad.
 
Thanks so much for your time!

**Comment by christophd** [comment]
The pom.xml in v2.8.0 uses Cucumber v3.0.2

In case you need to use a newer version of Cucumber please update to Citrus 3
