### ISSUE TITLE
Question: does Citrus support relative paths in  SOAP WSDL/XSD validation?

### ISSUE THREAD

**Issue by ejbartelds** [citrusframework/citrus#808]
**Citrus Version**
3.1.0

**Question**
Does Citrus support relative paths in  SOAP WSDL/XSD validation?  It appears it does not, but perhaps that is because I am doing something wrong in preparing the schemaRepository bean.

**What I've tried so far**

- adding all individual WSDLs and XSDs to the `XsdSchemaRepository` bean using `getSchemas().add()`.
- patching `JarWSDLLocator.getImportInputSource` so it knows how to deal with presence of  `../` (and `../../` etc) in parameter `importLocation` (basically: stripping the relative pieces and manipulating both `parentLocation` and `importLocation`, making `parentLocation+importLocation` a valid path).
- patching `WsdlXsdSchema` and `XsdSchemaRepository` to make use of that changed JarWSDLLocator.
- using `schemaRepository.setLocations()` instead of `getSchemas().add()` (because I noticed the `initialize` call will pick up the locations and actually call `addWsdlSchema()` when it encounters a WSDL.
-  I looked through the samples project looking for an appropriate example, none found.
- scanned Github issues for applicable issues (none found).

Unfortunately, none of the above seem to work. I keep getting an error like:
```
org.xml.sax.SAXParseException; lineNumber: 14; columnNumber: 59; src-resolve: Cannot resolve the name 'ns2:my-type' to a(n) 'type definition' component.
``` 

**Additional information**

I am working with a WSDL that looks like this (showing relevant fragment from top of file only):
```
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="https://sample.com/ns1"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap12/"
                  targetNamespace="https://sample.com/ns1">

    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://sample.com/ns1">
            <xs:import namespace="https://sample.com/ns1" schemaLocation="ns1.xsd"/>
        </xs:schema>
    </wsdl:types>
...
...
```
It references a `ns1.xsd` that has this:
```
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
           targetNamespace="https://schemas.ech.nl/ech-ws/systeem" xmlns:ns1="https://sample.com/ns1"
           xmlns:ns2="https://sample.com/ns2">

    <xs:include schemaLocation="systeem.xsd"/>
    <xs:import namespace="https://sample.com/ns2" schemaLocation="../../ns2/ns2.xsd"/>
```
So a `ns2.xsd` is referenced via a relative path. All mentioned and references XSD and WSDL files are present on the classpath in the proper relative places.

**Comment by christophd** [comment]
Have you tried to use a [XsdSchemaCollection](https://github.com/citrusframework/citrus/blob/main/validation/citrus-validation-xml/src/main/java/com/consol/citrus/xml/schema/XsdSchemaCollection.java)? I think adding the schemas in a collection may solve your prroblem

**Comment by ejbartelds** [comment]
Yes, that's exactly what we did eventually.  Back when I wrote the original question I think I probably didn't know about XsdSchemaCollection's existence yet.

One remark though: the WSDLs/XSDs we were trying to use are contained in a JAR file. Accessing them directly from within the JAR didn't work, so we extracted them first.
