### ISSUE TITLE
Factory for TestCase/TestCaseMetaInfo

### ISSUE THREAD

**Issue by tschlat** [citrusframework/citrus#818]
**User story**
As a user of a testing framework I would like to have the flexibility to use own implementations of TestCase and TestCaseMetaInfo.

*Usage example for specific TestCaseMetaInfo*
For example I would like to extend the basic TestCaseMetaInfos by the following additional properties:
- caseId - to track a unique TestCase id used in TestManagement tools
- hlCaseId - to track a high level TestCase id used in TestManagement tools
- label - to group TestCases
- issue - to assign an issue to a TestCase

*Usage example for specific TestCase*
I would like to treat the issue label in my specific TestCaseMetaInfo in the following way:
- If an issue is set and the test fails, report it as skipped. Since the issue is set, I know somebody is working on it and and I don't want the execution to blow my results.
- If an issue is set and the test passes, report it as failed with the specific message that tells me to remove the issue label from the TestCase (cleanup after work is done). 

In order to implement such a behaviour I need to be able to change the default reporting behaviour and thus some implementation details of a TestCase.

**Comment by christophd** [comment]
+1

Using annotations would be great for this

**Comment by tschlat** [comment]
PR has been merged.
