### ISSUE TITLE
Access variable content by xpath/jsonPath

### ISSUE THREAD

**Issue by tschlat** [citrusframework/citrus#821]
**User story**
As a test designer I often have to access data stored as json/xml. I would like to access this data directly by specifying a jsonPath/xpath as variable reference.

E.g.
A json of form:

`{
   "id": 12,
   "name": "sample"
}`

which is stored in the TestContext as variable **jsonVar**.

Should be accessible by the following variable expression: **${jsonVar.id}**

**Comment by christophd** [comment]
+1 but we need to find a good syntax for these kind of variable expressions that separate from normal bean property syntax used in variables
