### ISSUE TITLE
Citrus: Need to validate the status code while receiving. What is the element name?

### ISSUE THREAD

**Issue by bodharavikishore** [citrusframework/citrus#828]
Need to validate the status code while JMS receiving. What is the element name?
Is it possible to get the error code in the citrus HTML report?

![image](https://user-images.githubusercontent.com/28592139/146500189-730a9760-8d1e-4d6f-9e4e-6a5eb0c86a90.png)

**Comment by bodharavikishore** [comment]
@christophd  Could you please help with this?

**Comment by christophd** [comment]
sorry, I am not sure which status code you are talking about. Is this the Http status code that is usually provided with a response? I can not see any Http component in your example so I am a bit confused. Could you please give some more information about your use case?

**Comment by bodharavikishore** [comment]
I am connecting to ACTIVE MQ. I need some status code acknowledgment like Messages are sent to the queues are not.

**Comment by bodharavikishore** [comment]
Yes, you can close this.

Thanks,
Ravikishore
