### ISSUE TITLE
readFile() function does not honor variable and function substitution when called with base64 encoding 

### ISSUE THREAD

**Issue by tschlat** [citrusframework/citrus#831]
**Citrus Version**
3.1

**Expected behavior**
The readFile() function should replace variables and function-values in file content before encoding it to base64

**Actual behavior**
The readFile() function does not replace variables and function-values in file content before encoding it to base64

**Test case sample**
There is already a test case for the implementation of this function but it does not test the content of the encoded expression by decoding it.

ReadFileResourceFunctionTest.testExecuteBase64

**Comment by christophd** [comment]
Some thoughts on a long term strategy for reading file content in this function:

I wonder if we should remove the base64 option from readFile() function for the sake of separation of concerns. Instead we can have a nested function call like this:

```
citrus:encodeBase64(citrus:readFile("some/path/to/file.foo"))
```

The readFile() function could introduce a new option `binary=true/false` (default=false) which decides how to handle the file content. Based on this option the function should automatically replace variables in the file content after reading. Replacing test variables in binary content does not make sense.

Also the function could auto guess the file content based on the file extension

- .txt = text
- .json = text
- .xml =text
- .jpg = binary
- .png = binary
- ...
