### ISSUE TITLE
Groovy Script JSON Validation failes after upgrading to Java 17 

### ISSUE THREAD

**Issue by StefanFellinger** [citrusframework/citrus#836]
**Citrus Version**
3.1.2 

**Expected behavior**
When switching between Java 11 and Java 17, my Groovy Script Validation failes. Switching back to 11, and everything works as before. Using Java 17 should work as with Java 11.

**Actual behavior**
I have some groovy script in form of "assert json.somearray.size == 2" fails with false [null, null]. It seems that the json is not parsed correctly. The output shows some double json array like [[...]], but i think it should look like [{...}]

It seems that there is some issue with arrays inside the received message, maybe the JsonSlurper.
Debugging was a little bit confusing since i'm always jumping into the ValidationScript inside script-validation-template.groovy, but one step before i'm in the GroovyJsonMessageValidator which in my opinion uses the Template json-validation-template.groovy that contains the JsonSlurper code. Nevertheless it's working with Java 11 as expected.

**Test case sample**
Switch between Java 11 (everything works as expected), and Java 17 (something went wrong)

http().client(...)
            .receive()
            .response(HttpStatus.OK)
            .message()
            .type(MessageType.JSON)
            .validate(Builder.groovy().script(validateScript))
            .build();

with some Groovy Script like:  assert json.somearray.size == 2

**Comment by christophd** [comment]
can you try to use `assert json.somearray.size() == 2`

**Comment by christophd** [comment]
we have started to work on JDK 17 compatibility a few weeks ago. We think Citrus is fine to run on JDK 17 (see PR https://github.com/citrusframework/citrus/pull/812). Some unit tests and CI job are still flaky as stated in #835

**Comment by StefanFellinger** [comment]
> can you try to use `assert json.somearray.size() == 2`

Looks good. I will adapt that to my other assertion scripts and start my round about 2000 Tests. I think that issue can be closed for now.

**Comment by christophd** [comment]
@StefanFellinger wow 2000 tests! quite impressive! are these all integration tests written with Citrus?

**Comment by StefanFellinger** [comment]
> @StefanFellinger wow 2000 tests! quite impressive! are these all integration tests written with Citrus?

Yes we are instrumenting mountbank with Test Data, testing the combination of our services with our batch and checking results for many many different business configurations. Works great. I love Citrus - good work ;-)
