### ISSUE TITLE
Can I both mock with a HttpServer and assert on it in the same test ?

### ISSUE THREAD

**Issue by benoitdupont** [citrusframework/citrus#912]
**Citrus Version**

3.3.0

**Question**

Hello, I'm trying to use into the same Citrus test an HttpClient and a HttpServer as a mock HttpServer, and I also assert things on that mock. Doing so yield the following error:

```
Unable to create endpoint for static endpoint adapter type 'class com.consol.citrus.endpoint.adapter.StaticResponseEndpointAdapter'
com.consol.citrus.exceptions.TestCaseFailedException: Unable to create endpoint for static endpoint adapter type 'class com.consol.citrus.endpoint.adapter.StaticResponseEndpointAdapter'
    at com.consol.citrus.DefaultTestCase.executeAction(DefaultTestCase.java:143)
    at com.consol.citrus.DefaultTestCaseRunner.run(DefaultTestCaseRunner.java:125)
    at com.consol.citrus.GherkinTestActionRunner.then(GherkinTestActionRunner.java:66)
    at HttpTheMockWillAnswerTest.testThatTheMockWillAnswer(HttpTheMockWillAnswerTest.java:48)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
    at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
```

I'm not sure if it's more a bug than a question though. Here's some context on what I'm trying to achieve:

1. A client does a http get on my SUT: http_get(http://sut_hostname/someResource)
2. The SUT is a kind of middelman and will forward the http query to an external server: http_get(http://some_server_hostname/login?username=boo,password=far) 
3. The external server reply by giving a jwt: { token: someBase64Token)
4. The SUT code then use the token to securely query the resource to the same external server: http_get(http://some_server_namename/someResource?token=someBase64Token)

I'm wondering how I can achieve this (or if it's simply out of scope of citrus).

I can easily mock the initial call with an httpClient, and "mock" the external server with a Citrus HttpServer with a StaticResponseEndpointAdapter. But I think it's not made to both serve as a mock and assert things on it:

My assertions will:

1. Test the http client get query, no problem
2. Test the http client first get response with the token, still no problem
3. Test that the external server (http server mock) will receive a http get(http://some_server_hostname/login?username=boo,password=far)
-> boom, I'm receive some exception saying that I cannot use a StaticEndpointAdapter.

**What I've tried so far**

I browsed Citrus samples and documentation, but AFAIK I didn't find a relevant one for this specific use case, I don't really see assertions on both a httpClient and a httpServer on the same test case.

I reproduced the issue [here](https://github.com/benoitdupont/citrus), it will helps on the context.

Can you help/tell me how to it if I'm doing it wrong/ point towards some direction if I can help fix/improve this ? Thanks !

**Additional information**

**Comment by christophd** [comment]
Hello and thank you for the detailed problem description!

Yes, combining a static response adapter with dynamic assertion through the test case is not possible at the moment. So your HttpServer is only able to serve the static response at the moment. Following from that the test is not able to connect to the server in order to handle the request/response dynamically and the error is thrown. 

As a workaround I suggest to also assert the token request in your test and to provide the token response within the test case instead of using the static response adapter.

This is not a perfect solution as I guess you would like to avoid every test to also explicitly assert the token request as an additional step, right?

You could also try to use a customized [DirectEndpointAdapter](https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/com/consol/citrus/endpoint/direct/DirectEndpointAdapter.java) that supports static responses for specific request messages.

**Comment by christophd** [comment]
Please let me know if one of these workarounds is working for you.

In general I think we should support your scenario and make it easy to use as it is a valid use case. This may imply some refactoring on how endpoint adapters are handled on the server component though.

**Comment by benoitdupont** [comment]
Hello, thanks for the quick reply, I will follow-up on your propositions and get back once I played around with it

**Comment by christophd** [comment]
any news?

**Comment by hmmlopez** [comment]
Had similar issue, setting up a test and mocking kecloak and the resource server. I’ve setup the http client and servers as spring beans and injected them in my testcase. So I didn’t use the static response adapter, but manually send server response in my testcase. 
in my scenario I had to test the case that when the resource server responded with a 401 (unauthorized), that my application will try to invalidate and fetch a new token.
These scenarios wouldn’t be possible to test with real applications.

**Comment by bbortt** [comment]
closing as answered.
