### ISSUE TITLE
XMLTestLoader requires citrus instance

### ISSUE THREAD

**Issue by bbortt** [citrusframework/citrus#921]
**Citrus Version**

`v3.4.0`

**Expected behavior**

`XmlTestLoader` does require **either** a `com.consol.citrus.Citrus` **or** `com.consol.citrus.CitrusContext` instance. e.g. the following **should** work:

```java
        XmlTestLoader loader = (XmlTestLoader) new XmlTestLoader(getClass(), testName, "GeneratedApiTest")
            .citrusContext(citrusSpringContext);
        loader.load();
        return loader.getTestCase();
```

**Actual behavior**

instead, this throws an error - `citrus` is null [in `XmlTestLoader`](https://github.com/citrusframework/citrus/blob/7364224dd1e91576ad03c957478b78a8949e82a0/runtime/citrus-xml/src/main/java/com/consol/citrus/xml/XmlTestLoader.java#L95). that is, because the `DefaultTestLoader` does not create `citrus` [when initializing](https://github.com/citrusframework/citrus/blob/7364224dd1e91576ad03c957478b78a8949e82a0/core/citrus-base/src/main/java/com/consol/citrus/common/DefaultTestLoader.java#L125).

I currently have to do the following:

```java
        XmlTestLoader loader = (XmlTestLoader) new XmlTestLoader(getClass(), testName, "GeneratedApiTest")
            .citrus(Citrus.newInstance(new CitrusSpringContextProvider(citrusSpringContext.getApplicationContext())));
        loader.load();
        return loader.getTestCase();
```

**Side note**

while I'm on it I still vow for a "load-and-get" method. combine `DefaultTestLoader#load` and `DefaultTestLoader#getTestCase` into one method.

**Test case sample**

I think the problem i spretty understandable. the implementation should provide a test case, probably.

**Comment by bbortt** [comment]
is this a desired behavior @christophd? because in this particular case mentioned above I should proably use the `SpringXmlTestLoader`.. but, I still think it's a bug, tho.

the SpringXmlTestLoader does also no longer support the "full-params" constructor:

```java
// variant 1
new SpringXmlTestLoader(Class<?> testClass, String testName, String packageName, CitrusContext citrusContext) {
    super(testClass, testName, packageName, citrusContext)
}

// variant 2, probably makes more sense...
new SpringXmlTestLoader(Class<?> testClass, String testName, String packageName, ApplicationContext applicationContext) {
    super(testClass, testName, packageName, new CitrusSpringContextProvider(applicationContext))
}
```

**Comment by christophd** [comment]
yes, `XmlTestLoader` has changed to load pure XML test cases without Spring. The former `XmlTestLoader` has been renamed to `SpringXmlTestLoader`. Sorry, for the missing release notes and notice on this change. I need to make a better job in making these changes public. I assumed that this is an internal API that is not used by the end user.

The idea is to have multiple implementations for the `TestLoader` interface. Currently with 3.4.0 we have

- GroovyTestLoader
- XmlTestLoader
- YamlTestLoader
- SpringXmlTestLoader

The generic Citrus test written in JUnit or TestNG is able to use all of them by having a generic interface to initialize. The test loader to use is determined by resource lookup

```java
TestLoader testLoader = TestLoader.lookup(type)
                .orElseThrow(() -> new CitrusRuntimeException(String.format("Missing test loader for type '%s'", type)));
```

Where `type` is the name of the test loader which is available via resource path lookup. After the lookup users are able to inject loader specific objects via:

```java
CitrusAnnotations.injectAll(testLoader, citrus, testContext);
```

All of this is done automatically when using the Citrus JUnit/TestNG base classes. Of course you can also use the constructors to initialize the loader instance by yourself. In case there is something missing please feel free to add more constructors to the individual test loader implementations. The usual usage is via resource path lookup though so we need some generic initialization mechanism in combination with resource injection as described above.

Hope this clarifies some questions
