### ISSUE TITLE
LoggingClientInterceptor do not print German Umlauts

### ISSUE THREAD

**Issue by chokdee** [citrusframework/citrus#929]
**Citrus Version**
3.4.0

**Expected behavior**
Printing German Umlauts with correct encoding

**Actual behavior**
Printing wrong characters to log

**Test case sample**
handleRequest(getRequestContent(request, new String(body)));

should be 
handleRequest(getRequestContent(request, new String(body, StandardCharsets.UTF_8)));
or even better, use the encoding from the http header

**Comment by bbortt** [comment]
I agree, it should: Respect encoding from HTTP headers or fallback to UTF-8.
