### ISSUE TITLE
GitHub Action is very slow...

### ISSUE THREAD

**Issue by bbortt** [citrusframework/citrus#943]
... and logs a lot! I think one of the reasons the GitHub actions runs so slow might be the very expensive stdout being done. a log level of warning and maybe the tests being run should be sufficient.

**Comment by christophd** [comment]
also consider using [mvnd](https://github.com/apache/maven-mvnd) Maven deamon to run the builds

**Comment by bbortt** [comment]
I don't think that helps in a CI environment, right?

**Comment by apupier** [comment]
in order to have a baseline:

* on the 29th March, the build was taking 19m24s (when it was reported)
* Last build last week, took 17m29s
![image](https://github.com/citrusframework/citrus/assets/1105127/758caed1-03b8-4ce4-9a5d-510bedbbd5ba)


> I don't think that[using mvnd] helps in a CI environment, right?

i do not think it is helping neither

**Comment by bbortt** [comment]
![image](https://github.com/user-attachments/assets/9a9fce2b-e50c-472f-84a6-86f711a3d683)

I will try using parallel builds this evening. I think that'd help a little. although I do think 15 minutes (or 16 that be) is quit ok for a fullbuild.
