### ISSUE TITLE
TransformAction.Builder#xsltFile sets the charset of the xml resource instead of the xslt resource

### ISSUE THREAD

**Issue by picimako** [citrusframework/citrus#965]
**Citrus Version**
4.0.0-M1

**Expected behavior**
During digging in the Citrus code base, I noticed that [TransformAction.Builder#xsltFile(String, String)](https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/org/citrusframework/actions/TransformAction.java#L296) although sets the charset, it is `xmlResourceCharset` that is set, and not `xsltResourceCharset`.

```java
public Builder xsltFile(String xsltResourcePath, String charset) {
    this.xsltResourcePath = xsltResourcePath;
    this.xmlResourceCharset = charset;
    return this;
}
```

**Actual behavior**
I think `xsltFile(String, String)` should set the charset in `xsltResourceCharset` like this:

```java
this.xsltResourceCharset = charset;
```

**Test case sample**

--

**Comment by bbortt** [comment]
nice catch, that would make sense!

**Comment by christophd** [comment]
Many thanks! good one! @picimako would you be able to open a fix PR for this! Much appreciated!

**Comment by picimako** [comment]
@christophd Sure, I'll look into it probably sometime this week.
