### ISSUE TITLE
Enable/disable default test reporters via env var settings

### ISSUE THREAD

**Issue by christophd** [citrusframework/citrus#976]
**User story**
We should allow default test reporters to be enabled/disabled by env var settings. Once disabled the reporter should not even get initialized and log events should not be set to disabled reporters.

**Additional context**
Enable/disable the reporter via env var settings like HTMLReporter is doing (see [HtmlReporter](https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/org/citrusframework/report/HtmlReporter.java#L73))

Find a way to completely remove the reporter from the list of reporters once disabled. So we do not even initialize the reporter and send log events to it once disabled.

Reporters are initialized in [DefaultTestReporters](https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/org/citrusframework/report/DefaultTestReporters.java). So we should make this configurable and enable/disable reporters here in order to not even initialize the disabled ones.

For Spring configuration we can use

```java
@ConditionalOnProperty(
  value="citrus.default.logging.enabled", 
  havingValue = "true", 
  matchIfMissing = true)
```
on the reporter bean to not even initialize the bean based on the env var settings.

**Comment by tschlat** [comment]
Note that the dependency to 

```xml
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>
```

Needs to be added to the project setup in order to accomplish this. 
Ok with this?

**Comment by christophd** [comment]
good point. I would try to avoid adding the dependency. Maybe there is another way to do this without adding Spring Boot
