### ISSUE TITLE
IntelliJ plugin for Citrus

### ISSUE THREAD

**Issue by picimako** [citrusframework/citrus#982]
Hi,

I'm developing an Intellij plugin for Citrus, and I'm planning to release it on the JetBrains Martketplace sometime around the end of September.

@christophd Last week I sent an email to your redhat email address, with some questions (regarding plugin name and logo copyright, and some technical ones), though I'm not sure if you've received it or had the time to check it.
Please let me know if I should send my questions to a different address, on social media, or somewhere else.

I created this issue, so that in case you didn't receive my email, I can still proceed forwarding my questions to you or any of the core developers.

Thank you.

**Comment by christophd** [comment]
Hi, yes I have received that message but did not have time yet to answer properly, sorry. I will do so offline, so closing this one here. many thanks!

**Comment by bbortt** [comment]
@picimako just for your information, we do also have an IntelliJ plugin in our company. it allows starting citrus XML tests like you would do with JUnit tests. once you get the plugin open sourced somewhere, please let us know. will gladly take a look at it!

**Comment by christophd** [comment]
I'd suggest you two join forces to craft the best IntelliJ plugin for Citrus, open available for everyone 😅

**Comment by picimako** [comment]
Hi @christophd,  @bbortt,
In case you are interested, the [plugin](https://plugins.jetbrains.com/plugin/22813-citric) (called Citric) is now published, with some key features mentioned on the Marketplace profile. The full documentation is available [here](https://www.picimako.com/citric/).
