### ISSUE TITLE
Lazy evaluation of Optional fallback values

### ISSUE THREAD

**Issue by picimako** [citrusframework/citrus#997]
Hi!

I noticed that throughout the Citrus project, there are calls to `java.util.Optional#orElse()` with arguments that could be initialized or instantiated in a lazy manner, just to name a few:
- [InputAction](https://github.com/citrusframework/citrus/blob/main/core/citrus-base/src/main/java/org/citrusframework/actions/InputAction.java#L72)
- [KafkaProducer](https://github.com/citrusframework/citrus/blob/main/endpoints/citrus-kafka/src/main/java/org/citrusframework/kafka/endpoint/KafkaProducer.java#L75)

At those places, I think `Optional#orElseGet()` could be used instead.

I'll gladly open a PR, if you too think this could be useful.

**Comment by bbortt** [comment]
sure! wherever the value is not static, `orElseGet` should be used. it will slightly improve performance for sure!

**Comment by picimako** [comment]
Alright. I'll open a PR in the next few days.
