### ISSUE TITLE
variable citrus junitreports directory

### ISSUE THREAD

**Issue by bbortt** [citrusframework/citrus#998]
as reported in https://github.com/citrusframework/citrus/issues/983, the `target/citrus-reports/junitreports/TEST-TestSuite.xml` report path should be adaptable using a property.

**note:** `citrus.html.report.directory=build/citrus-reports` does move the `citrus-test-results.html` file.

**Comment by hmmlopez** [comment]
I've noticed the following, if I set the `citrus.report.directory` property in the **citrus-application.properties** it solves my issue with the reports being generated in target directory when using gradle. I then don't need to specify the specific html/junit/etc location.
For example: `citrus.report.directory=build/citrus-reports`
Maybe it's just worth mentioning this in the documentation where gradle configuration is being explained?

**Comment by bbortt** [comment]
that's a nice catch!

**Comment by hmmlopez** [comment]
We can close this issue as well.
